import type { CommandVisibilityRule } from "./command-runtime.types";
import type { PermissionRequirement } from "./security-runtime.types";

export type MetadataLifecycleState =
  | "draft"
  | "published"
  | "deprecated"
  | "retired";

export type MetadataLayer = "system" | "managed" | "unmanaged";

export type FieldDataType =
  | "string"
  | "multiline-string"
  | "number"
  | "decimal"
  | "currency"
  | "boolean"
  | "date"
  | "time"
  | "datetime"
  | "lookup"
  | "optionset"
  | "multi-optionset"
  | "email"
  | "phone"
  | "url"
  | "json";

export type FieldRequirementLevel = "none" | "recommended" | "required";
export type FieldBehavior = "normal" | "readonly" | "calculated" | "rollup";
export type FormMode = "create" | "edit" | "read";
export type FormColumnCount = 1 | 2 | 3 | 4;
export type FormSectionLayout =
  | "single-column"
  | "two-column"
  | "three-column"
  | "four-column";
export type FormComponentType = "field" | "notes" | "relatedList" | "widget";
export type FormTabType = "fields" | "related_module";
export type WidgetType = "timeline" | "reporting_hierarchy" | (string & {});
export type ViewType = "main" | "lookup" | "subgrid" | "quick-find";
export type SortDirection = "asc" | "desc";
export type RelationshipType = "one-to-many" | "many-to-one" | "many-to-many";
export type RelatedTabLayout =
  | "subgrid"
  | "form-section"
  | "timeline"
  | "custom-slot";

export interface MetadataIdentity {
  readonly id: string;
  readonly logicalName: string;
  readonly displayName: string;
  readonly description?: string;
  readonly version: string;
  readonly lifecycleState: MetadataLifecycleState;
  readonly layer: MetadataLayer;
  readonly solutionName?: string;
  readonly publisherName?: string;
}

export interface OptionSetValueMetadata {
  readonly value: string;
  readonly label: string;
  readonly parentValue?: string;
  readonly color?: string;
  readonly order?: number;
  readonly isDefault?: boolean;
  readonly isActive?: boolean;
}

export interface LookupTargetMetadata {
  readonly entityLogicalName: string;
  readonly primaryNameField?: string;
  readonly viewLogicalName?: string;
  readonly relationshipName?: string;
}

export interface FieldMetadata extends MetadataIdentity {
  readonly entityLogicalName: string;
  readonly dataType: FieldDataType;
  readonly schemaName?: string;
  readonly requirementLevel: FieldRequirementLevel;
  readonly behavior: FieldBehavior;
  readonly isPrimaryName?: boolean;
  readonly isOwner?: boolean;
  readonly isStatus?: boolean;
  readonly isSubStatus?: boolean;
  readonly isSoftDeleteFlag?: boolean;
  readonly isAudited?: boolean;
  readonly isSearchable?: boolean;
  readonly isSortable?: boolean;
  readonly maxLength?: number;
  readonly minLength?: number;
  readonly min?: number;
  readonly max?: number;
  readonly pattern?: string;
  readonly customValidationKey?: string;
  readonly backendFieldName?: string;
  readonly minDate?: string;
  readonly maxDate?: string;
  readonly precision?: number;
  readonly defaultValue?: unknown;
  readonly autoGenerated?: boolean;
  readonly formatSource?: "settings" | "metadata" | "system";
  readonly settingsKey?: string;
  readonly lockedByDefault?: boolean;
  readonly unlockableByCustomization?: boolean;
  readonly options?: readonly OptionSetValueMetadata[];
  readonly lookupTargets?: readonly LookupTargetMetadata[];
  readonly readPermission?: PermissionRequirement;
  readonly writePermission?: PermissionRequirement;
  readonly dependencies?: readonly string[];
  readonly dependsOnFieldId?: string;
  readonly dependencyFilterKey?: string;
  readonly resetOnParentChange?: boolean;
}

export interface EntityMetadata extends MetadataIdentity {
  readonly collectionName: string;
  readonly primaryIdField: string;
  readonly primaryNameField: string;
  readonly ownerField?: string;
  readonly statusField?: string;
  readonly subStatusField?: string;
  readonly softDeleteField?: string;
  readonly routeBase?: string;
  readonly fields: readonly FieldMetadata[];
  readonly defaultFormLogicalName?: string;
  readonly defaultViewLogicalName?: string;
  readonly permissions?: {
    readonly read?: PermissionRequirement;
    readonly create?: PermissionRequirement;
    readonly update?: PermissionRequirement;
    readonly delete?: PermissionRequirement;
    readonly restore?: PermissionRequirement;
    readonly purge?: PermissionRequirement;
  };
  readonly dependencies?: readonly string[];
  readonly relationships?: readonly RelationshipMetadata[];
  readonly relatedTabs?: readonly RelatedTabMetadata[];
  readonly documentProfile?: DocumentProfileMetadata;
}

export interface FormFieldMetadata {
  readonly id?: string;
  readonly fieldLogicalName: string;
  readonly label?: string;
  readonly helpText?: string;
  readonly order: number;
  readonly columnSpan?: number;
  readonly mode?: FormMode;
  readonly isVisible?: boolean;
  readonly isReadonly?: boolean;
  readonly requirementLevel?: FieldRequirementLevel;
  readonly visibilityRuleKey?: string;
}

export interface FormComponentMetadata {
  readonly id: string;
  readonly type: FormComponentType;
  readonly order: number;
  readonly fieldLogicalName?: string;
  readonly relationshipName?: string;
  readonly relatedTabKey?: string;
  readonly widgetId?: string;
  readonly widgetType?: WidgetType;
  readonly height?: number;
  readonly isInitiallyCollapsed?: boolean;
  readonly placementConfig?: Readonly<Record<string, unknown>>;
  readonly label?: string;
  readonly columnSpan?: FormColumnCount;
  readonly isVisible?: boolean;
  readonly isReadonly?: boolean;
  readonly requirementLevel?: FieldRequirementLevel;
  readonly visibilityRuleKey?: string;
  readonly lifecycleState?: MetadataLifecycleState;
}

export interface WidgetMetadata extends MetadataIdentity {
  readonly moduleKey?: string;
  readonly entityLogicalName?: string;
  readonly widgetType: WidgetType;
  readonly isSystem: boolean;
  readonly isCustom: boolean;
  readonly packageId?: string;
  readonly packageName?: string;
  readonly globalConfig?: Readonly<Record<string, unknown>>;
  readonly permission?: PermissionRequirement;
  readonly maxInstancesPerForm?: number;
  readonly allowedModuleKeys?: readonly string[];
}

export interface TimelinePlaceholderMetadata {
  readonly key: string;
  readonly value: string;
  readonly href?: string;
  readonly permission?: PermissionRequirement;
}

export interface TimelineEntryMetadata {
  readonly id: string;
  readonly occurredAt: string;
  readonly template: string;
  readonly category?: string;
  readonly actorDisplayName?: string;
  readonly placeholders?: readonly TimelinePlaceholderMetadata[];
}

export interface FormSectionMetadata {
  readonly id: string;
  readonly tabKey?: string;
  readonly label: string;
  readonly order: number;
  readonly layout: FormSectionLayout;
  readonly columns?: FormColumnCount;
  readonly column?: FormColumnCount;
  readonly columnSpan?: FormColumnCount;
  readonly fields: readonly FormFieldMetadata[];
  readonly components?: readonly FormComponentMetadata[];
  readonly isCollapsible?: boolean;
  readonly isInitiallyCollapsed?: boolean;
  readonly visibilityRuleKey?: string;
  /*
   * Declarative role and permission gating, evaluated by
   * resolveVisibleByRules. Every rule must pass for the section to render.
   */
  readonly visibilityRules?: readonly CommandVisibilityRule[];
}

export interface FormTabMetadata {
  readonly id: string;
  readonly tabKey: string;
  readonly label: string;
  readonly order: number;
  readonly type: FormTabType;
  readonly columns?: FormColumnCount;
  readonly sectionIds?: readonly string[];
  readonly relatedTabKey?: string;
  readonly subgrid?: RelatedSubgridMetadata;
  readonly isVisible?: boolean;
  /* As FormSectionMetadata: every rule must pass for the tab to render. */
  readonly visibilityRules?: readonly CommandVisibilityRule[];
  readonly isDisabled?: boolean;
  readonly disabledReason?: string;
}

export interface FormMetadata extends MetadataIdentity {
  readonly entityLogicalName: string;
  readonly mode: FormMode;
  readonly formType?: "main" | "minimal" | "quickCreate";
  readonly columns?: FormColumnCount;
  readonly tabs?: readonly FormTabMetadata[];
  readonly sections: readonly FormSectionMetadata[];
  readonly commandPlacements?: readonly string[];
  readonly dependencies?: readonly string[];
}

export interface ViewColumnMetadata {
  readonly fieldLogicalName: string;
  readonly label?: string;
  readonly order: number;
  readonly width?: number;
  readonly isSortable?: boolean;
  readonly isHidden?: boolean;
}

export interface ViewSortMetadata {
  readonly fieldLogicalName: string;
  readonly direction: SortDirection;
}

export interface ViewFilterMetadata {
  readonly fieldLogicalName: string;
  readonly operator: string;
  readonly value?: unknown;
}

export interface ViewMetadata extends MetadataIdentity {
  readonly viewKey?: string;
  readonly viewId?: string;
  readonly entityLogicalName: string;
  readonly type: ViewType;
  readonly columns: readonly ViewColumnMetadata[];
  readonly defaultSort?: readonly ViewSortMetadata[];
  readonly filters?: readonly ViewFilterMetadata[];
  readonly pageSize?: number;
  readonly commandPlacements?: readonly string[];
  readonly dependencies?: readonly string[];
  readonly permission?: PermissionRequirement;
  readonly isDefault?: boolean;
  readonly isSystem?: boolean;
  readonly isCustom?: boolean;
  readonly isPublished?: boolean;
  readonly visibilityScope?: "private" | "team" | "tenant" | "global";
}

export interface RelationshipMetadata extends MetadataIdentity {
  readonly relationshipName: string;
  readonly type: RelationshipType;
  readonly sourceEntityLogicalName: string;
  readonly targetEntityLogicalName: string;
  readonly parentEntityLogicalName?: string;
  readonly relatedEntityLogicalName?: string;
  readonly sourceFieldLogicalName?: string;
  readonly targetFieldLogicalName?: string;
  readonly lookupFieldLogicalName?: string;
  readonly displayFieldLogicalName?: string;
  readonly columns?: readonly ViewColumnMetadata[];
  readonly filters?: readonly ViewFilterMetadata[];
  readonly defaultSort?: readonly ViewSortMetadata[];
  readonly cascadeDelete?: "none" | "soft-delete" | "restrict";
}

export interface RelatedFieldMetadata {
  readonly fieldLogicalName: string;
  readonly relatedEntityLogicalName: string;
  readonly relationshipName: string;
  readonly displayFieldLogicalName?: string;
  readonly label?: string;
  readonly order?: number;
}

export interface RelatedSubgridMetadata {
  readonly id: string;
  readonly relationshipName: string;
  readonly entityLogicalName: string;
  readonly relatedEntityLogicalName?: string;
  readonly viewLogicalName?: string;
  readonly title: string;
  readonly columns?: readonly ViewColumnMetadata[];
  readonly filters?: readonly ViewFilterMetadata[];
  readonly defaultSort?: readonly ViewSortMetadata[];
  /** Base route used to open related records from read-only subgrids. */
  readonly routeBase?: string;
  readonly pageSize?: number;
  readonly emptyStateTitle?: string;
  readonly emptyStateDescription?: string;
  readonly quickCreateFields?: readonly {
    readonly fieldLogicalName: string;
    readonly label?: string;
    readonly dataType: FieldDataType;
    readonly required?: boolean;
    readonly maxLength?: number;
    readonly options?: readonly OptionSetValueMetadata[];
  }[];
  readonly assignment?: {
    readonly lookupFieldLogicalName: string;
    readonly optionsPath: string;
    readonly title?: string;
    readonly optionValueField?: string;
    readonly optionLabelField?: string;
    readonly optionDescriptionField?: string;
    readonly optionMetaFields?: readonly string[];
    readonly assignedValueField?: string;
    readonly extraBooleanField?: {
      readonly fieldLogicalName: string;
      readonly label: string;
      readonly defaultValue?: boolean;
    };
    readonly extraFields?: readonly {
      readonly fieldLogicalName: string;
      readonly label: string;
      readonly dataType: FieldDataType;
      readonly required?: boolean;
      readonly maxLength?: number;
      readonly defaultValue?: unknown;
      readonly options?: readonly OptionSetValueMetadata[];
    }[];
  };
  /** Metadata-owned transport contract. Tokens: {parentId}, {recordId}. */
  readonly api?: {
    readonly listPath: string;
    readonly createPath?: string;
    readonly updatePath?: string;
    readonly deletePath?: string;
    readonly permissions?: {
      readonly create?: string | readonly string[];
      readonly update?: string | readonly string[];
      readonly delete?: string | readonly string[];
    };
  };
}

export interface RelatedTabMetadata {
  readonly id: string;
  readonly tabKey: string;
  readonly label: string;
  readonly order: number;
  readonly layout: RelatedTabLayout;
  readonly relationshipName?: string;
  readonly subgrid?: RelatedSubgridMetadata;
  readonly relatedFields?: readonly RelatedFieldMetadata[];
  readonly permission?: PermissionRequirement;
  readonly isVisible?: boolean;
  readonly isDisabled?: boolean;
  readonly disabledReason?: string;
}

export interface DocumentTypeMetadata {
  readonly id: string;
  readonly key: string;
  readonly displayName: string;
  readonly isRequired?: boolean;
  readonly isActive?: boolean;
  readonly allowedExtensions?: readonly string[];
  readonly maxFileSizeBytes?: number;
}

export interface DocumentProfileMetadata {
  readonly id: string;
  readonly moduleKey: string;
  readonly enabled: boolean;
  readonly relationshipName: string;
  readonly documentTypes: readonly DocumentTypeMetadata[];
  readonly permission?: PermissionRequirement;
}
