import type {
  EntityMetadata,
  FieldMetadata,
  FormFieldMetadata,
  FormMetadata,
} from "./metadata-runtime.types";

export type RuntimeFieldValue =
  | string
  | number
  | boolean
  | readonly string[]
  | null
  | undefined;

export type RuntimeFormValues = Readonly<Record<string, RuntimeFieldValue>>;

export interface RuntimeFormValidationResult {
  readonly isValid: boolean;
  readonly errors: Record<string, string[]>;
}

export function validateRuntimeForm({
  entity,
  form,
  values,
}: {
  readonly entity: EntityMetadata;
  readonly form: FormMetadata;
  readonly values: RuntimeFormValues;
}): RuntimeFormValidationResult {
  const fieldsByName = new Map(
    entity.fields.map((field) => [field.logicalName, field]),
  );
  const errors: Record<string, string[]> = {};

  for (const formField of visibleFormFields(form)) {
    const field = fieldsByName.get(formField.fieldLogicalName);
    if (!field || shouldSkipField(field)) continue;

    const fieldErrors = validateField({
      field,
      formField,
      value: values[field.logicalName],
    });

    if (fieldErrors.length) {
      errors[field.logicalName] = fieldErrors;
    }
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
}

export function mapBackendFieldErrors({
  errors,
  fieldMap = {},
}: {
  readonly errors: unknown;
  readonly fieldMap?: Readonly<Record<string, string>>;
}): Record<string, string[]> {
  const mapped: Record<string, string[]> = {};

  if (!errors || typeof errors !== "object") return mapped;

  for (const [fieldName, messages] of Object.entries(
    errors as Record<string, unknown>,
  )) {
    const runtimeField = fieldMap[fieldName] ?? fieldName;
    const normalizedMessages = Array.isArray(messages)
      ? messages.map(String)
      : [String(messages)];

    mapped[runtimeField] = [
      ...(mapped[runtimeField] ?? []),
      ...normalizedMessages,
    ];
  }

  return mapped;
}

function validateField({
  field,
  formField,
  value,
}: {
  readonly field: FieldMetadata;
  readonly formField: FormFieldMetadata;
  readonly value: RuntimeFieldValue;
}) {
  const errors: string[] = [];
  const label = formField.label ?? field.displayName;
  const required =
    formField.requirementLevel === "required" ||
    field.requirementLevel === "required";
  const stringValue = typeof value === "string" ? value.trim() : "";

  if (required && isEmptyValue(value)) {
    errors.push(`${label} is required.`);
  }

  if (stringValue) {
    if (field.minLength && stringValue.length < field.minLength) {
      errors.push(`${label} must be at least ${field.minLength} characters.`);
    }

    if (field.maxLength && stringValue.length > field.maxLength) {
      errors.push(`${label} must be ${field.maxLength} characters or fewer.`);
    }

    if (field.dataType === "email" && !isValidEmail(stringValue)) {
      errors.push(`${label} must be a valid email address.`);
    }

    if (field.pattern) {
      const pattern = new RegExp(field.pattern);
      if (!pattern.test(stringValue)) {
        errors.push(`${label} has an invalid format.`);
      }
    }
  }

  if (typeof value === "number") {
    if (field.min !== undefined && value < field.min) {
      errors.push(`${label} must be at least ${field.min}.`);
    }

    if (field.max !== undefined && value > field.max) {
      errors.push(`${label} must be no more than ${field.max}.`);
    }
  }

  return errors;
}

function visibleFormFields(form: FormMetadata) {
  return form.sections
    .filter((section) => !section.visibilityRuleKey)
    .flatMap((section) =>
      section.fields.filter(
        (field) => field.isVisible !== false && !field.visibilityRuleKey,
      ),
    );
}

function shouldSkipField(field: FieldMetadata) {
  return Boolean(
    field.autoGenerated &&
    field.lockedByDefault &&
    field.defaultValue === undefined &&
    field.formatSource,
  );
}

function isEmptyValue(value: RuntimeFieldValue) {
  if (value === null || value === undefined) return true;
  if (typeof value === "string") return value.trim().length === 0;
  if (Array.isArray(value)) return value.length === 0;
  return false;
}

function isValidEmail(value: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}
