def load(p):
    raw = open(p, encoding='utf-8', newline='').read()
    return raw.replace('\r\n', '\n'), ('\r\n' in raw)

def save(p, s, crlf):
    open(p, 'w', encoding='utf-8', newline='').write(s.replace('\n', '\r\n') if crlf else s)

p = 'scripts/rebuild-qa.mjs'
s, crlf = load(p)

BLOCK = '''
// ------------------------------------------------------- the generated graph

/*
 * GRAPH_ORPHANS, and why this block exists.
 *
 * A generated note can have a perfectly valid canonical source and still be an
 * isolated dot in the Obsidian graph — no inbound link, no outbound link,
 * unreachable by anything except search. Measured on 2026-08-18, 82 of 95 QA
 * scenarios were exactly that, and so were every plan and the regression index:
 * 102 isolated nodes out of 294 generated ones.
 *
 * The relationships were not missing. They were sitting in frontmatter — AREA,
 * RELATED_BUGS, RELATED_REGRESSIONS — where Obsidian cannot see them, because a
 * YAML value is not a wikilink.
 *
 * So this projects the relationships that ALREADY EXIST into links. It invents
 * nothing:
 *   - every scenario belongs to the plan covering its AREA. That mapping is
 *     already validated — `loadQaRecords` refuses a scenario whose AREA has no
 *     plan — so the edge is guaranteed to resolve.
 *   - RELATED_BUGS and RELATED_REGRESSIONS become links to those records.
 *   - AREA becomes a module link only on an EXACT match with a module note.
 *     Fuzzy matching was rejected: "commercial-onboarding" is not
 *     "commercial-onboarding-lifecycle", and a plausible-looking wrong edge is
 *     worse than an absent one.
 *
 * The block is delimited and rewritten in place. Everything outside the markers
 * is hand-authored and never touched.
 */
const GRAPH_BEGIN = '<!-- GRAPH:BEGIN — generated by scripts/rebuild-qa.mjs; edit the frontmatter, not this block -->';
const GRAPH_END = '<!-- GRAPH:END -->';

const moduleNoteNames = new Set(
  existsSync(join(ROOT, 'docs/knowledge/modules'))
    ? readdirSync(join(ROOT, 'docs/knowledge/modules'))
        .filter((name) => name.endsWith('.md') && name !== 'README.md')
        .map((name) => name.replace(/\\.md$/, ''))
    : [],
);

const planByArea = new Map(sortedPlans.map((plan) => [plan.area, plan]));

function graphBlockFor(record, kind) {
  const lines = [GRAPH_BEGIN, '', '## Related', ''];
  const rows = [];

  if (kind === 'scenario') {
    const plan = planByArea.get(record.area);
    if (plan) rows.push(`- Test plan — [[${plan.id}]]`);
  } else {
    const owned = (byArea.get(record.area) ?? []).slice().sort((a, b) => a.id.localeCompare(b.id));
    if (owned.length) {
      rows.push(`- Scenarios — ${owned.map((scenario) => `[[${scenario.id}]]`).join(', ')}`);
    }
  }

  if (moduleNoteNames.has(record.area)) rows.push(`- Module — [[${record.area}]]`);
  if (record.bugs?.length) rows.push(`- Bugs — ${record.bugs.map((id) => `[[${id}]]`).join(', ')}`);
  if (record.regressions?.length) {
    rows.push(`- Regressions — ${record.regressions.map((id) => `[[${id}]]`).join(', ')}`);
  }

  if (!rows.length) {
    rows.push(
      '- `STANDALONE_ALLOWED` — no plan, module, bug or regression relationship is',
      '  declared in this record\\'s frontmatter. Declare one rather than adding a',
      '  link here by hand.',
    );
  }

  lines.push(...rows, '', GRAPH_END);
  return lines.join('\\n');
}

function withGraphBlock(body, block) {
  const start = body.indexOf(GRAPH_BEGIN);
  if (start === -1) return `${body.replace(/\\s*$/, '')}\\n\\n${block}\\n`;
  const end = body.indexOf(GRAPH_END, start);
  if (end === -1) return `${body.slice(0, start).replace(/\\s*$/, '')}\\n\\n${block}\\n`;
  return `${body.slice(0, start)}${block}${body.slice(end + GRAPH_END.length)}`;
}

const graphTargets = [
  ...sortedScenarios.map((record) => ({ record, kind: 'scenario' })),
  ...sortedPlans.map((record) => ({ record, kind: 'plan' })),
];

for (const { record, kind } of graphTargets) {
  const current = readFileSync(record.path, 'utf8');
  const normalised = current.replace(/\\r\\n/g, '\\n');
  const next = withGraphBlock(normalised, graphBlockFor(record, kind));
  if (next === normalised) continue;
  if (CHECK_ONLY) {
    drift.push(record.relative);
    continue;
  }
  writeFileSync(record.path, current.includes('\\r\\n') ? next.replace(/\\n/g, '\\r\\n') : next);
  changed += 1;
  console.log(`  rewrote  ${record.relative} (graph block)`);
}

'''

anchor = '''if (CHECK_ONLY) {
  if (drift.length) {'''
assert anchor in s, 'anchor'
s = s.replace(anchor, BLOCK.lstrip('\n') + anchor, 1)
save(p, s, crlf)
print('rebuild-qa.mjs: generated graph block added')
