export const TENANT_SETTING_CATEGORIES = [
  'organization',
  'employees',
  'access',
  'leave',
  'attendance',
  'timesheets',
  'payroll',
  'recruitment',
  'documents',
  'branding',
  'notifications',
  'security',
  'system',
] as const;

export type TenantSettingCategory = (typeof TENANT_SETTING_CATEGORIES)[number];

export type TenantSettingDefaults = Record<
  TenantSettingCategory,
  Record<string, boolean | number | string | null>
>;

export const DEFAULT_TENANT_SETTINGS: TenantSettingDefaults = {
  organization: {
    tenantDisplayName: '',
    companyDisplayName: '',
    legalBusinessName: '',
    industry: '',
    businessEmail: '',
    businessPhone: '',
    websiteUrl: '',
    timezone: 'UTC',
    currency: 'USD',
    country: '',
    dateFormat: 'MM/dd/yyyy',
    timeFormat: '12h',
    weekStartsOn: 'MONDAY',
    companySize: '',
    businessDateSource: 'TENANT_TIMEZONE',
    businessDateTimezone: 'UTC',
    businessDayStartTime: '00:00',
    allowManualBusinessDateOverride: false,
    manualBusinessDate: '',
    lockPastBusinessDates: true,
  },
  employees: {
    employeeIdPrefix: 'EMP',
    employeeIdSequenceLength: 4,
    autoGenerateEmployeeId: true,
    defaultEmployeeStatus: 'ACTIVE',
    requirePersonalEmail: false,
    requireEmergencyContact: true,
    requireJoiningDate: true,
    requireCountry: false,
    requireBusinessUnit: false,
    requireDepartment: false,
    requireDesignation: false,
    requireEmployeeLevel: false,
    requireReportingManager: false,
    requireWorkLocation: false,
    requireWorkCalendar: false,
    requireWorkSchedule: false,
    defaultEmploymentType: 'FULL_TIME',
    defaultWorkMode: 'OFFICE',
    autoCreateDraftOnHire: true,
    keepEmployeeAsDraftUntilOnboardingComplete: true,
    preventActivationUntilMandatoryFieldsCompleted: true,
    maxReportingLevels: 5,
    maximumDirectReports: 20,
    allowSkipLevelApprovals: false,
    allowMatrixReporting: false,
    allowEmployeeWithoutManager: true,
    validateReportingHierarchy: true,
    preventCircularReporting: true,
    preventDuplicateByPersonalEmail: true,
    preventDuplicateWorkEmail: true,
    preventDuplicateByPhoneNumber: false,
    preventDuplicateByNationalId: false,
    preventDuplicatePassport: false,
    preventDuplicateEmployeeId: true,
    warnOnPossibleDuplicate: true,
    onboardingChecklistTemplate: 'standard',
  },
  access: {
    allowDirectPermissions: true,
    allowCustomRoles: true,
    defaultManagerRoleKey: 'manager',
    defaultEmployeeRoleKey: 'employee',
    lockSystemRoles: true,
  },
  leave: {
    defaultApprovalFlow: 'manager_then_hr',
    allowHalfDayRequests: true,
    documentReminderAfterDays: 3,
    defaultCarryForwardEnabled: false,
    defaultHolidayCalendarName: 'Company Calendar',
    allowManualLeaveMarking: true,
  },
  attendance: {
    defaultGraceMinutes: 10,
    allowManualAdjustments: true,
    autoCheckOutEnabled: false,
    trackMissedCheckOut: true,
    allowedModes: 'OFFICE,REMOTE,HYBRID',
    enforceOfficeLocationForOfficeMode: true,
    requireRemoteLocationCapture: true,
    locationCaptureRequired: true,
    locationRequiredForModes: 'OFFICE,REMOTE,HYBRID',
    allowIpFallback: false,
    allowManualLocationException: false,
    locationTimeoutSeconds: 15,
    locationRetryAttempts: 2,
    highAccuracyLocation: true,
    maxAllowedAccuracyMeters: null,
    captureLocationOnCheckIn: true,
    captureLocationOnCheckOut: true,
    storeIpAddress: false,
    storeUserAgent: false,
    standardWorkHoursPerDay: 8,
    allowEarlyCheckIn: true,
    earliestCheckInMinutesBeforeShift: 30,
    allowLateCheckOut: true,
    maximumWorkingHoursPerDay: 16,
    minimumWorkingHoursPerDay: 1,
    enforceWorkSiteGeofence: false,
    maximumAllowedDistanceMeters: 100,
    outsideGeofenceAction: 'WARN',
    requireWorkSiteOnOfficeAttendance: false,
    noAssignedScheduleBehavior: 'ALLOW_MANUAL_ATTENDANCE',
    requireReasonForOffdayHolidayCheckIn: true,
    allowManualAttendanceAdjustments: true,
    employeesCanRequestCorrection: true,
    managerCanApproveCorrection: true,
    hrCanOverrideAttendance: true,
    correctionRequiresReason: true,
    correctionRequiresAttachment: false,
    maximumCorrectionAgeDays: 30,
    detectMockLocation: true,
    rejectMockLocation: false,

    // --- Attendance Integration Platform -----------------------------------
    // Added to the existing attendance category rather than a new one, so these
    // resolve through the same tenant -> organization override chain as every
    // other setting instead of a parallel configuration system.
    //
    // Two settings the platform needs already exist above and are reused rather
    // than duplicated:
    //   Maximum Accepted GPS Accuracy -> maxAllowedAccuracyMeters
    //   Default Geofence Radius       -> maximumAllowedDistanceMeters
    integrationEnabled: false,
    defaultSyncMode: 'POLL',
    defaultDevicePollIntervalMinutes: 30,
    /// Floor for connectors that re-read the whole history on every poll. A
    /// connector may declare a higher minimum; the stricter of the two wins.
    minimumLegacyPollIntervalMinutes: 15,
    /// Terminals keep their own clock and DijiPeople never sets it. Drift is
    /// reported as a health signal so an operator can correct the device before
    /// punch timestamps become untrustworthy.
    deviceClockDriftWarningSeconds: 60,
    deviceClockDriftCriticalSeconds: 300,
    /// Gateway runtime cadence. Sent to the gateway with its configuration so a
    /// tenant can slow a chatty install down without redeploying the service.
    gatewayHeartbeatIntervalSeconds: 60,
    gatewayConfigRefreshSeconds: 300,
    /// Punches per upload request. The ingestion endpoint accepts up to 5000;
    /// the gateway default stays well under it so one failure retries cheaply.
    gatewayUploadBatchSize: 500,
    webAttendancePolicy: 'ALLOWED',
    officeWebAttendancePolicy: 'ALLOWED',
    webFallbackPolicy: 'ALLOW_WHEN_DEVICE_UNAVAILABLE',
    deviceProvisioningEnabled: false,
    automaticEmployeeProvisioning: false,
    automaticEmployeeDeactivation: false,
    provisioningMaxRetries: 3,
    provisioningRetryIntervalMinutes: 15,
    /// How to treat a device punch and a web punch covering the same period.
    attendanceConflictPolicy: 'PREFER_DEVICE',
    /// Hybrid is a derived daily outcome, never a raw event classification.
    hybridAttendancePolicy: 'DERIVE_FROM_SESSIONS',

    // --- Attendance Engine (reconciliation) --------------------------------
    // Each of these is consumed by the reconciliation engine. Nothing
    // speculative: a setting with no reader is a setting nobody can trust.
    //
    /// The engine only reconciles days on or after this date. Existing tenants
    /// carry years of AttendanceEntry rows with no raw events behind them, and
    /// rebuilding those would replace real history with an empty calculation.
    attendanceEngineEffectiveFrom: '',
    /// Two punches on the same reader this close together are one intent. Every
    /// raw event is still stored; only session building ignores the repeat.
    semanticDuplicateWindowSeconds: 30,
    /// What happens when a new work period starts before the previous one closed.
    /// The default keeps both facts and asks a human, because "they forgot to
    /// check out" and "the reader fired twice" need different corrections.
    workModeTransitionPolicy: 'CREATE_EXCEPTION',
    /// Close an unterminated session at the scheduled shift end. Off by default:
    /// an invented check-out is indistinguishable downstream from a real one,
    /// and it is paid.
    autoCloseMissingCheckoutAtShiftEnd: false,
    /// A work period that starts at one authorised site and ends at another.
    crossSiteAttendancePolicy: 'WARNING',
    /// How to read devices that do not reliably report direction. ALTERNATING
    /// needs no vendor code mapping, which is why it is the default.
    defaultPunchDirectionStrategy: 'ALTERNATING',
    /// Whether the gap between two work periods is an unpaid break. Off by
    /// default: a gap may be lunch, or travel between sites on work time.
    treatSessionGapsAsBreaks: false,
    /// Extra time below this is not proposed as overtime at all.
    overtimeMinimumMinutes: 30,
    /// Flags attendance recorded in two places too far apart to have travelled
    /// between. A risk signal for review only: it never rejects attendance,
    /// alters sessions or reduces worked time.
    impossibleTravelDetectionEnabled: true,
    /// Below this separation nothing is flagged, so GPS noise between two nearby
    /// readings cannot manufacture an alert.
    impossibleTravelMinimumDistanceKm: 100,
    /// Above this implied average speed the movement is treated as implausible.
    /// Set beyond a commercial airliner so ordinary travel never trips it.
    impossibleTravelMaximumSpeedKph: 500,
  },
  timesheets: {
    enableTimesheetModule: true,
    timesheetRequired: true,
    timesheetPeriodType: 'monthly',
    entryMode: 'HOURS',
    weekendDays: 'SATURDAY,SUNDAY',
    defaultWorkHours: 8,
    defaultHoursForOnWork: 8,
    allowWeekendWork: true,
    allowHolidayWork: true,
    requireMonthlySubmission: true,
    requireMONTHLYSubmission: true,
    autoFillWorkingDays: false,
    requireAllDaysCompletedBeforeSubmit: true,
    requireSubmissionNote: false,
    allowBulkImport: true,
    allowEmployeeSelfImport: false,
    allowManagerImportForTeam: true,
    requireApprovalBeforePayroll: true,
    generatePayrollInputsAutomatically: false,
    includeOvertimeInPayrollExport: true,
    includeLeaveInPayrollExport: true,
    includeHolidaysInPayrollExport: true,
    includeUnpaidTimeInPayrollExport: true,
    exportTemplateFormat: 'XLSX',
    lockTimesheetAfterApproval: true,
    allowRejectedTimesheetResubmission: true,
    submissionDeadlineDaysAfterPeriodEnd: 5,
    managerApprovalDeadlineDays: 5,
    allowFutureEntries: false,
    maximumBackdatedDays: 30,
    defaultPolicyId: '',
    requirePolicyAssignment: false,
    allowEmployeeExemption: true,
    policyEffectiveDateMode: 'ENTRY_DATE',
    generateNextMonthAutomatically: true,
    generationLeadDays: 7,
    visiblePastMonths: 12,
    visibleFutureMonths: 1,
    weekStartDay: 'MONDAY',
    enableCurrentWeekOnly: true,
    allowPreviousIncompleteWeek: true,
    allowPreviousOverdueWeek: true,
    allowPreviousRejectedWeek: true,
    allowFutureWeekEntry: false,
    futureWeeksAllowed: 0,
    weeklySubmissionRequired: true,
    weeklySubmissionDeadlineDay: 'MONDAY',
    weeklySubmissionDeadlineTime: '12:00',
    submissionGracePeriodHours: 0,
    allowLateSubmission: true,
    allowPayrollLateSubmissionOverride: true,
    requireLateSubmissionReason: true,
    autoCompleteLeaveOnlyWeek: true,
    autoSubmitLeaveOnlyWeek: false,
    lockWeekOnSubmission: true,
    lockWeekOnApproval: true,
    allowWithdrawalBeforeApproval: true,
    requireWorkSchedule: false,
    missingScheduleBehavior: 'TENANT_DEFAULT',
    includeEmploymentDates: true,
    lockSystemClassifiedDays: true,
    minimumEntryMinutes: 15,
    entryMinuteIncrement: 15,
    maximumHoursPerDay: 24,
    preventOverlappingEntries: true,
    requireEntryNotes: false,
    requireNotesOverHours: 12,
    allowCopyPreviousWeek: true,
    allowTimerEntries: false,
    attendanceIntegrationMode: 'ATTENDANCE_PREFILL',
    preventHoursAboveAttendance: false,
    varianceToleranceMinutes: 15,
    varianceTolerancePercent: 5,
    requireVarianceReason: true,
    includeAttendanceCorrections: true,
    attendanceConflictBehavior: 'WARN',
    includeApprovedLeave: true,
    includePartialLeave: true,
    lockApprovedLeave: true,
    recalculateRetroactiveLeave: true,
    pendingLeaveBehavior: 'WARN',
    includeScopedHolidays: true,
    requireHolidayWorkReason: true,
    requireHolidayWorkApproval: true,
    holidayHoursCategory: 'OVERTIME',
    requireProject: true,
    allowNonProjectTime: false,
    allowUnassignedProjectEntry: false,
    allocationValidation: 'WARN',
    requireProjectManagerApproval: false,
    allowNonBillableActivity: true,
    requireTask: false,
    requireCostCenter: false,
    requireWorkItemReference: false,
    approvalScope: 'WEEK',
    defaultApproverSource: 'APPROVAL_MATRIX',
    requireProjectApproval: false,
    requireHrApproval: false,
    requirePayrollApproval: false,
    approvalSlaHours: 48,
    allowDelegation: true,
    enableApprovalEscalation: true,
    payrollUsage: 'NOT_USED',
    approvedTimesheetsOnly: true,
    includeRegularHoursInPayroll: true,
    includeWeekendHoursInPayroll: true,
    includeBillableHoursInPayroll: true,
    includeNonBillableHoursInPayroll: true,
    payrollCutoffDay: 25,
    preventReopenAfterPayroll: true,
    allowPayrollAdjustment: true,
    lockWeekAfterPayrollExport: true,
    requireReopeningApproval: true,
    maximumReopeningPeriodDays: 30,
    allowEmployeeReopeningRequest: true,
    allowManagerReopeningRequest: true,
    allowHrReopening: true,
    allowPayrollReopening: false,
    requirePayrollAdjustmentAfterReopening: true,
    restrictReopeningToSpecifiedEntries: false,
    autoExpireReopeningDays: 7,
    reapprovalBehavior: 'FULL_WORKFLOW',
    enableMissingTimesheetWarnings: true,
    warningAfterDays: 1,
    enableAccessRestrictions: false,
    restrictionMode: 'WARNING_ONLY',
    restrictionAfterDays: 7,
    restrictionExpiryDays: 7,
    excludedRoleKeys: '',
    excludedEmployeeIds: '',
    restrictionAllowedModules: 'timesheets,notifications,profile,help,support',
    allowTimesheetsDuringRestriction: true,
    allowNotificationsDuringRestriction: true,
    allowProfileDuringRestriction: true,
    allowHelpDuringRestriction: true,
    emergencyOverrideEnabled: true,
    managerRestrictionExemption: false,
    hrRestrictionExemption: true,
    temporaryOverrideExpiryHours: 24,
    restrictionMessage:
      'Your timesheet is overdue. Complete and submit it to restore normal access.',
    excludeApprovedLeave: true,
    excludePendingApproval: true,
    allowNotifications: true,
    submissionReminderEnabled: true,
    approvalReminderEnabled: true,
    overdueNotificationEnabled: true,
    rejectionNotificationEnabled: true,
    reopeningNotificationEnabled: true,
    payrollNotificationEnabled: true,
    reminderSchedule: 'P1D',
    escalationSchedule: 'P2D',
    largeExportRowThreshold: 5000,
    exportRetentionDays: 7,
    sanitizeSpreadsheetValues: true,
    auditEntryChanges: true,
    auditPolicyResolution: true,
    auditExports: true,
    auditBackgroundJobs: true,
    retentionYears: 7,
    requireChangeReasonAfterApproval: true,
  },
  payroll: {
    payFrequency: 'MONTHLY',
    payrollStatus: 'ACTIVE',
    defaultPayrollGroup: 'main',
    defaultPaymentMode: 'BANK_TRANSFER',
    compensationReviewCycle: 'ANNUAL',
    defaultCurrency: 'USD',
    defaultPayrollRegionId: '',
    defaultPayrollCalendarId: '',
    defaultCompensationPackageId: '',
    defaultTaxPolicyId: '',
    defaultPostingProfileId: '',
    defaultEmployerBankAccountId: '',
    defaultPaymentAccountId: '',
    defaultPayrollCurrencySource: 'TENANT_DEFAULT',
    allowMultiCurrencyPayroll: false,
    exchangeRateSource: 'MANUAL',
    exchangeRateLockPoint: 'PAYROLL_RUN_CREATION',
    payrollGenerationSource: 'ATTENDANCE',
    requireApprovedTimesheetsForPayroll: true,
    requireApprovedAttendanceForPayroll: true,
    requireApprovedLeavesForPayroll: true,
    requireEmployeePayrollBankAccount: false,
    requireEmployeeProjectAllocation: false,
    activeEmployeeContractAction: 'BLOCK',
    activeCompensationAssignmentAction: 'BLOCK',
    activeTaxProfileAction: 'WARN',
    payrollBankAccountAction: 'WARN',
    approvedAttendanceAction: 'BLOCK',
    approvedTimesheetsAction: 'BLOCK',
    approvedLeaveAction: 'BLOCK',
    approvedOvertimeAction: 'BLOCK',
    projectAllocationAction: 'WARN',
    resolvedPostingRulesAction: 'BLOCK',
    validPayrollCalendarAction: 'BLOCK',
    validPayrollPeriodAction: 'BLOCK',
    duplicatePeriodAction: 'BLOCK',
    negativeNetPayAction: 'BLOCK',
    payrollApprovalAction: 'BLOCK',
    missingExchangeRateAction: 'BLOCK',
    baseReportingCurrency: 'USD',
    roundingMethod: 'HALF_UP',
    currencyPrecision: 2,
    calculationSequenceProfile: 'STANDARD',
    prorationMethod: 'CALENDAR_DAYS',
    partialMonthMethod: 'DAILY_RATE',
    workingDaysSource: 'PAYROLL_CALENDAR',
    taxCalculationMode: 'PERIODIC',
    ytdRecalculationEnabled: true,
    retroactiveCalculationEnabled: true,
    manualAdjustmentAllowed: true,
    calculationPrecision: 2,
    roundingDifferenceComponentId: '',
    negativeNetPayHandling: 'BLOCK',
    underAllocationAction: 'WARN',
    overAllocationAction: 'WARN',
    defaultBenchCostCenterId: '',
    allocationSource: 'EMPLOYEE_PROJECT_ALLOCATIONS',
    projectCostPostingBehavior: 'ALLOCATE_NET_PAY',
    includeLeavesInPayrollSummary: true,
    includeHolidaysInPayrollSummary: true,
    includeWeekendWorkInPayrollSummary: true,
    defaultPayrollCycleDay: 25,
    allowDraftPayrollAdjustments: true,
    payrollExportFormat: 'CSV',
    bankPaymentFileFormat: 'GENERIC_BANK_TRANSFER',
    paymentReferenceFormat: 'PAY-{RUN}-{EMPLOYEE}',
    payslipTemplate: 'STANDARD',
    payslipTemplateId: '',
    taxStatementTemplateId: '',
    publishPayslipAfterApproval: false,
    payslipPasswordProtection: false,
    requireEmployeePayslipAcknowledgment: false,
    requirePayrollApproval: true,
    lockAfterApproval: true,
    allowPayrollRegeneration: false,
    allowPayrollReopening: false,
    reopeningPermission: 'payroll-runs.reopen',
    reversalRequirement: 'REASON_REQUIRED',
    enableGlPosting: true,
    postingDateSource: 'PAYROLL_PERIOD',
    journalGrouping: 'CONSOLIDATED_PAYROLL',
    journalExportFormat: 'CSV',
    autoPostAfterApproval: false,
    requireBalancedJournal: true,
    allowReversalPosting: true,
    payslipFormat: 'PDF',
    emailPayslipOnPublish: false,
  },
  recruitment: {
    defaultRecruitmentPipelineId: '',
    defaultCandidateNumberRuleId: '',
    defaultCandidateSourceId: '',
    candidateRetentionPolicyId: '',
    duplicateCandidateDetection: true,
    duplicateMatchingStrategy: 'EMAIL_MOBILE',
    automaticallyParseSkillsAndExperience: true,
    automaticallyCreateCandidateAfterCvUpload: true,
    automaticallyMoveRejectedCandidatesToTalentPool: true,
    onboardingWorkflow: 'standard',
    defaultOnboardingPlanId: '',
    autoCreateEmployeeFromCandidate: true,
    automaticallyActivateEmployeeAfterSuccessfulOnboarding: false,
    defaultRecruiterAssignmentRuleId: '',
    defaultHiringManagerAssignmentRuleId: '',
    defaultInterviewPanelRuleId: '',
    onboardingChecklistTemplate: 'standard',
    automaticallyStartOnboardingAfterHiring: true,
    requireMandatoryOnboardingTasksBeforeActivation: true,
    requireOfferApprovalBeforeHiring: false,
    requireBackgroundVerificationBeforeHiring: false,
    requireDocumentVerificationBeforeEmployeeActivation: true,
    candidateDocumentChecklistId: '',
    mandatoryEmployeeDocumentChecklistId: '',
    defaultCandidateEmailTemplateId: '',
    defaultOfferLetterTemplateId: '',
    defaultRejectionEmailTemplateId: '',
    defaultWelcomeEmailTemplateId: '',
    automaticallyCloseJobOpeningWhenPositionsFilled: true,
    automaticallyScheduleOnboardingTasks: true,
    notifyHiringManagerWhenCandidateHired: true,
    notifyEmployeeWhenOnboardingStarts: true,
    keepEmployeeAsDraftUntilOnboardingComplete: true,
    preventEmployeeActivationUntilMandatoryFieldsCompleted: true,
    resumeParsingEnabled: true,
  },
  documents: {
    maxUploadSizeMb: 10,
    allowedExtensions: 'pdf,doc,docx,png,jpg,jpeg',
    blockedExtensions: 'exe,bat,cmd,js,sh',
    allowedMimeTypes: '',
    virusScanRequired: false,
    allowMultipleFilesPerRecord: true,
    maximumFilesPerRecord: 10,
    archiveAfterMonths: 24,
    storageProvider: 'INTERNAL',
    retentionPolicy: 'ARCHIVE_ONLY',
    deleteAfterYears: 7,
    compressionEnabled: false,
    versioningEnabled: true,
    maximumVersions: 10,
    requireDocumentCategories: true,
    requireDescription: false,
    requireDocumentNumber: false,
    encryptDocuments: false,
    auditDownloads: true,
    watermarkDownloads: false,
    disableExternalDownloads: false,
    requireOwner: false,
    requireExpiryDate: false,
    requireEffectiveDate: false,
    requireClassification: false,
    allowDuplicateFile: true,
    duplicateDetectionStrategy: 'FILE_HASH_RECORD',
    requireExpiryForExpirableCategories: true,
    blockExpiredDocuments: false,
    warnBeforeExpiryDays: 30,
  },
  branding: {
    appTitle: 'DijiPeople',
    brandName: 'DijiPeople',
    legalCompanyName: '',
    shortBrandName: '',
    brandDescription: '',
    primaryColor: '#059669',
    secondaryColor: '#047857',
    accentColor: '#34D399',
    backgroundColor: '#f8fafc',
    surfaceColor: '#ffffff',
    textColor: '#0f172a',
    mutedTextColor: '#64748b',
    borderColor: '#e2e8f0',
    sidebarBackgroundColor: '#0f172a',
    sidebarTextColor: '#e5e7eb',
    sidebarActiveBackgroundColor: '#059669',
    sidebarActiveTextColor: '#ffffff',
    successColor: '#16a34a',
    warningColor: '#f59e0b',
    dangerColor: '#dc2626',
    infoColor: '#3b82f6',
    fontFamily: 'INTER',
    themeMode: 'LIGHT',
    density: 'COMFORTABLE',
    radius: 'LARGE',
    shadow: 'SOFT',
    navigationLayout: 'SIDEBAR',
    appBackgroundColor: '#f5f0e8',
    appSurfaceColor: '#fffaf4',
    pageGradientStartColor: '#fffcf7',
    pageGradientEndColor: '#f5f0e8',
    cardGradientStartColor: '#ffffff',
    cardGradientEndColor: '#d6f4ee',
    defaultThemeMode: 'LIGHT',
    sidebarStyle: 'DEFAULT',
    uiDensity: 'COMFORTABLE',
    supportEmail: '',
    hrContactEmail: '',
    replyToEmail: '',
    supportPhone: '',
    privacyPolicyUrl: '',
    termsOfUseUrl: '',
    websiteUrl: '',
    helpCenterUrl: '',
    officeAddress: '',
    /*
     * Deliberately empty. This is a white-label platform, so a tenant that has
     * not uploaded its own artwork must show no logo rather than inherit the
     * vendor's - otherwise DijiPeople branding appears inside a customer's
     * workspace. Platform-owned surfaces carry the shipped assets instead.
     */
    logoUrl: '',
    logoDocumentId: '',
    squareLogoUrl: '',
    squareLogoDocumentId: '',
    faviconUrl: '',
    faviconDocumentId: '',
    loginBannerImageUrl: '',
    loginBannerImageDocumentId: '',
    emailHeaderLogoUrl: '',
    emailHeaderLogoDocumentId: '',
    portalTagline: '',
    welcomeTitle: '',
    welcomeSubtitle: '',
    footerText: 'Powered by DijiPeople',
    dashboardGreeting: '',
    employeePortalMessage: '',
    emptyStateMessage: '',
    emailSenderName: '',
    emailFooterText: '',
    emailBrandColor: '#0f766e',
    showLogoInEmails: true,
    showBrandingOnLoginPage: true,
    showBrandingInEmployeePortal: true,
    showBrandingInReports: true,
    showCompanyNameInBrowserTitle: true,
    enableWhiteLabelSupportDetails: false,
  },
  notifications: {
    inAppEnabled: true,
    emailEnabled: true,
    browserPushEnabled: false,
    digestEnabled: true,
    approvalDigestEnabled: true,
    instantApprovalRequestEnabled: true,
    approvalDecisionEnabled: true,
    escalationReminderEnabled: true,
    onboardingReminderEnabled: true,
    newJoinerAnnouncementEnabled: true,
    profileCompletionReminderEnabled: true,
    documentExpiryReminderEnabled: true,
    timesheetReminderEnabled: true,
    lateCheckInAlertEnabled: false,
    leaveRequestNotificationEnabled: true,
    attendanceRegularizationEnabled: false,
    leaveDecisionEmailEnabled: true,
    digestFrequency: 'DAILY',
    defaultReminderLeadDays: 2,
    maxReminderAttempts: 3,
    quietHoursEnabled: false,
    quietHoursWindow: '22:00-07:00',
    notifyReportingManagersOnly: true,
    notifyHrTeamForEmployeeChanges: true,
    notifyEmployeesDirectly: true,
    showNotificationPreviewInApp: true,
  },
  security: {
    minimumPasswordLength: 12,
    requireUppercase: true,
    requireLowercase: true,
    requireNumber: true,
    requireSpecialCharacter: true,
    passwordExpiryDays: 0,
    passwordHistoryCount: 5,
    failedAttemptsBeforeLock: 5,
    lockDurationMinutes: 30,
    allowRememberMe: true,
    requireEmailVerification: true,
    allowMultipleActiveSessions: false,
    sessionTimeoutMinutes: 480,
    refreshTokenExpiryDays: 30,
    absoluteSessionLifetimeDays: 30,
    idleTimeoutMinutes: 480,
    invitationExpiryHours: 72,
    allowInvitationResend: true,
    passwordSetupRequiredBeforeFirstLogin: true,
    mfaRequired: false,
    mfaMethod: 'EMAIL',
    rememberTrustedDevice: false,
  },
  system: {
    dateFormat: 'MM/dd/yyyy',
    timeFormat: '12h',
    locale: 'en-US',
    uiDensity: 'comfortable',
    defaultThemeMode: 'light',
    defaultDashboardView: 'admin',
    defaultLandingModule: 'overview',
    defaultWeekStartDay: 'MONDAY',
    defaultRecordsPerPage: '25',
    enableStickyFilters: true,
    defaultTimezone: 'UTC',
    defaultCurrency: 'USD',
    defaultLanguage: 'en',
    autoLogoutMinutes: 15,
    showHelpTips: true,
  },
};

export const TENANT_FEATURE_DEFINITIONS = [
  {
    key: 'employees',
    label: 'Employees',
    description:
      'Employee directory, profiles, lifecycle actions, and hierarchy.',
    defaultEnabled: true,
    categoryKey: 'core-hr',
    categoryLabel: 'Core HR',
    categoryOrder: 10,
    sortOrder: 10,
    icon: 'users',
    isVisible: true,
  },
  {
    key: 'organization',
    label: 'Organization',
    description:
      'Departments, designations, locations, and shared org master data.',
    defaultEnabled: true,
    categoryKey: 'core-hr',
    categoryLabel: 'Core HR',
    categoryOrder: 10,
    sortOrder: 20,
    icon: 'building-2',
    isVisible: true,
  },
  {
    key: 'leave',
    label: 'Leave',
    description: 'Leave types, policies, requests, and approval flows.',
    defaultEnabled: true,
    categoryKey: 'workforce',
    categoryLabel: 'Workforce Operations',
    categoryOrder: 20,
    sortOrder: 10,
    icon: 'calendar-days',
    isVisible: true,
  },
  {
    key: 'attendance',
    label: 'Attendance',
    description:
      'Check-ins, daily attendance entries, and attendance operations.',
    defaultEnabled: true,
    categoryKey: 'workforce',
    categoryLabel: 'Workforce Operations',
    categoryOrder: 20,
    sortOrder: 20,
    icon: 'clock-3',
    isVisible: true,
  },
  {
    key: 'timesheets',
    label: 'Timesheets',
    // Sentence case, not the raw enum spelling — this string is published on
    // the public /features and /plans pages (BUG-1307). "Monthly" is accurate
    // rather than a hedge: `Timesheet` is keyed `@@unique([tenantId,
    // employeeId, year, month])`, so a timesheet period *is* a calendar month.
    description: 'Monthly timesheets, submission, and approval workflows.',
    defaultEnabled: true,
    categoryKey: 'workforce',
    categoryLabel: 'Workforce Operations',
    categoryOrder: 20,
    sortOrder: 30,
    icon: 'clipboard-list',
    isVisible: true,
  },
  {
    key: 'projects',
    label: 'Projects',
    description: 'Projects, project staffing, and timesheet project selection.',
    defaultEnabled: true,
    categoryKey: 'work-management',
    categoryLabel: 'Work Management',
    categoryOrder: 30,
    sortOrder: 10,
    icon: 'folder-kanban',
    isVisible: true,
  },
  {
    key: 'recruitment',
    label: 'Recruitment',
    description: 'Job openings, candidates, applications, and hiring pipeline.',
    defaultEnabled: true,
    categoryKey: 'talent',
    categoryLabel: 'Talent',
    categoryOrder: 40,
    sortOrder: 10,
    icon: 'user-plus',
    isVisible: true,
  },
  {
    key: 'onboarding',
    label: 'Onboarding',
    description:
      'Template-driven onboarding plans, tasks, and progress tracking.',
    defaultEnabled: true,
    categoryKey: 'talent',
    categoryLabel: 'Talent',
    categoryOrder: 40,
    sortOrder: 20,
    icon: 'list-checks',
    isVisible: true,
  },
  {
    key: 'documents',
    label: 'Documents',
    description:
      'Shared document metadata and cross-module document references.',
    defaultEnabled: true,
    categoryKey: 'platform',
    categoryLabel: 'Platform',
    categoryOrder: 50,
    sortOrder: 10,
    icon: 'file-stack',
    isVisible: true,
  },
  {
    key: 'notifications',
    label: 'Notifications',
    description:
      'Internal notification delivery and future communication hooks.',
    defaultEnabled: true,
    categoryKey: 'platform',
    categoryLabel: 'Platform',
    categoryOrder: 50,
    sortOrder: 20,
    icon: 'bell',
    isVisible: true,
  },
  {
    key: 'branding',
    label: 'Branding',
    description:
      'Tenant-level brand identity values for future white-label settings.',
    defaultEnabled: true,
    categoryKey: 'platform',
    categoryLabel: 'Platform',
    categoryOrder: 50,
    sortOrder: 30,
    icon: 'palette',
    isVisible: true,
  },
  {
    key: 'payroll',
    label: 'Payroll',
    description:
      'Payroll cycles, employee compensation, and draft payroll runs.',
    defaultEnabled: true,
    categoryKey: 'payroll-finance',
    categoryLabel: 'Payroll & Finance',
    categoryOrder: 60,
    sortOrder: 10,
    icon: 'wallet',
    isVisible: true,
  },
] as const;
