export const TENANT_SETTING_CATEGORIES = [
  'organization',
  'employees',
  'access',
  'leave',
  'attendance',
  'timesheets',
  'payroll',
  'recruitment',
  'documents',
  'branding',
  'notifications',
  'system',
] as const;

export type TenantSettingCategory = (typeof TENANT_SETTING_CATEGORIES)[number];

export type TenantSettingDefaults = Record<
  TenantSettingCategory,
  Record<string, boolean | number | string | null>
>;

export const DEFAULT_TENANT_SETTINGS: TenantSettingDefaults = {
  organization: {
    companyDisplayName: '',
    legalBusinessName: '',
    industry: '',
    businessEmail: '',
    businessPhone: '',
    timezone: 'UTC',
    currency: 'USD',
    dateFormat: 'MM/dd/yyyy',
    weekStartsOn: 'MONDAY',
  },
  employees: {
    employeeIdPrefix: 'EMP',
    employeeIdSequenceLength: 4,
    autoGenerateEmployeeId: true,
    defaultEmployeeStatus: 'Active',
    requirePersonalEmail: false,
    requireEmergencyContact: true,
    requireJoiningDate: true,
    requireDepartment: false,
    requireDesignation: false,
    requireReportingManager: false,
    requireWorkLocation: false,
    defaultEmploymentType: 'FULL_TIME',
    defaultWorkMode: 'OFFICE',
    autoCreateDraftOnHire: true,
    keepEmployeeAsDraftUntilOnboardingComplete: true,
    preventActivationUntilMandatoryFieldsCompleted: true,
    maxReportingLevels: 5,
    allowSkipLevelApprovals: false,
    allowMatrixReporting: false,
    allowEmployeeWithoutManager: true,
    preventDuplicateByPersonalEmail: true,
    preventDuplicateByPhoneNumber: false,
    preventDuplicateByNationalId: false,
    warnOnPossibleDuplicate: true,
    onboardingChecklistTemplate: 'standard',
  },
  access: {
    allowDirectPermissions: true,
    allowCustomRoles: true,
    defaultManagerRoleKey: 'manager',
    defaultEmployeeRoleKey: 'employee',
    lockSystemRoles: true,
  },
  leave: {
    defaultApprovalFlow: 'manager_then_hr',
    allowHalfDayRequests: true,
    documentReminderAfterDays: 3,
    defaultCarryForwardEnabled: false,
    defaultHolidayCalendarName: 'Company Calendar',
    allowManualLeaveMarking: true,
  },
  attendance: {
    defaultGraceMinutes: 10,
    allowManualAdjustments: true,
    autoCheckOutEnabled: false,
    trackMissedCheckOut: true,
    allowedModes: 'OFFICE,REMOTE,HYBRID',
    enforceOfficeLocationForOfficeMode: true,
    requireRemoteLocationCapture: false,
    standardWorkHoursPerDay: 8,
  },
  timesheets: {
    timesheetPeriodType: 'monthly',
    weekendDays: 'SATURDAY,SUNDAY',
    defaultWorkHours: 8,
    defaultHoursForOnWork: 8,
    allowWeekendWork: true,
    allowHolidayWork: true,
    requireMonthlySubmission: true,
    requireMONTHLYSubmission: true,
    autoFillWorkingDays: false,
    requireAllDaysCompletedBeforeSubmit: true,
    requireSubmissionNote: false,
    allowBulkImport: true,
    allowEmployeeSelfImport: false,
    allowManagerImportForTeam: true,
    requireApprovalBeforePayroll: true,
    exportTemplateFormat: 'XLSX',
    lockTimesheetAfterApproval: true,
    allowRejectedTimesheetResubmission: true,
  },
  payroll: {
    payFrequency: 'MONTHLY',
    payrollStatus: 'Active',
    defaultPayrollGroup: 'main',
    defaultPaymentMode: 'BANK_TRANSFER',
    compensationReviewCycle: 'ANNUAL',
    defaultCurrency: 'USD',
    payrollGenerationSource: 'approved_timesheets',
    requireApprovedTimesheetsForPayroll: true,
    includeLeavesInPayrollSummary: true,
    includeHolidaysInPayrollSummary: true,
    includeWeekendWorkInPayrollSummary: true,
    defaultPayrollCycleDay: 25,
    allowDraftPayrollAdjustments: true,
    payrollExportFormat: 'CSV',
  },
  recruitment: {
    candidateStages:
      'APPLIED,SCREENING,SHORTLISTED,INTERVIEW,FINAL_REVIEW,OFFER,APPROVED,HIRED',
    onboardingWorkflow: 'standard',
    autoCreateEmployeeFromCandidate: true,
    onboardingChecklistTemplate: 'standard',
    keepEmployeeAsDraftUntilOnboardingComplete: true,
    preventEmployeeActivationUntilMandatoryFieldsCompleted: true,
    resumeParsingEnabled: true,
  },
  documents: {
    maxUploadSizeMb: 10,
    allowedExtensions: 'pdf,doc,docx,png,jpg,jpeg',
    archiveAfterMonths: 24,
    requireDocumentCategories: true,
  },
  branding: {
    appTitle: 'DijiPeople',
    brandName: 'DijiPeople',
    legalCompanyName: '',
    shortBrandName: '',
    brandDescription: '',
    primaryColor: '#0f766e',
    secondaryColor: '#115e59',
    accentColor: '#14b8a6',
    backgroundColor: '#f8fafc',
    surfaceColor: '#ffffff',
    textColor: '#0f172a',
    fontFamily: 'INTER',
    appBackgroundColor: '#f5f0e8',
    appSurfaceColor: '#fffaf4',
    pageGradientStartColor: '#fffcf7',
    pageGradientEndColor: '#f5f0e8',
    cardGradientStartColor: '#ffffff',
    cardGradientEndColor: '#d6f4ee',
    defaultThemeMode: 'LIGHT',
    sidebarStyle: 'DEFAULT',
    uiDensity: 'COMFORTABLE',
    supportEmail: '',
    hrContactEmail: '',
    replyToEmail: '',
    supportPhone: '',
    websiteUrl: '',
    helpCenterUrl: '',
    officeAddress: '',
    logoUrl: '',
    logoDocumentId: '',
    squareLogoUrl: '',
    squareLogoDocumentId: '',
    faviconUrl: '',
    faviconDocumentId: '',
    loginBannerImageUrl: '',
    loginBannerImageDocumentId: '',
    emailHeaderLogoUrl: '',
    emailHeaderLogoDocumentId: '',
    portalTagline: '',
    welcomeTitle: '',
    welcomeSubtitle: '',
    footerText: 'Powered by DijiPeople',
    dashboardGreeting: '',
    employeePortalMessage: '',
    emptyStateMessage: '',
    emailSenderName: '',
    emailFooterText: '',
    emailBrandColor: '#0f766e',
    showLogoInEmails: true,
    showBrandingOnLoginPage: true,
    showBrandingInEmployeePortal: true,
    showBrandingInReports: true,
    showCompanyNameInBrowserTitle: true,
    enableWhiteLabelSupportDetails: false,
  },
  notifications: {
    inAppEnabled: true,
    emailEnabled: true,
    browserPushEnabled: false,
    digestEnabled: true,
    approvalDigestEnabled: true,
    instantApprovalRequestEnabled: true,
    approvalDecisionEnabled: true,
    escalationReminderEnabled: true,
    onboardingReminderEnabled: true,
    newJoinerAnnouncementEnabled: true,
    profileCompletionReminderEnabled: true,
    documentExpiryReminderEnabled: true,
    timesheetReminderEnabled: true,
    lateCheckInAlertEnabled: false,
    leaveRequestNotificationEnabled: true,
    attendanceRegularizationEnabled: false,
    leaveDecisionEmailEnabled: true,
    digestFrequency: 'DAILY',
    defaultReminderLeadDays: 2,
    maxReminderAttempts: 3,
    quietHoursEnabled: false,
    quietHoursWindow: '22:00-07:00',
    notifyReportingManagersOnly: true,
    notifyHrTeamForEmployeeChanges: true,
    notifyEmployeesDirectly: true,
    showNotificationPreviewInApp: true,
  },
  system: {
    dateFormat: 'MM/dd/yyyy',
    timeFormat: '12h',
    locale: 'en-US',
    uiDensity: 'comfortable',
    defaultThemeMode: 'light',
    defaultDashboardView: 'overview',
    defaultLandingModule: 'overview',
    defaultWeekStartDay: 'MONDAY',
    defaultRecordsPerPage: '25',
    enableStickyFilters: true,
    defaultTimezone: 'UTC',
    defaultCurrency: 'USD',
    defaultLanguage: 'en',
    autoLogoutMinutes: 15,
    showHelpTips: true,
  },
};

export const TENANT_FEATURE_DEFINITIONS = [
  {
    key: 'employees',
    label: 'Employees',
    description: 'Employee directory, profiles, lifecycle actions, and hierarchy.',
    defaultEnabled: true,
  },
  {
    key: 'organization',
    label: 'Organization',
    description: 'Departments, designations, locations, and shared org master data.',
    defaultEnabled: true,
  },
  {
    key: 'leave',
    label: 'Leave',
    description: 'Leave types, policies, requests, and approval flows.',
    defaultEnabled: true,
  },
  {
    key: 'attendance',
    label: 'Attendance',
    description: 'Check-ins, daily attendance entries, and attendance operations.',
    defaultEnabled: true,
  },
  {
    key: 'timesheets',
    label: 'Timesheets',
    description: 'MONTHLY timesheets, submission, and approval workflows.',
    defaultEnabled: true,
  },
  {
    key: 'projects',
    label: 'Projects',
    description: 'Projects, project staffing, and timesheet project selection.',
    defaultEnabled: true,
  },
  {
    key: 'recruitment',
    label: 'Recruitment',
    description: 'Job openings, candidates, applications, and hiring pipeline.',
    defaultEnabled: true,
  },
  {
    key: 'onboarding',
    label: 'Onboarding',
    description: 'Template-driven onboarding plans, tasks, and progress tracking.',
    defaultEnabled: true,
  },
  {
    key: 'documents',
    label: 'Documents',
    description: 'Shared document metadata and cross-module document references.',
    defaultEnabled: true,
  },
  {
    key: 'notifications',
    label: 'Notifications',
    description: 'Internal notification delivery and future communication hooks.',
    defaultEnabled: true,
  },
  {
    key: 'branding',
    label: 'Branding',
    description: 'Tenant-level brand identity values for future white-label settings.',
    defaultEnabled: true,
  },
  {
    key: 'payroll',
    label: 'Payroll',
    description: 'Payroll cycles, employee compensation, and draft payroll runs.',
    defaultEnabled: true,
  },
] as const;
