import type { InvoicePdfModel } from './invoice-pdf.template';

export function createSampleInvoicePdfModel(
  overrides: Partial<InvoicePdfModel> = {},
): InvoicePdfModel {
  return {
    invoiceNumber: 'INV-20260618-7012',
    status: 'ISSUED',
    issueDate: new Date('2026-06-18T00:00:00.000Z'),
    dueDate: new Date('2026-07-02T00:00:00.000Z'),
    currency: 'USD',
    billingPeriod: 'Jun 01, 2026 - Jun 30, 2026',
    subscriptionStatus: 'ACTIVE',
    generatedAt: new Date('2026-06-18T18:30:00.000Z'),
    brand: {
      brandName: 'DijiPeople',
      logoText: 'DP',
      primaryColor: '#0f766e',
      accentColor: '#14b8a6',
      supportEmail: 'support@dijipeople.com',
      website: 'https://dijipeople.com',
      addressLines: ['DijiPeople Platform', 'Riyadh, Saudi Arabia'],
      footerText:
        'This invoice is generated by the DijiPeople Platform Admin billing system.',
      paymentInstructions:
        'Please pay by bank transfer or card according to your platform agreement. Include the invoice number in your payment reference.',
      terms: 'Payment is due by the invoice due date unless otherwise agreed.',
    },
    billFrom: {
      name: 'DijiPeople Platform',
      logoText: 'DP',
      email: 'billing@dijipeople.com',
      addressLines: ['Riyadh, Saudi Arabia', 'https://dijipeople.com'],
      taxNumber: 'TRN-000000000',
    },
    billTo: {
      name: 'Acme HR Services Limited',
      logoText: 'AH',
      email: 'billing@acme.example',
      addressLines: ['King Fahd Road', 'Riyadh', 'Saudi Arabia'],
      taxNumber: 'VAT-123456789',
    },
    lineItems: [
      {
        description: 'DijiPeople Enterprise Plan',
        billingPeriod: 'Jun 01, 2026 - Jun 30, 2026',
        quantity: 1,
        unitPrice: 1200,
        tax: 180,
        total: 1380,
      },
    ],
    subtotal: 1200,
    discount: 0,
    tax: 180,
    total: 1380,
    paid: 0,
    outstandingBalance: 1380,
    payments: [
      {
        date: new Date('2026-06-19T00:00:00.000Z'),
        method: 'BANK',
        status: 'PENDING',
        amount: 500,
      },
    ],
    notes: 'Thank you for choosing DijiPeople.',
    ...overrides,
  };
}
