import type { StandardModuleRuntimeSpec } from "./standard-module-runtime";

const status = (values: string[]) =>
  values.map((value) => ({ value, label: value.replaceAll("_", " ") }));

export const payrollRunRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-runs",
  apiPath: "/api/payroll/runs",
  entityLogicalName: "payrollRun",
  collectionName: "payrollRuns",
  label: "Payroll Runs",
  singularLabel: "Payroll Run",
  routeBase: "/payroll/runs",
  primaryNameField: "runName",
  statusField: "status",
  permissions: { read: "payroll-runs.read", create: "payroll-runs.create" },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: { payrollPeriodId: "/api/payroll/periods" },
  fields: [
    {
      logicalName: "runName",
      displayName: "Payroll Run",
      isPrimaryName: true,
      isReadOnly: true,
    },
    {
      logicalName: "periodName",
      displayName: "Payroll Period",
      isReadOnly: true,
    },
    {
      logicalName: "payrollPeriodId",
      displayName: "Payroll Period",
      dataType: "lookup",
    },
    {
      logicalName: "runNumber",
      displayName: "Run Number",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "DRAFT",
        "CALCULATING",
        "CALCULATED",
        "REVIEWED",
        "APPROVED",
        "PAID",
        "LOCKED",
        "FAILED",
      ]),
      isStatus: true,
    },
    {
      logicalName: "calculatedAt",
      displayName: "Calculated At",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "lockedAt",
      displayName: "Locked At",
      dataType: "datetime",
      isReadOnly: true,
    },
  ],
  formFields: ["payrollPeriodId"],
  views: [
    {
      logicalName: "payroll-runs.all",
      viewId: "07fe81dc-c70c-4f37-b95c-2f6f8fbc6821",
      displayName: "All Payroll Runs",
      columns: [
        "runName",
        "periodName",
        "runNumber",
        "status",
        "calculatedAt",
        "lockedAt",
      ],
      isDefault: true,
    },
  ],
};

export const payslipRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payslips",
  apiPath: "/api/payslips",
  entityLogicalName: "payslip",
  collectionName: "payslips",
  label: "Payslips",
  singularLabel: "Payslip",
  routeBase: "/payroll/payslips",
  primaryNameField: "payslipNumber",
  statusField: "status",
  permissions: { read: "payslips.read-all" },
  recordNavigation: true,
  adapterCapabilities: { disableCreate: true, disableEdit: true },
  fields: [
    {
      logicalName: "payslipNumber",
      displayName: "Payslip",
      isPrimaryName: true,
      isReadOnly: true,
    },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "periodName",
      displayName: "Payroll Period",
      isReadOnly: true,
    },
    { logicalName: "currencyCode", displayName: "Currency", isReadOnly: true },
    {
      logicalName: "grossEarnings",
      displayName: "Gross Earnings",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "totalDeductions",
      displayName: "Deductions",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "netPay",
      displayName: "Net Pay",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status(["DRAFT", "GENERATED", "PUBLISHED", "VOID"]),
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "payslips.all",
      viewId: "95d422d5-969c-423b-a589-62d1178d4b01",
      displayName: "All Payslips",
      columns: [
        "payslipNumber",
        "employeeName",
        "periodName",
        "grossEarnings",
        "totalDeductions",
        "netPay",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const loanRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "loans",
  apiPath: "/api/loans",
  entityLogicalName: "loanRequest",
  collectionName: "loans",
  label: "Loan Requests",
  singularLabel: "Loan Request",
  routeBase: "/loans",
  primaryNameField: "requestNumber",
  statusField: "status",
  permissions: {
    read: "loans.read-all",
    create: "loans.create",
    update: "loans.update",
  },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    loanPolicyId: "/api/loan-policies",
    currencyCode: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "requestNumber",
      displayName: "Loan Request",
      isPrimaryName: true,
      isReadOnly: true,
    },
    { logicalName: "employeeId", displayName: "Employee", dataType: "lookup" },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "loanPolicyId",
      displayName: "Loan Policy",
      dataType: "lookup",
    },
    {
      logicalName: "requestedAmount",
      displayName: "Requested Amount",
      dataType: "currency",
    },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
    },
    {
      logicalName: "installmentCount",
      displayName: "Installments",
      dataType: "number",
    },
    {
      logicalName: "requestedStartDate",
      displayName: "Start Date",
      dataType: "date",
    },
    {
      logicalName: "reason",
      displayName: "Reason",
      dataType: "multiline-string",
    },
    {
      logicalName: "outstandingBalance",
      displayName: "Outstanding",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "DRAFT",
        "PENDING_APPROVAL",
        "APPROVED",
        "ACTIVE",
        "REJECTED",
        "SETTLED",
        "CANCELLED",
      ]),
      isStatus: true,
    },
  ],
  formFields: [
    "employeeId",
    "loanPolicyId",
    "requestedAmount",
    "currencyCode",
    "installmentCount",
    "requestedStartDate",
    "reason",
  ],
  views: [
    {
      logicalName: "loans.all",
      viewId: "b626aee6-a7d5-4fcf-a5c5-9cf8591e5e31",
      displayName: "All Loan Requests",
      columns: [
        "requestNumber",
        "employeeName",
        "requestedAmount",
        "currencyCode",
        "installmentCount",
        "outstandingBalance",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const benefitAssignmentRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "benefit-assignments",
  apiPath: "/api/benefits/assignments",
  entityLogicalName: "employeeBenefitAssignment",
  collectionName: "benefitAssignments",
  label: "Employee Benefit Assignments",
  singularLabel: "Benefit Assignment",
  routeBase: "/benefits/assignments",
  primaryNameField: "assignmentName",
  statusField: "status",
  permissions: { read: "benefits.read", create: "benefits.assign" },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    benefitPolicyId: "/api/benefits/policies",
    currencyCodeOverride: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "assignmentName",
      displayName: "Benefit Assignment",
      isPrimaryName: true,
      isReadOnly: true,
    },
    { logicalName: "employeeId", displayName: "Employee", dataType: "lookup" },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "benefitPolicyId",
      displayName: "Benefit Policy",
      dataType: "lookup",
    },
    { logicalName: "benefitName", displayName: "Benefit", isReadOnly: true },
    {
      logicalName: "fixedAmountOverride",
      displayName: "Fixed Amount Override",
      dataType: "currency",
    },
    {
      logicalName: "percentageOverride",
      displayName: "Percentage Override",
      dataType: "decimal",
    },
    {
      logicalName: "currencyCodeOverride",
      displayName: "Currency Override",
      dataType: "lookup",
    },
    {
      logicalName: "effectiveFrom",
      displayName: "Effective From",
      dataType: "date",
    },
    {
      logicalName: "effectiveTo",
      displayName: "Effective To",
      dataType: "date",
    },
    {
      logicalName: "allocatedBalance",
      displayName: "Allocated Balance",
      dataType: "currency",
    },
    {
      logicalName: "consumedBalance",
      displayName: "Consumed Balance",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "notes",
      displayName: "Notes",
      dataType: "multiline-string",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "PENDING_APPROVAL",
        "ACTIVE",
        "SUSPENDED",
        "EXPIRED",
        "CANCELLED",
      ]),
      isStatus: true,
    },
  ],
  formFields: [
    "employeeId",
    "benefitPolicyId",
    "fixedAmountOverride",
    "percentageOverride",
    "currencyCodeOverride",
    "effectiveFrom",
    "effectiveTo",
    "allocatedBalance",
    "notes",
  ],
  views: [
    {
      logicalName: "benefit-assignments.all",
      viewId: "d2f840a8-48f6-48d6-94f1-c24df3c1dc22",
      displayName: "All Benefit Assignments",
      columns: [
        "assignmentName",
        "employeeName",
        "benefitName",
        "effectiveFrom",
        "effectiveTo",
        "allocatedBalance",
        "consumedBalance",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const employeeBankAccountRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "employee-bank-accounts",
  apiPath: "/api/employee-bank-accounts",
  entityLogicalName: "employeeBankAccount",
  collectionName: "employeeBankAccounts",
  label: "Employee Bank Accounts",
  singularLabel: "Employee Bank Account",
  routeBase: "/employee-bank-accounts",
  primaryNameField: "accountTitle",
  statusField: "verificationStatus",
  permissions: {
    read: "employee-bank-accounts.read",
    create: "employee-bank-accounts.manage",
  },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    bankId: "/api/banks",
    countryCode: "/api/lookups/countries",
    currencyCode: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "accountTitle",
      displayName: "Account Title",
      isPrimaryName: true,
    },
    { logicalName: "employeeId", displayName: "Employee", dataType: "lookup" },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    { logicalName: "bankId", displayName: "Bank", dataType: "lookup" },
    { logicalName: "bankName", displayName: "Bank", isReadOnly: true },
    { logicalName: "accountNumber", displayName: "Account Number" },
    { logicalName: "iban", displayName: "IBAN" },
    { logicalName: "swiftOrRoutingCode", displayName: "SWIFT / Routing Code" },
    { logicalName: "countryCode", displayName: "Country", dataType: "lookup" },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
    },
    {
      logicalName: "isPrimaryPayroll",
      displayName: "Primary Payroll Account",
      dataType: "boolean",
    },
    {
      logicalName: "effectiveFrom",
      displayName: "Effective From",
      dataType: "date",
    },
    {
      logicalName: "effectiveTo",
      displayName: "Effective To",
      dataType: "date",
    },
    {
      logicalName: "verificationStatus",
      displayName: "Verification",
      dataType: "optionset",
      options: status(["UNVERIFIED", "PENDING", "VERIFIED", "REJECTED"]),
      isStatus: true,
    },
    { logicalName: "isActive", displayName: "Active", dataType: "boolean" },
  ],
  formFields: [
    "employeeId",
    "bankId",
    "accountTitle",
    "accountNumber",
    "iban",
    "swiftOrRoutingCode",
    "countryCode",
    "currencyCode",
    "isPrimaryPayroll",
    "effectiveFrom",
    "effectiveTo",
  ],
  views: [
    {
      logicalName: "employee-bank-accounts.all",
      viewId: "ea166ec7-c713-4a7f-97d4-3e5393901ecb",
      displayName: "All Employee Bank Accounts",
      columns: [
        "accountTitle",
        "employeeName",
        "bankName",
        "accountNumber",
        "iban",
        "currencyCode",
        "isPrimaryPayroll",
        "verificationStatus",
      ],
      isDefault: true,
    },
  ],
};

export const payrollExceptionRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-exceptions",
  apiPath: "/api/payroll/operations/exceptions",
  entityLogicalName: "payrollException",
  collectionName: "payrollExceptions",
  label: "Payroll Exceptions",
  singularLabel: "Payroll Exception",
  routeBase: "/payroll/exceptions",
  recordNavigation: false,
  primaryNameField: "issue",
  permissions: {
    read: "payroll-exceptions.read",
    export: "payroll-exceptions.export",
  },
  adapterCapabilities: {
    disableCreate: true,
    disableEdit: true,
    import: false,
    export: true,
    exportTemplate: false,
  },
  fields: [
    { logicalName: "employee", displayName: "Employee", isPrimaryName: true, isReadOnly: true },
    { logicalName: "employeeCode", displayName: "Employee Code", isReadOnly: true },
    { logicalName: "issue", displayName: "Issue", dataType: "multiline-string", isReadOnly: true },
    { logicalName: "severity", displayName: "Severity", dataType: "optionset", options: status(["INFO", "WARNING", "ERROR", "BLOCKER"]), isStatus: true, isReadOnly: true },
    { logicalName: "category", displayName: "Category", isReadOnly: true },
    { logicalName: "suggestedResolution", displayName: "Suggested Resolution", dataType: "multiline-string", isReadOnly: true },
    { logicalName: "openRecordUrl", displayName: "Open Record", dataType: "url", isReadOnly: true },
  ],
  views: [{
    logicalName: "payroll-exceptions.open",
    viewId: "3825e055-6545-4199-814c-7ed2430df223",
    displayName: "Open Payroll Exceptions",
    columns: ["employee", "employeeCode", "issue", "severity", "category", "suggestedResolution", "openRecordUrl"],
    isDefault: true,
  }],
};
