import type { StandardModuleRuntimeSpec } from "./standard-module-runtime";

const status = (values: string[]) =>
  values.map((value) => ({
    value,
    label: value
      .toLowerCase()
      .split("_")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(" "),
  }));

const frequencyOptions = status(["WEEKLY", "BIWEEKLY", "SEMI_MONTHLY", "MONTHLY"]);
const payFrequencyOptions = status(["MONTHLY", "SEMI_MONTHLY", "BI_WEEKLY", "WEEKLY", "DAILY", "HOURLY"]);
const payrollCycleStatusOptions = [
  { value: "DRAFT", label: "Draft" },
  { value: "PROCESSING", label: "Processing" },
  { value: "REVIEW", label: "In Review" },
  { value: "FINALIZED", label: "Finalized" },
  { value: "FAILED", label: "Failed" },
];

export const payrollCycleRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-cycles",
  apiPath: "/api/payroll/cycles",
  entityLogicalName: "payrollCycle",
  collectionName: "payrollCycles",
  label: "Payroll Cycles",
  singularLabel: "Payroll Cycle",
  routeBase: "/payroll/cycles",
  primaryNameField: "name",
  ownerField: "createdById",
  statusField: "status",
  permissions: {
    read: "payroll-cycles.read",
    create: "payroll-cycles.create",
    update: "payroll-cycles.update",
    export: "payroll-cycles.export",
  },
  lookupApiPaths: {
    businessUnitId: "/api/business-units",
    payrollCalendarId: "/api/payroll/calendars",
    payrollRegionId: "/api/payroll-regions",
    currencyCode: "/api/configuration/currencies",
    defaultEmployerBankAccountId: "/api/payroll/employer-bank-accounts",
  },
  fields: [
    { logicalName: "name", displayName: "Cycle Name", isPrimaryName: true },
    {
      logicalName: "code",
      displayName: "Code",
      requirementLevel: "required",
    },
    {
      logicalName: "businessUnitId",
      displayName: "Business Unit",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "businessUnit",
    },
    {
      logicalName: "payrollCalendarId",
      displayName: "Payroll Calendar",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "payrollCalendar",
    },
    { logicalName: "payrollCalendarName", displayName: "Payroll Calendar", isReadOnly: true },
    {
      logicalName: "periodStart",
      displayName: "Period Start",
      dataType: "date",
      requirementLevel: "required",
    },
    {
      logicalName: "periodEnd",
      displayName: "Period End",
      dataType: "date",
      requirementLevel: "required",
    },
    { logicalName: "runDate", displayName: "Run Date", dataType: "date" },
    {
      logicalName: "payFrequency",
      displayName: "Frequency",
      dataType: "optionset",
      options: frequencyOptions,
    },
    {
      logicalName: "payrollRegionId",
      displayName: "Payroll Region",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "payrollRegion",
    },
    { logicalName: "payrollRegionName", displayName: "Payroll Region", isReadOnly: true },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    { logicalName: "periodStartRule", displayName: "Period Start Rule" },
    { logicalName: "periodEndRule", displayName: "Period End Rule" },
    {
      logicalName: "cutoffDay",
      displayName: "Cutoff Day",
      dataType: "number",
      min: 1,
      max: 31,
    },
    {
      logicalName: "paymentDay",
      displayName: "Payment Day",
      dataType: "number",
      min: 1,
      max: 31,
    },
    { logicalName: "adjustDatesForWeekend", displayName: "Adjust Weekends", dataType: "boolean" },
    { logicalName: "adjustDatesForHoliday", displayName: "Adjust Holidays", dataType: "boolean" },
    {
      logicalName: "dateAdjustmentDirection",
      displayName: "Date Adjustment",
      dataType: "optionset",
      options: status(["PREVIOUS_BUSINESS_DAY", "NEXT_BUSINESS_DAY"]),
    },
    {
      logicalName: "defaultGenerationSource",
      displayName: "Default Source",
      dataType: "optionset",
      options: status(["ATTENDANCE", "TIMESHEETS", "HYBRID", "MANUAL"]),
    },
    {
      logicalName: "defaultEmployerBankAccountId",
      displayName: "Employer Bank Account",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employerBankAccount",
    },
    { logicalName: "defaultEmployerBankAccountName", displayName: "Employer Bank Account", isReadOnly: true },
    { logicalName: "description", displayName: "Description", dataType: "multiline-string" },
    { logicalName: "periodRule", displayName: "Period Rule", isReadOnly: true },
    { logicalName: "paymentRule", displayName: "Payment Rule", isReadOnly: true },
    { logicalName: "employeeScope", displayName: "Employee Scope", isReadOnly: true },
    { logicalName: "assignedEmployees", displayName: "Assigned Employees", dataType: "number", isReadOnly: true },
    { logicalName: "nextPeriod", displayName: "Next Period", isReadOnly: true },
    { logicalName: "isDefault", displayName: "Default", dataType: "boolean" },
    { logicalName: "ownerName", displayName: "Owner", isReadOnly: true },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: payrollCycleStatusOptions,
      isStatus: true,
      isReadOnly: true,
    },
    {
      logicalName: "createdById",
      displayName: "Created By",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "user",
      isOwner: true,
      isReadOnly: true,
    },
    { logicalName: "createdAt", displayName: "Created On", dataType: "datetime", isReadOnly: true },
    { logicalName: "updatedAt", displayName: "Modified On", dataType: "datetime", isReadOnly: true },
  ],
  formSections: [
    {
      id: "payroll-cycle.identity",
      tabKey: "general",
      label: "Cycle Details",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "name", order: 10 },
        { fieldLogicalName: "code", order: 20 },
        { fieldLogicalName: "payFrequency", order: 30 },
        { fieldLogicalName: "payrollCalendarId", order: 40 },
        { fieldLogicalName: "payrollRegionId", order: 50 },
        { fieldLogicalName: "businessUnitId", order: 60 },
        { fieldLogicalName: "currencyCode", order: 70 },
        { fieldLogicalName: "isDefault", order: 80 },
      ],
    },
    {
      id: "payroll-cycle.period",
      tabKey: "general",
      label: "Period",
      order: 20,
      layout: "three-column",
      columns: 3,
      fields: [
        { fieldLogicalName: "periodStart", order: 10 },
        { fieldLogicalName: "periodEnd", order: 20 },
        { fieldLogicalName: "runDate", order: 30 },
        { fieldLogicalName: "periodStartRule", order: 40 },
        { fieldLogicalName: "periodEndRule", order: 50 },
      ],
    },
    {
      id: "payroll-cycle.payment",
      tabKey: "general",
      label: "Cutoff & Payment",
      order: 30,
      layout: "three-column",
      columns: 3,
      fields: [
        { fieldLogicalName: "cutoffDay", order: 10 },
        { fieldLogicalName: "paymentDay", order: 20 },
        { fieldLogicalName: "dateAdjustmentDirection", order: 30 },
        { fieldLogicalName: "adjustDatesForWeekend", order: 40 },
        { fieldLogicalName: "adjustDatesForHoliday", order: 50 },
      ],
    },
    {
      id: "payroll-cycle.defaults",
      tabKey: "general",
      label: "Generation Defaults",
      order: 40,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "defaultGenerationSource", order: 10 },
        { fieldLogicalName: "defaultEmployerBankAccountId", order: 20 },
        { fieldLogicalName: "description", order: 30, columnSpan: 2 },
      ],
    },
    {
      id: "payroll-cycle.audit",
      tabKey: "general",
      label: "Audit",
      order: 50,
      layout: "three-column",
      columns: 3,
      fields: [
        { fieldLogicalName: "status", order: 10 },
        { fieldLogicalName: "createdById", order: 20 },
        { fieldLogicalName: "createdAt", order: 30 },
        { fieldLogicalName: "updatedAt", order: 40 },
      ],
    },
  ],
  quickCreateFormFields: ["name", "payFrequency", "payrollCalendarId", "payrollRegionId", "currencyCode"],
  views: [
    {
      logicalName: "payroll-cycles.all",
      viewId: "863b6e3e-9a8a-4cf6-bf75-77efc870a2d9",
      displayName: "All Payroll Cycles",
      columns: [
        "name",
        "code",
        "payFrequency",
        "payrollCalendarName",
        "payrollRegionName",
        "currencyCode",
        "periodRule",
        "paymentRule",
        "defaultGenerationSource",
        "employeeScope",
        "assignedEmployees",
        "nextPeriod",
        "status",
        "isDefault",
        "ownerName",
      ],
      isDefault: true,
    },
  ],
};

export const payrollCalendarRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-calendars",
  apiPath: "/api/payroll/calendars",
  entityLogicalName: "payrollCalendar",
  collectionName: "payrollCalendars",
  label: "Payroll Calendars",
  singularLabel: "Payroll Calendar",
  routeBase: "/payroll/calendars",
  primaryNameField: "name",
  statusField: "status",
  permissions: { read: "payroll-calendars.read", create: "payroll-calendars.manage" },
  lookupApiPaths: {
    businessUnitId: "/api/business-units",
    currencyCode: "/api/configuration/currencies",
    timezone: "/api/configuration/timezones",
  },
  fields: [
    { logicalName: "name", displayName: "Calendar", isPrimaryName: true },
    { logicalName: "frequency", displayName: "Frequency", dataType: "optionset", options: frequencyOptions },
    {
      logicalName: "timezone",
      displayName: "Timezone",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "timezone",
    },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "businessUnitId",
      displayName: "Business Unit",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "businessUnit",
    },
    { logicalName: "businessUnitName", displayName: "Business Unit", isReadOnly: true },
    { logicalName: "isDefault", displayName: "Default", dataType: "boolean" },
    { logicalName: "isActive", displayName: "Active", dataType: "boolean" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: [
        { value: "ACTIVE", label: "Active" },
        { value: "INACTIVE", label: "Inactive" },
      ],
      isStatus: true,
      isReadOnly: true,
    },
    { logicalName: "updatedAt", displayName: "Modified On", dataType: "datetime", isReadOnly: true },
  ],
  formSections: [
    {
      id: "payroll-calendar.identity",
      tabKey: "general",
      label: "Calendar Details",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "name", order: 10, columnSpan: 2 },
        { fieldLogicalName: "frequency", order: 20 },
        { fieldLogicalName: "businessUnitId", order: 30 },
        { fieldLogicalName: "timezone", order: 40 },
        { fieldLogicalName: "currencyCode", order: 50 },
      ],
    },
    {
      id: "payroll-calendar.controls",
      tabKey: "general",
      label: "Controls",
      order: 20,
      layout: "three-column",
      columns: 3,
      fields: [
        { fieldLogicalName: "isDefault", order: 10 },
        { fieldLogicalName: "isActive", order: 20 },
        { fieldLogicalName: "status", order: 30 },
        { fieldLogicalName: "updatedAt", order: 40 },
      ],
    },
  ],
  views: [
    {
      logicalName: "payroll-calendars.all",
      viewId: "7ace2dd4-7e98-4a4b-a8cf-8d694f174676",
      displayName: "All Payroll Calendars",
      columns: ["name", "frequency", "businessUnitName", "currencyCode", "timezone", "isDefault", "isActive"],
      isDefault: true,
    },
  ],
};

export const payrollPeriodRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-periods",
  apiPath: "/api/payroll/periods",
  entityLogicalName: "payrollPeriod",
  collectionName: "payrollPeriods",
  label: "Payroll Periods",
  singularLabel: "Payroll Period",
  routeBase: "/payroll/periods",
  primaryNameField: "name",
  statusField: "status",
  permissions: { read: "payroll-periods.read", create: "payroll-periods.manage" },
  lookupApiPaths: {
    payrollCalendarId: "/api/payroll/calendars",
    fiscalYearId: "/api/fiscal-years",
  },
  fields: [
    { logicalName: "name", displayName: "Period", isPrimaryName: true },
    {
      logicalName: "payrollCalendarId",
      displayName: "Calendar",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "payrollCalendar",
    },
    { logicalName: "calendarName", displayName: "Calendar", isReadOnly: true },
    { logicalName: "periodStart", displayName: "Start", dataType: "date" },
    { logicalName: "periodEnd", displayName: "End", dataType: "date" },
    { logicalName: "cutoffDate", displayName: "Cutoff", dataType: "date" },
    { logicalName: "paymentDate", displayName: "Payment", dataType: "date" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: [
        { value: "OPEN", label: "Open" },
        { value: "INPUT_CLOSED", label: "Input Closed" },
        { value: "LOCKED", label: "Locked" },
        { value: "CLOSED", label: "Closed" },
      ],
      isStatus: true,
    },
    { logicalName: "updatedAt", displayName: "Modified On", dataType: "datetime", isReadOnly: true },
  ],
  formSections: [
    {
      id: "payroll-period.identity",
      tabKey: "general",
      label: "Period Details",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "name", order: 10, columnSpan: 2 },
        { fieldLogicalName: "payrollCalendarId", order: 20 },
        { fieldLogicalName: "status", order: 30 },
      ],
    },
    {
      id: "payroll-period.dates",
      tabKey: "general",
      label: "Dates",
      order: 20,
      layout: "four-column",
      columns: 4,
      fields: [
        { fieldLogicalName: "periodStart", order: 10 },
        { fieldLogicalName: "periodEnd", order: 20 },
        { fieldLogicalName: "cutoffDate", order: 30 },
        { fieldLogicalName: "paymentDate", order: 40 },
      ],
    },
    {
      id: "payroll-period.audit",
      tabKey: "general",
      label: "Audit",
      order: 30,
      layout: "single-column",
      columns: 1,
      fields: [{ fieldLogicalName: "updatedAt", order: 10 }],
    },
  ],
  views: [
    {
      logicalName: "payroll-periods.all",
      viewId: "617711cc-fd1c-43d5-b614-b75f39491038",
      displayName: "All Payroll Periods",
      columns: ["name", "calendarName", "periodStart", "periodEnd", "cutoffDate", "paymentDate", "status"],
      isDefault: true,
    },
  ],
};

export const employeeCompensationRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "employee-compensation",
  apiPath: "/api/payroll/compensations",
  entityLogicalName: "employeeCompensation",
  collectionName: "employeeCompensations",
  label: "Employee Compensation",
  singularLabel: "Employee Compensation",
  routeBase: "/payroll/employee-compensation",
  primaryNameField: "employeeName",
  permissions: { read: "payroll-compensation.read", create: "payroll-compensation.create" },
  lookupApiPaths: {
    employeeId: "/api/employees",
    currency: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "employeeId",
      displayName: "Employee",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    { logicalName: "employeeName", displayName: "Employee", isPrimaryName: true, isReadOnly: true },
    { logicalName: "employeeCode", displayName: "Employee Code", isReadOnly: true },
    { logicalName: "workEmail", displayName: "Work Email", isReadOnly: true },
    { logicalName: "basicSalary", displayName: "Basic Salary", dataType: "currency" },
    {
      logicalName: "currency",
      displayName: "Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    { logicalName: "payFrequency", displayName: "Frequency", dataType: "optionset", options: payFrequencyOptions },
    { logicalName: "effectiveDate", displayName: "Effective Date", dataType: "date" },
    { logicalName: "endDate", displayName: "End Date", dataType: "date" },
    {
      logicalName: "payrollStatus",
      displayName: "Payroll Status",
      dataType: "optionset",
      options: status(["ACTIVE", "ON_HOLD", "STOPPED"]),
      isStatus: true,
    },
    { logicalName: "payrollGroup", displayName: "Payroll Group" },
    {
      logicalName: "paymentMode",
      displayName: "Payment Mode",
      dataType: "optionset",
      options: status(["BANK_TRANSFER", "CASH", "CHECK", "OTHER"]),
    },
    { logicalName: "bankName", displayName: "Bank Name" },
    { logicalName: "bankAccountTitle", displayName: "Bank Account Title" },
    { logicalName: "bankAccountNumber", displayName: "Bank Account Number" },
    { logicalName: "bankIban", displayName: "IBAN" },
    { logicalName: "bankRoutingNumber", displayName: "Routing Number" },
    { logicalName: "taxIdentifier", displayName: "Tax Identifier" },
    { logicalName: "notes", displayName: "Notes", dataType: "multiline-string" },
    { logicalName: "updatedAt", displayName: "Modified On", dataType: "datetime", isReadOnly: true },
  ],
  formFields: [
    "employeeId",
    "basicSalary",
    "currency",
    "payFrequency",
    "effectiveDate",
    "endDate",
    "payrollStatus",
    "payrollGroup",
    "paymentMode",
    "bankName",
    "bankAccountTitle",
    "bankAccountNumber",
    "bankIban",
    "bankRoutingNumber",
    "taxIdentifier",
    "notes",
  ],
  views: [
    {
      logicalName: "employee-compensation.all",
      viewId: "0bc11993-1aaf-410c-9fa9-c23e7c75255a",
      displayName: "All Compensation",
      columns: [
        "employeeName",
        "employeeCode",
        "workEmail",
        "basicSalary",
        "currency",
        "payFrequency",
        "payrollStatus",
        "paymentMode",
        "effectiveDate",
        "endDate",
      ],
      isDefault: true,
    },
  ],
};

export const payrollRunRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-runs",
  apiPath: "/api/payroll/runs",
  entityLogicalName: "payrollRun",
  collectionName: "payrollRuns",
  label: "Payroll Runs",
  singularLabel: "Payroll Run",
  routeBase: "/payroll/runs",
  primaryNameField: "runName",
  statusField: "status",
  permissions: {
    read: "payroll-runs.read",
    create: "payroll-runs.create",
    delete: "payroll-runs.delete",
  },
  adapterCapabilities: { disableEdit: true, softDelete: true },
  lookupApiPaths: {
    payrollPeriodId: "/api/payroll/periods",
    employerBankAccountId: "/api/payroll/employer-bank-accounts",
  },
  fields: [
    {
      logicalName: "runName",
      displayName: "Payroll Run",
      isPrimaryName: true,
    },
    {
      logicalName: "periodName",
      displayName: "Payroll Period",
      isReadOnly: true,
    },
    {
      logicalName: "payrollPeriodId",
      displayName: "Payroll Period",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "payrollPeriod",
    },
    { logicalName: "payrollCycleName", displayName: "Payroll Cycle", isReadOnly: true },
    { logicalName: "payrollCalendarName", displayName: "Payroll Calendar", isReadOnly: true },
    { logicalName: "payrollRegionName", displayName: "Payroll Region", isReadOnly: true },
    {
      logicalName: "employeeScope",
      displayName: "Employee Scope",
      dataType: "optionset",
      options: [
        { value: "ALL_ELIGIBLE_EMPLOYEES", label: "All Eligible Employees" },
        { value: "SELECTED_EMPLOYEES", label: "Selected Employees" },
      ],
    },
    {
      logicalName: "employerBankAccountId",
      displayName: "Employer Bank Account",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employerBankAccount",
    },
    {
      logicalName: "runNumber",
      displayName: "Run Number",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "DRAFT",
        "CALCULATING",
        "CALCULATED",
        "REVIEWED",
        "APPROVED",
        "PAID",
        "LOCKED",
        "FAILED",
      ]),
      isStatus: true,
      isReadOnly: true,
    },
    {
      logicalName: "calculatedAt",
      displayName: "Calculated At",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "lockedAt",
      displayName: "Locked At",
      dataType: "datetime",
      isReadOnly: true,
    },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    { logicalName: "employeeCode", displayName: "Employee Code", isReadOnly: true },
    { logicalName: "projectName", displayName: "Project", isReadOnly: true },
    { logicalName: "customerName", displayName: "Customer", isReadOnly: true },
    { logicalName: "allocationPercentage", displayName: "Allocation %", dataType: "number", isReadOnly: true },
    { logicalName: "originalAmount", displayName: "Original Cost", dataType: "currency", isReadOnly: true },
    { logicalName: "reportingAmount", displayName: "Reporting Cost", dataType: "currency", isReadOnly: true },
    { logicalName: "isBench", displayName: "Bench", dataType: "boolean", isReadOnly: true },
    { logicalName: "label", displayName: "Label", isReadOnly: true },
    { logicalName: "amount", displayName: "Amount", dataType: "currency", isReadOnly: true },
    { logicalName: "currencyCode", displayName: "Currency", isReadOnly: true },
    { logicalName: "category", displayName: "Category", isReadOnly: true },
    { logicalName: "reason", displayName: "Reason", isReadOnly: true },
    { logicalName: "notes", displayName: "Notes", isReadOnly: true },
    { logicalName: "sourceReference", displayName: "Source Reference", isReadOnly: true },
  ],
  formSections: [
    {
      id: "payroll-run.summary",
      tabKey: "general",
      label: "Run Details",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "runName", order: 10 },
        { fieldLogicalName: "runNumber", order: 20 },
        { fieldLogicalName: "status", order: 30 },
        { fieldLogicalName: "employeeScope", order: 40 },
      ],
    },
    {
      id: "payroll-run.period",
      tabKey: "general",
      label: "Period & Source",
      order: 20,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "payrollPeriodId", order: 10 },
        { fieldLogicalName: "payrollCycleName", order: 20 },
        { fieldLogicalName: "payrollCalendarName", order: 30 },
        { fieldLogicalName: "payrollRegionName", order: 40 },
        { fieldLogicalName: "employerBankAccountId", order: 50 },
      ],
    },
    {
      id: "payroll-run.timestamps",
      tabKey: "general",
      label: "Processing",
      order: 30,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "calculatedAt", order: 10 },
        { fieldLogicalName: "lockedAt", order: 20 },
        { fieldLogicalName: "notes", order: 30, columnSpan: 2 },
      ],
    },
  ],
  quickCreateFormFields: ["payrollPeriodId", "employeeScope"],
  views: [
    {
      logicalName: "payroll-runs.all",
      viewId: "07fe81dc-c70c-4f37-b95c-2f6f8fbc6821",
      displayName: "All Payroll Runs",
      columns: [
        "runName",
        "periodName",
        "runNumber",
        "status",
        "calculatedAt",
        "lockedAt",
      ],
      isDefault: true,
    },
  ],
  relatedTabs: [
    {
      tabKey: "adjustments",
      label: "Adjustments",
      order: 70,
      relationshipName: "payroll_run_adjustments",
      relatedEntityLogicalName: "payrollAdjustment",
      targetFieldLogicalName: "payrollRunId",
      columns: [
        "employeeName",
        "label",
        "category",
        "amount",
        "currencyCode",
        "status",
        "reason",
        "sourceReference",
      ],
      pageSize: 20,
      listPath: "/api/payroll/runs/{parentId}/adjustments",
    },
    {
      tabKey: "cost-allocation",
      label: "Cost Allocation",
      order: 80,
      relationshipName: "payroll_run_cost_allocations",
      relatedEntityLogicalName: "payrollCostAllocationLine",
      targetFieldLogicalName: "payrollRunId",
      columns: [
        "employeeName",
        "projectName",
        "customerName",
        "allocationPercentage",
        "originalAmount",
        "reportingAmount",
        "isBench",
      ],
      pageSize: 20,
      listPath: "/api/payroll/runs/{parentId}/cost-allocations",
    },
  ],
};

export const payslipRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payslips",
  apiPath: "/api/payslips",
  entityLogicalName: "payslip",
  collectionName: "payslips",
  label: "Payslips",
  singularLabel: "Payslip",
  routeBase: "/payroll/payslips",
  primaryNameField: "payslipNumber",
  statusField: "status",
  permissions: { read: "payslips.read-all" },
  recordNavigation: true,
  adapterCapabilities: { disableCreate: true, disableEdit: true },
  fields: [
    {
      logicalName: "payslipNumber",
      displayName: "Payslip",
      isPrimaryName: true,
      isReadOnly: true,
    },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "periodName",
      displayName: "Payroll Period",
      isReadOnly: true,
    },
    { logicalName: "currencyCode", displayName: "Currency", isReadOnly: true },
    {
      logicalName: "grossEarnings",
      displayName: "Gross Earnings",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "totalDeductions",
      displayName: "Deductions",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "netPay",
      displayName: "Net Pay",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status(["DRAFT", "GENERATED", "PUBLISHED", "VOID"]),
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "payslips.all",
      viewId: "95d422d5-969c-423b-a589-62d1178d4b01",
      displayName: "All Payslips",
      columns: [
        "payslipNumber",
        "employeeName",
        "periodName",
        "grossEarnings",
        "totalDeductions",
        "netPay",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const loanRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "loans",
  apiPath: "/api/loans",
  entityLogicalName: "loanRequest",
  collectionName: "loans",
  label: "Loan Requests",
  singularLabel: "Loan Request",
  routeBase: "/loans",
  primaryNameField: "requestNumber",
  statusField: "status",
  permissions: {
    read: "loans.read-all",
    create: "loans.create",
    update: "loans.update",
  },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    loanPolicyId: "/api/loan-policies",
    currencyCode: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "requestNumber",
      displayName: "Loan Request",
      isPrimaryName: true,
      isReadOnly: true,
    },
    {
      logicalName: "employeeId",
      displayName: "Employee",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "loanPolicyId",
      displayName: "Loan Policy",
      dataType: "lookup",
    },
    {
      logicalName: "requestedAmount",
      displayName: "Requested Amount",
      dataType: "currency",
    },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "installmentCount",
      displayName: "Installments",
      dataType: "number",
    },
    {
      logicalName: "requestedStartDate",
      displayName: "Start Date",
      dataType: "date",
    },
    {
      logicalName: "reason",
      displayName: "Reason",
      dataType: "multiline-string",
    },
    {
      logicalName: "outstandingBalance",
      displayName: "Outstanding",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "DRAFT",
        "PENDING_APPROVAL",
        "APPROVED",
        "ACTIVE",
        "REJECTED",
        "SETTLED",
        "CANCELLED",
      ]),
      isStatus: true,
    },
  ],
  formFields: [
    "employeeId",
    "loanPolicyId",
    "requestedAmount",
    "currencyCode",
    "installmentCount",
    "requestedStartDate",
    "reason",
  ],
  views: [
    {
      logicalName: "loans.all",
      viewId: "b626aee6-a7d5-4fcf-a5c5-9cf8591e5e31",
      displayName: "All Loan Requests",
      columns: [
        "requestNumber",
        "employeeName",
        "requestedAmount",
        "currencyCode",
        "installmentCount",
        "outstandingBalance",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const benefitAssignmentRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "benefit-assignments",
  apiPath: "/api/benefits/assignments",
  entityLogicalName: "employeeBenefitAssignment",
  collectionName: "benefitAssignments",
  label: "Employee Benefit Assignments",
  singularLabel: "Benefit Assignment",
  routeBase: "/benefits/assignments",
  primaryNameField: "assignmentName",
  statusField: "status",
  permissions: { read: "benefits.read", create: "benefits.assign" },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    benefitPolicyId: "/api/benefits/policies",
    currencyCodeOverride: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "assignmentName",
      displayName: "Benefit Assignment",
      isPrimaryName: true,
      isReadOnly: true,
    },
    { logicalName: "employeeId", displayName: "Employee", dataType: "lookup" },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    {
      logicalName: "benefitPolicyId",
      displayName: "Benefit Policy",
      dataType: "lookup",
    },
    { logicalName: "benefitName", displayName: "Benefit", isReadOnly: true },
    {
      logicalName: "fixedAmountOverride",
      displayName: "Fixed Amount Override",
      dataType: "currency",
    },
    {
      logicalName: "percentageOverride",
      displayName: "Percentage Override",
      dataType: "decimal",
    },
    {
      logicalName: "currencyCodeOverride",
      displayName: "Currency Override",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "effectiveFrom",
      displayName: "Effective From",
      dataType: "date",
    },
    {
      logicalName: "effectiveTo",
      displayName: "Effective To",
      dataType: "date",
    },
    {
      logicalName: "allocatedBalance",
      displayName: "Allocated Balance",
      dataType: "currency",
    },
    {
      logicalName: "consumedBalance",
      displayName: "Consumed Balance",
      dataType: "currency",
      isReadOnly: true,
    },
    {
      logicalName: "notes",
      displayName: "Notes",
      dataType: "multiline-string",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: status([
        "PENDING_APPROVAL",
        "ACTIVE",
        "SUSPENDED",
        "EXPIRED",
        "CANCELLED",
      ]),
      isStatus: true,
    },
  ],
  formFields: [
    "employeeId",
    "benefitPolicyId",
    "fixedAmountOverride",
    "percentageOverride",
    "currencyCodeOverride",
    "effectiveFrom",
    "effectiveTo",
    "allocatedBalance",
    "notes",
  ],
  views: [
    {
      logicalName: "benefit-assignments.all",
      viewId: "d2f840a8-48f6-48d6-94f1-c24df3c1dc22",
      displayName: "All Benefit Assignments",
      columns: [
        "assignmentName",
        "employeeName",
        "benefitName",
        "effectiveFrom",
        "effectiveTo",
        "allocatedBalance",
        "consumedBalance",
        "status",
      ],
      isDefault: true,
    },
  ],
};

export const employeeBankAccountRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "employee-bank-accounts",
  apiPath: "/api/employee-bank-accounts",
  entityLogicalName: "employeeBankAccount",
  collectionName: "employeeBankAccounts",
  label: "Employee Bank Accounts",
  singularLabel: "Employee Bank Account",
  routeBase: "/employee-bank-accounts",
  primaryNameField: "accountTitle",
  statusField: "verificationStatus",
  permissions: {
    read: "employee-bank-accounts.read",
    create: "employee-bank-accounts.manage",
    update: "employee-bank-accounts.manage",
    delete: "employee-bank-accounts.manage",
    export: "employee-bank-accounts.read",
    share: "employee-bank-accounts.read",
  },
  adapterCapabilities: { disableEdit: true },
  lookupApiPaths: {
    employeeId: "/api/employees",
    bankId: "/api/banks",
    countryCode: "/api/lookups/countries",
    currencyCode: "/api/configuration/currencies",
  },
  fields: [
    {
      logicalName: "accountTitle",
      displayName: "Account Title",
      isPrimaryName: true,
    },
    {
      logicalName: "employeeId",
      displayName: "Employee",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    { logicalName: "employeeName", displayName: "Employee", isReadOnly: true },
    { logicalName: "bankId", displayName: "Bank", dataType: "lookup", lookupTargetEntityLogicalName: "bank" },
    { logicalName: "bankName", displayName: "Bank", isReadOnly: true },
    { logicalName: "accountNumber", displayName: "Account Number" },
    { logicalName: "iban", displayName: "IBAN" },
    { logicalName: "swiftOrRoutingCode", displayName: "SWIFT / Routing Code" },
    { logicalName: "countryCode", displayName: "Country", dataType: "lookup", lookupTargetEntityLogicalName: "country" },
    {
      logicalName: "currencyCode",
      displayName: "Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "isPrimaryPayroll",
      displayName: "Primary Payroll Account",
      dataType: "boolean",
    },
    {
      logicalName: "effectiveFrom",
      displayName: "Effective From",
      dataType: "date",
    },
    {
      logicalName: "effectiveTo",
      displayName: "Effective To",
      dataType: "date",
    },
    {
      logicalName: "verificationStatus",
      displayName: "Verification",
      dataType: "optionset",
      options: status(["UNVERIFIED", "PENDING", "VERIFIED", "REJECTED"]),
      isStatus: true,
    },
    { logicalName: "isActive", displayName: "Active", dataType: "boolean" },
  ],
  formFields: [
    "employeeId",
    "bankId",
    "accountTitle",
    "accountNumber",
    "iban",
    "swiftOrRoutingCode",
    "countryCode",
    "currencyCode",
    "isPrimaryPayroll",
    "effectiveFrom",
    "effectiveTo",
  ],
  views: [
    {
      logicalName: "employee-bank-accounts.all",
      viewId: "ea166ec7-c713-4a7f-97d4-3e5393901ecb",
      displayName: "All Employee Bank Accounts",
      columns: [
        "accountTitle",
        "employeeName",
        "bankName",
        "accountNumber",
        "iban",
        "currencyCode",
        "isPrimaryPayroll",
        "verificationStatus",
      ],
      isDefault: true,
    },
  ],
  commands: [
    {
      key: "employeeBankAccounts.submitVerification",
      label: "Submit Verification",
      description: "Submit this employee bank account for verification.",
      scope: "record",
      placement: "detail-command-bar",
      executionMode: "client",
      handlerKey: "employeeBankAccounts.submitVerification",
      order: 35,
      permission: {
        permissionKey: "employee-bank-accounts.manage",
        anyPermissionKeys: [
          "employee-bank-accounts.manage",
          "employee-bank-accounts.verify",
        ],
      },
      visibilityRules: [
        {
          operator: "field-equals",
          fieldLogicalName: "isActive",
          expectedValue: true,
        },
        {
          operator: "field-not-equals",
          fieldLogicalName: "verificationStatus",
          expectedValue: "PENDING",
        },
        {
          operator: "field-not-equals",
          fieldLogicalName: "verificationStatus",
          expectedValue: "VERIFIED",
        },
      ],
    },
    {
      key: "employeeBankAccounts.verify",
      label: "Verify Account",
      description: "Mark this employee bank account as verified.",
      scope: "record",
      placement: "detail-command-bar",
      executionMode: "client",
      handlerKey: "employeeBankAccounts.verify",
      order: 36,
      permission: {
        permissionKey: "employee-bank-accounts.verify",
        anyPermissionKeys: [
          "employee-bank-accounts.verify",
          "employee-bank-accounts.manage",
        ],
      },
      visibilityRules: [
        {
          operator: "field-equals",
          fieldLogicalName: "isActive",
          expectedValue: true,
        },
        {
          operator: "field-not-equals",
          fieldLogicalName: "verificationStatus",
          expectedValue: "VERIFIED",
        },
      ],
    },
    {
      key: "employeeBankAccounts.setPayroll",
      label: "Set As Payroll",
      description: "Set this verified bank account as the primary payroll account.",
      scope: "record",
      placement: "detail-command-bar",
      executionMode: "client",
      handlerKey: "employeeBankAccounts.setPayroll",
      order: 37,
      permission: {
        permissionKey: "employee-bank-accounts.manage",
        anyPermissionKeys: [
          "employee-bank-accounts.manage",
          "employee-bank-accounts.verify",
        ],
      },
      visibilityRules: [
        {
          operator: "field-equals",
          fieldLogicalName: "isActive",
          expectedValue: true,
        },
        {
          operator: "field-equals",
          fieldLogicalName: "verificationStatus",
          expectedValue: "VERIFIED",
        },
        {
          operator: "field-not-equals",
          fieldLogicalName: "isPrimaryPayroll",
          expectedValue: true,
        },
      ],
    },
  ],
};

export const bankRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "banks",
  apiPath: "/api/banks",
  entityLogicalName: "bank",
  collectionName: "banks",
  label: "Banks",
  singularLabel: "Bank",
  routeBase: "/settings/payroll/banking/banks",
  primaryNameField: "name",
  statusField: "isActive",
  permissions: {
    read: "payroll.settings.read",
    create: "payroll.settings.update",
    update: "payroll.settings.update",
  },
  lookupApiPaths: {
    countryCode: "/api/lookups/countries",
  },
  fields: [
    { logicalName: "name", displayName: "Bank", isPrimaryName: true },
    { logicalName: "code", displayName: "Bank Code" },
    {
      logicalName: "countryCode",
      displayName: "Country",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "country",
    },
    { logicalName: "swiftCode", displayName: "SWIFT Code" },
    { logicalName: "routingCode", displayName: "Routing Code" },
    { logicalName: "isActive", displayName: "Active", dataType: "boolean", isStatus: true },
    { logicalName: "updatedAt", displayName: "Modified On", dataType: "datetime", isReadOnly: true },
  ],
  formFields: ["name", "code", "countryCode", "swiftCode", "routingCode", "isActive"],
  views: [
    {
      logicalName: "banks.all",
      viewId: "fdf71412-3696-46d5-9d50-9bdf8c68cf97",
      displayName: "All Banks",
      columns: ["name", "code", "countryCode", "swiftCode", "routingCode", "isActive"],
      isDefault: true,
    },
  ],
};

export const employerBankAccountRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "employer-bank-accounts",
  apiPath: "/api/payroll/employer-bank-accounts",
  entityLogicalName: "employerBankAccount",
  collectionName: "employerBankAccounts",
  label: "Employer Bank Accounts",
  singularLabel: "Employer Bank Account",
  routeBase: "/settings/payroll/banking/employer-bank-accounts",
  primaryNameField: "name",
  statusField: "isActive",
  permissions: {
    read: "payroll.settings.read",
    create: "payroll.settings.update",
    update: "payroll.settings.update",
  },
  lookupApiPaths: {
    bankId: "/api/banks",
    currencyCode: "/api/configuration/currencies",
  },
  fields: [
    { logicalName: "name", displayName: "Account Name", isPrimaryName: true },
    { logicalName: "bankId", displayName: "Bank", dataType: "lookup", lookupTargetEntityLogicalName: "bank" },
    { logicalName: "bankName", displayName: "Bank", isReadOnly: true },
    { logicalName: "accountTitle", displayName: "Account Title" },
    { logicalName: "accountNumber", displayName: "Account Number" },
    { logicalName: "iban", displayName: "IBAN" },
    { logicalName: "branch", displayName: "Branch" },
    { logicalName: "currencyCode", displayName: "Currency", dataType: "lookup", lookupTargetEntityLogicalName: "currency" },
    {
      logicalName: "accountPurpose",
      displayName: "Account Purpose",
      dataType: "optionset",
      options: status(["PAYROLL", "OPERATING", "TAX", "BENEFITS", "OTHER"]),
    },
    { logicalName: "isDefaultPayrollAccount", displayName: "Default Payroll Account", dataType: "boolean" },
    {
      logicalName: "paymentFileFormat",
      displayName: "Payment File Format",
      dataType: "optionset",
      options: status(["CSV", "EXCEL", "GENERIC_BANK_TRANSFER", "BANK_PORTAL"]),
    },
    { logicalName: "description", displayName: "Description", dataType: "multiline-string" },
    { logicalName: "isActive", displayName: "Active", dataType: "boolean", isStatus: true },
  ],
  formFields: [
    "name",
    "bankId",
    "accountTitle",
    "accountNumber",
    "iban",
    "branch",
    "currencyCode",
    "accountPurpose",
    "isDefaultPayrollAccount",
    "paymentFileFormat",
    "description",
  ],
  views: [
    {
      logicalName: "employer-bank-accounts.all",
      viewId: "f334dd64-ad95-4b84-8bd5-74526353e3de",
      displayName: "All Employer Bank Accounts",
      columns: [
        "name",
        "bankName",
        "accountTitle",
        "iban",
        "currencyCode",
        "accountPurpose",
        "isDefaultPayrollAccount",
        "isActive",
      ],
      isDefault: true,
    },
  ],
};

export const payrollExceptionRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "payroll-exceptions",
  apiPath: "/api/payroll/operations/exceptions",
  entityLogicalName: "payrollException",
  collectionName: "payrollExceptions",
  label: "Payroll Exceptions",
  singularLabel: "Payroll Exception",
  routeBase: "/payroll/exceptions",
  recordNavigation: false,
  primaryNameField: "issue",
  permissions: {
    read: "payroll-exceptions.read",
    export: "payroll-exceptions.export",
  },
  adapterCapabilities: {
    disableCreate: true,
    disableEdit: true,
    import: false,
    export: true,
    exportTemplate: false,
  },
  fields: [
    { logicalName: "employee", displayName: "Employee", isPrimaryName: true, isReadOnly: true },
    { logicalName: "employeeCode", displayName: "Employee Code", isReadOnly: true },
    { logicalName: "issue", displayName: "Issue", dataType: "multiline-string", isReadOnly: true },
    { logicalName: "severity", displayName: "Severity", dataType: "optionset", options: status(["INFO", "WARNING", "ERROR", "BLOCKER"]), isStatus: true, isReadOnly: true },
    { logicalName: "category", displayName: "Category", isReadOnly: true },
    { logicalName: "suggestedResolution", displayName: "Suggested Resolution", dataType: "multiline-string", isReadOnly: true },
    { logicalName: "openRecordUrl", displayName: "Open Record", dataType: "url", isReadOnly: true },
  ],
  views: [{
    logicalName: "payroll-exceptions.open",
    viewId: "3825e055-6545-4199-814c-7ed2430df223",
    displayName: "Open Payroll Exceptions",
    columns: ["employee", "employeeCode", "issue", "severity", "category", "suggestedResolution", "openRecordUrl"],
    isDefault: true,
  }],
};
