import { PERMISSION_KEYS } from "@/lib/security-keys";
import type { CommandDefinition } from "../command-runtime.types";
import type { StandardModuleRuntimeSpec } from "./standard-module-runtime";

const ACTIVE_STATUS_OPTIONS = [
  { value: "ACTIVE", label: "Active" },
  { value: "INACTIVE", label: "Inactive" },
] as const;

const APPROVAL_STATUS_OPTIONS = [
  { value: "PENDING", label: "Pending" },
  { value: "APPROVED", label: "Approved" },
  { value: "REJECTED", label: "Rejected" },
  { value: "CANCELLED", label: "Cancelled" },
] as const;

const RECRUITMENT_STAGE_OPTIONS = [
  { value: "APPLIED", label: "Applied" },
  { value: "SCREENING", label: "Screening" },
  { value: "SHORTLISTED", label: "Shortlisted" },
  { value: "INTERVIEW", label: "Interview" },
  { value: "FINAL_REVIEW", label: "Final Review" },
  { value: "OFFER", label: "Offer" },
  { value: "APPROVED", label: "Approved" },
  { value: "HIRED", label: "Hired" },
  { value: "ON_HOLD", label: "On Hold" },
  { value: "REJECTED", label: "Rejected" },
  { value: "WITHDRAWN", label: "Withdrawn" },
] as const;

const JOB_OPENING_STATUS_OPTIONS = [
  { value: "DRAFT", label: "Draft" },
  { value: "OPEN", label: "Open" },
  { value: "ON_HOLD", label: "On Hold" },
  { value: "CLOSED", label: "Closed" },
  { value: "FILLED", label: "Filled" },
  { value: "Cancelled", label: "Cancelled" },
] as const;

const JOB_OPENING_EDUCATION_LEVEL_OPTIONS = [
  { value: "High School", label: "High School" },
  { value: "Diploma", label: "Diploma" },
  { value: "Bachelor's", label: "Bachelor's" },
  { value: "Master's", label: "Master's" },
  { value: "MPhil", label: "MPhil" },
  { value: "PhD", label: "PhD" },
] as const;

const JOB_OPENING_WORK_MODE_OPTIONS = [
  { value: "Onsite", label: "Onsite" },
  { value: "Hybrid", label: "Hybrid" },
  { value: "Remote", label: "Remote" },
] as const;

const ONBOARDING_STATUS_OPTIONS = [
  { value: "DRAFT", label: "Draft" },
  { value: "NOT_STARTED", label: "Not Started" },
  { value: "IN_PROGRESS", label: "In Progress" },
  { value: "AWAITING_CANDIDATE_INPUT", label: "Awaiting Candidate Input" },
  { value: "READY_FOR_CONVERSION", label: "Ready For Conversion" },
  { value: "BLOCKED", label: "Blocked" },
  { value: "COMPLETED", label: "Completed" },
  { value: "CANCELLED", label: "Cancelled" },
] as const;

const INDUSTRY_OPTIONS = [
  { value: "Healthcare", label: "Healthcare" },
  { value: "IT / Software", label: "IT / Software" },
  { value: "Recruitment", label: "Recruitment" },
  { value: "Staffing", label: "Staffing" },
  { value: "Professional Services", label: "Professional Services" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Construction", label: "Construction" },
  { value: "Education", label: "Education" },
  { value: "Retail", label: "Retail" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Financial Services", label: "Financial Services" },
  { value: "Government", label: "Government" },
  { value: "Nonprofit", label: "Nonprofit" },
  { value: "Other", label: "Other" },
] as const;

const PROJECT_STATUS_OPTIONS = [
  { value: "DRAFT", label: "Draft" },
  { value: "PLANNING", label: "Planning" },
  { value: "ACTIVE", label: "Active" },
  { value: "ON_HOLD", label: "On Hold" },
  { value: "COMPLETED", label: "Completed" },
  { value: "CLOSED", label: "Closed" },
  { value: "CANCELLED", label: "Cancelled" },
] as const;

const PROJECT_BILLING_TYPE_OPTIONS = [
  { value: "NON_BILLABLE", label: "Non-billable" },
  { value: "FIXED_PRICE", label: "Fixed price" },
  { value: "TIME_AND_MATERIAL", label: "Time and material" },
  { value: "RETAINER", label: "Retainer" },
] as const;

const PROJECT_TYPE_OPTIONS = [
  { value: "CLIENT", label: "Client" },
  { value: "IMPLEMENTATION", label: "Implementation" },
  { value: "SUPPORT", label: "Support" },
  { value: "MAINTENANCE", label: "Maintenance" },
  { value: "INTERNAL", label: "Internal" },
  { value: "RESEARCH", label: "Research" },
  { value: "TRAINING", label: "Training" },
  { value: "OTHER", label: "Other" },
] as const;

const PROJECT_HEALTH_OPTIONS = [
  { value: "UNKNOWN", label: "Unknown" },
  { value: "GREEN", label: "Green" },
  { value: "AMBER", label: "Amber" },
  { value: "RED", label: "Red" },
] as const;

const PROJECT_RISK_OPTIONS = [
  { value: "LOW", label: "Low" },
  { value: "MEDIUM", label: "Medium" },
  { value: "HIGH", label: "High" },
  { value: "CRITICAL", label: "Critical" },
] as const;

const PROJECT_PRIORITY_OPTIONS = [
  { value: "LOW", label: "Low" },
  { value: "NORMAL", label: "Normal" },
  { value: "HIGH", label: "High" },
  { value: "CRITICAL", label: "Critical" },
] as const;

const PROJECT_DELIVERY_STATUS_OPTIONS = [
  { value: "NOT_STARTED", label: "Not started" },
  { value: "ON_TRACK", label: "On track" },
  { value: "AT_RISK", label: "At risk" },
  { value: "DELAYED", label: "Delayed" },
  { value: "DELIVERED", label: "Delivered" },
] as const;

const PROJECT_BILLING_STATUS_OPTIONS = [
  { value: "NOT_BILLABLE", label: "Not billable" },
  { value: "NOT_STARTED", label: "Not started" },
  { value: "IN_PROGRESS", label: "In progress" },
  { value: "READY_TO_BILL", label: "Ready to bill" },
  { value: "BILLED", label: "Billed" },
] as const;

const PROJECT_APPROVAL_MODE_OPTIONS = [
  { value: "NONE", label: "No approval required" },
  { value: "PROJECT_MANAGER", label: "Project manager" },
  { value: "ACCOUNT_MANAGER", label: "Account manager" },
  { value: "DELIVERY_MANAGER", label: "Delivery manager" },
  { value: "MANAGER", label: "Employee reporting manager" },
  { value: "BOTH", label: "Project manager + reporting manager" },
  { value: "CUSTOM_MANAGER", label: "Custom approval manager" },
] as const;

const PROJECT_ALLOCATION_TYPE_OPTIONS = [
  { value: "PERCENTAGE", label: "Percentage" },
  { value: "HOURS", label: "Hours" },
] as const;

const PROJECT_RESOURCE_STATUS_OPTIONS = [
  { value: "ACTIVE", label: "Active" },
  { value: "INACTIVE", label: "Inactive" },
] as const;

const PROJECT_ROLE_OPTIONS = [
  { value: "PROJECT_MANAGER", label: "Project Manager" },
  { value: "PROGRAM_MANAGER", label: "Program Manager" },
  { value: "DELIVERY_MANAGER", label: "Delivery Manager" },
  { value: "ACCOUNT_MANAGER", label: "Account Manager" },
  { value: "BUSINESS_ANALYST", label: "Business Analyst" },
  { value: "PRODUCT_OWNER", label: "Product Owner" },
  { value: "SCRUM_MASTER", label: "Scrum Master" },
  { value: "SOLUTION_ARCHITECT", label: "Solution Architect" },
  { value: "TECHNICAL_LEAD", label: "Technical Lead" },
  { value: "TEAM_LEAD", label: "Team Lead" },
  { value: "SOFTWARE_ENGINEER", label: "Software Engineer" },
  { value: "FRONTEND_ENGINEER", label: "Frontend Engineer" },
  { value: "BACKEND_ENGINEER", label: "Backend Engineer" },
  { value: "FULL_STACK_ENGINEER", label: "Full-stack Engineer" },
  { value: "MOBILE_ENGINEER", label: "Mobile Engineer" },
  { value: "DEVOPS_ENGINEER", label: "DevOps Engineer" },
  { value: "QA_ENGINEER", label: "QA Engineer" },
  { value: "TEST_AUTOMATION_ENGINEER", label: "Test Automation Engineer" },
  { value: "UI_UX_DESIGNER", label: "UI/UX Designer" },
  { value: "DATA_ANALYST", label: "Data Analyst" },
  { value: "DATA_ENGINEER", label: "Data Engineer" },
  { value: "DATA_SCIENTIST", label: "Data Scientist" },
  { value: "AI_ML_ENGINEER", label: "AI/ML Engineer" },
  { value: "SECURITY_SPECIALIST", label: "Security Specialist" },
  { value: "IMPLEMENTATION_CONSULTANT", label: "Implementation Consultant" },
  { value: "FUNCTIONAL_CONSULTANT", label: "Functional Consultant" },
  { value: "TECHNICAL_CONSULTANT", label: "Technical Consultant" },
  { value: "SUPPORT_ENGINEER", label: "Support Engineer" },
  { value: "TRAINER", label: "Trainer" },
  { value: "CONTENT_SPECIALIST", label: "Content Specialist" },
  { value: "MARKETING_SPECIALIST", label: "Marketing Specialist" },
  { value: "SALES_CONSULTANT", label: "Sales Consultant" },
  { value: "FINANCE_ANALYST", label: "Finance Analyst" },
  { value: "HR_CONSULTANT", label: "HR Consultant" },
  { value: "LEGAL_ADVISOR", label: "Legal Advisor" },
  { value: "OPERATIONS_SPECIALIST", label: "Operations Specialist" },
  { value: "PROCUREMENT_SPECIALIST", label: "Procurement Specialist" },
  { value: "FIELD_ENGINEER", label: "Field Engineer" },
  { value: "SITE_SUPERVISOR", label: "Site Supervisor" },
  { value: "OTHER", label: "Other" },
] as const;

export const customerRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "customers",
  apiPath: "/api/customers",
  entityLogicalName: "customer",
  collectionName: "customers",
  label: "Customers",
  singularLabel: "Customer",
  routeBase: "/customers",
  capabilities: ["timeline"],
  timelineApiPath: "/api/customers/{recordId}/timeline",
  primaryNameField: "name",
  ownerField: "createdById",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.CUSTOMERS_READ,
    create: PERMISSION_KEYS.CUSTOMERS_CREATE,
    update: PERMISSION_KEYS.CUSTOMERS_WRITE,
    delete: PERMISSION_KEYS.CUSTOMERS_DELETE,
    assign: PERMISSION_KEYS.CUSTOMERS_ASSIGN,
    share: PERMISSION_KEYS.CUSTOMERS_SHARE,
  },
  lookupApiPaths: {
    countryId: "/api/lookups/countries",
    stateProvinceId: "/api/lookups/states",
    cityId: "/api/lookups/cities",
  },
  fields: [
    { logicalName: "name", displayName: "Company", isPrimaryName: true },
    { logicalName: "code", displayName: "Code", isReadOnly: true },
    {
      logicalName: "industry",
      displayName: "Industry",
      dataType: "optionset",
      options: INDUSTRY_OPTIONS,
    },
    { logicalName: "contactName", displayName: "Primary Contact" },
    {
      logicalName: "contactEmail",
      displayName: "Contact Email",
      dataType: "email",
    },
    {
      logicalName: "contactPhone",
      displayName: "Contact Phone",
      dataType: "phone",
    },
    {
      logicalName: "billingEmail",
      displayName: "Billing Email",
      dataType: "email",
    },
    { logicalName: "websiteUrl", displayName: "Website", dataType: "url" },
    {
      logicalName: "address",
      displayName: "Address Notes",
      dataType: "multiline-string",
    },
    { logicalName: "addressLine1", displayName: "Address Line 1" },
    { logicalName: "addressLine2", displayName: "Address Line 2" },
    {
      logicalName: "countryId",
      displayName: "Country",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "country",
    },
    {
      logicalName: "stateProvinceId",
      displayName: "State / Province",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "stateProvince",
      dependsOnFieldId: "countryId",
      dependencyFilterKey: "countryId",
      resetOnParentChange: true,
    },
    {
      logicalName: "cityId",
      displayName: "City",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "city",
      dependsOnFieldId: "stateProvinceId",
      dependencyFilterKey: "stateProvinceId",
      resetOnParentChange: true,
    },
    { logicalName: "postalCode", displayName: "Postal Code" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: ACTIVE_STATUS_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "projectCount",
      displayName: "Projects",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "createdById",
      displayName: "Owner",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "user",
      isOwner: true,
      isReadOnly: true,
    },
    {
      logicalName: "updatedById",
      displayName: "Modified By",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "user",
      isReadOnly: true,
    },
  ],
  formFields: [
    "name",
    "industry",
    "contactName",
    "contactEmail",
    "contactPhone",
    "billingEmail",
    "websiteUrl",
    "addressLine1",
    "addressLine2",
    "countryId",
    "stateProvinceId",
    "cityId",
    "postalCode",
    "address",
  ],
  formSections: [
    {
      id: "customers.main.company",
      tabKey: "general",
      label: "Company",
      order: 10,
      layout: "single-column",
      columns: 1,
      column: 1,
      fields: [
        { fieldLogicalName: "name", order: 10, requirementLevel: "required" },
        { fieldLogicalName: "industry", order: 20 },
        { fieldLogicalName: "websiteUrl", order: 30 },
      ],
    },
    {
      id: "customers.main.contact",
      tabKey: "general",
      label: "Contact",
      order: 20,
      layout: "single-column",
      columns: 1,
      column: 2,
      fields: [
        { fieldLogicalName: "contactName", order: 10 },
        { fieldLogicalName: "contactEmail", order: 20 },
        { fieldLogicalName: "contactPhone", order: 30 },
        { fieldLogicalName: "billingEmail", order: 40 },
      ],
    },
    {
      id: "customers.main.address",
      tabKey: "general",
      label: "Address",
      order: 30,
      layout: "single-column",
      columns: 1,
      column: 3,
      fields: [
        { fieldLogicalName: "addressLine1", order: 10 },
        { fieldLogicalName: "addressLine2", order: 20 },
        { fieldLogicalName: "countryId", order: 30 },
        { fieldLogicalName: "stateProvinceId", order: 40 },
        { fieldLogicalName: "cityId", order: 50 },
        { fieldLogicalName: "postalCode", order: 60 },
        { fieldLogicalName: "address", order: 70 },
      ],
    },
  ],
  views: [
    {
      logicalName: "customers.all",
      viewId: "00000000-0000-4000-8000-000000000601",
      displayName: "All Customers",
      columns: [
        "name",
        "code",
        "industry",
        "contactName",
        "projectCount",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
    {
      logicalName: "customers.active",
      viewId: "00000000-0000-4000-8000-000000000602",
      displayName: "Active Customers",
      columns: [
        "name",
        "code",
        "industry",
        "contactName",
        "projectCount",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "ACTIVE" },
      ],
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
  ],
  commands: [
    disabledBusinessCommand("customer.activate", "Activate"),
    disabledBusinessCommand("customer.deactivate", "Deactivate"),
    disabledBusinessCommand("customer.convert", "Convert"),
  ],
};

export const projectRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "projects",
  apiPath: "/api/projects",
  entityLogicalName: "project",
  collectionName: "projects",
  label: "Projects",
  singularLabel: "Project",
  routeBase: "/projects",
  capabilities: ["timeline", "documents"],
  timelineApiPath: "/api/projects/{recordId}/timeline",
  primaryNameField: "name",
  ownerField: "createdById",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.PROJECTS_READ,
    create: PERMISSION_KEYS.PROJECTS_CREATE,
    update: PERMISSION_KEYS.PROJECTS_UPDATE,
    assign: PERMISSION_KEYS.PROJECTS_ASSIGN,
  },
  lookupApiPaths: {
    approvalManagerEmployeeId: "/api/employees",
    accountManagerEmployeeId: "/api/employees",
    businessUnitId: "/api/business-units",
    budgetCurrencyCode: "/api/configuration/currencies",
    currencyCode: "/api/configuration/currencies",
    customerId: "/api/customers",
    deliveryManagerEmployeeId: "/api/employees",
    employeeId: "/api/employees",
    organizationId: "/api/organizations",
    projectManagerEmployeeId: "/api/employees",
    timezone: "/api/configuration/timezones",
  },
  fields: [
    { logicalName: "name", displayName: "Project Name", isPrimaryName: true },
    { logicalName: "code", displayName: "Project Code" },
    {
      logicalName: "description",
      displayName: "Description",
      dataType: "multiline-string",
    },
    {
      logicalName: "customerId",
      displayName: "Customer",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "customer",
    },
    { logicalName: "customerName", displayName: "Customer", isReadOnly: true },
    {
      logicalName: "projectType",
      displayName: "Project Type",
      dataType: "optionset",
      options: PROJECT_TYPE_OPTIONS,
    },
    {
      logicalName: "projectManagerEmployeeId",
      displayName: "Project Manager",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "accountManagerEmployeeId",
      displayName: "Account Manager",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "deliveryManagerEmployeeId",
      displayName: "Delivery Manager",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "organizationId",
      displayName: "Organization",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "organization",
    },
    {
      logicalName: "businessUnitId",
      displayName: "Business Unit",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "businessUnit",
      dependsOnFieldId: "organizationId",
      dependencyFilterKey: "organizationId",
      resetOnParentChange: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: PROJECT_STATUS_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "startDate",
      displayName: "Planned Start Date",
      dataType: "date",
    },
    {
      logicalName: "endDate",
      displayName: "Planned End Date",
      dataType: "date",
    },
    {
      logicalName: "timezone",
      displayName: "Timezone",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "timezone",
    },
    {
      logicalName: "currencyCode",
      displayName: "Project Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "billingType",
      displayName: "Billing Type",
      dataType: "optionset",
      options: PROJECT_BILLING_TYPE_OPTIONS,
    },
    {
      logicalName: "budgetHours",
      displayName: "Budget Hours",
      dataType: "decimal",
    },
    {
      logicalName: "budgetAmount",
      displayName: "Budget Amount",
      dataType: "decimal",
    },
    {
      logicalName: "budgetCurrencyCode",
      displayName: "Budget Currency",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "currency",
    },
    {
      logicalName: "requiredResourceCount",
      displayName: "Resources Required",
      dataType: "number",
    },
    {
      logicalName: "requiredSkills",
      displayName: "Required Skills",
      dataType: "multiline-string",
    },
    {
      logicalName: "billableHours",
      displayName: "Billable Hours",
      dataType: "decimal",
    },
    {
      logicalName: "nonBillableHours",
      displayName: "Non-billable Hours",
      dataType: "decimal",
    },
    {
      logicalName: "billingRateAmount",
      displayName: "Billing Rate",
      dataType: "decimal",
    },
    {
      logicalName: "costBudgetAmount",
      displayName: "Cost Budget",
      dataType: "decimal",
    },
    {
      logicalName: "plannedHours",
      displayName: "Planned Hours",
      dataType: "decimal",
    },
    {
      logicalName: "actualHours",
      displayName: "Actual Hours",
      dataType: "decimal",
      isReadOnly: true,
    },
    {
      logicalName: "remainingHours",
      displayName: "Remaining Hours",
      dataType: "decimal",
      isReadOnly: true,
    },
    {
      logicalName: "projectHealth",
      displayName: "Project Health",
      dataType: "optionset",
      options: PROJECT_HEALTH_OPTIONS,
    },
    {
      logicalName: "riskLevel",
      displayName: "Risk Level",
      dataType: "optionset",
      options: PROJECT_RISK_OPTIONS,
    },
    {
      logicalName: "priority",
      displayName: "Priority",
      dataType: "optionset",
      options: PROJECT_PRIORITY_OPTIONS,
    },
    {
      logicalName: "deliveryStatus",
      displayName: "Delivery Status",
      dataType: "optionset",
      options: PROJECT_DELIVERY_STATUS_OPTIONS,
    },
    {
      logicalName: "billingStatus",
      displayName: "Billing Status",
      dataType: "optionset",
      options: PROJECT_BILLING_STATUS_OPTIONS,
    },
    {
      logicalName: "allowTimesheets",
      displayName: "Allow Timesheets",
      dataType: "boolean",
    },
    {
      logicalName: "requireApproval",
      displayName: "Require Approval",
      dataType: "boolean",
    },
    {
      logicalName: "approvalMode",
      displayName: "Require Approval",
      dataType: "optionset",
      options: PROJECT_APPROVAL_MODE_OPTIONS,
    },
    {
      logicalName: "approvalManagerEmployeeId",
      displayName: "Custom Approval Manager",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "assignedEmployeesCount",
      displayName: "Assigned Employees",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "createdById",
      displayName: "Owner",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "user",
      isOwner: true,
      isReadOnly: true,
    },
    {
      logicalName: "employeeId",
      displayName: "Employee",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "employeeName",
      displayName: "Employee",
      isReadOnly: true,
    },
    {
      logicalName: "employeeCode",
      displayName: "Employee Code",
      isReadOnly: true,
    },
    {
      logicalName: "projectRoleId",
      displayName: "Project Role",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "projectRole",
    },
    {
      logicalName: "projectRoleName",
      displayName: "Project Role",
      isReadOnly: true,
    },
    {
      logicalName: "roleOnProject",
      displayName: "Project Role",
      dataType: "optionset",
      options: PROJECT_ROLE_OPTIONS,
    },
    {
      logicalName: "allocationPercent",
      displayName: "Allocation %",
      dataType: "number",
    },
    {
      logicalName: "allocationHours",
      displayName: "Allocation Hours",
      dataType: "decimal",
    },
    {
      logicalName: "costRateAmount",
      displayName: "Cost Rate / Hour",
      dataType: "decimal",
    },
    {
      logicalName: "allocationType",
      displayName: "Allocation Type",
      dataType: "optionset",
      options: PROJECT_ALLOCATION_TYPE_OPTIONS,
    },
    {
      logicalName: "billableFlag",
      displayName: "Billable",
      dataType: "boolean",
    },
    {
      logicalName: "approvalManagerEmployeeId",
      displayName: "Approval Manager",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "employee",
    },
    {
      logicalName: "departmentName",
      displayName: "Department",
      isReadOnly: true,
    },
    {
      logicalName: "designationName",
      displayName: "Designation",
      isReadOnly: true,
    },
    {
      logicalName: "resourceStatus",
      displayName: "Resource Status",
      dataType: "optionset",
      options: PROJECT_RESOURCE_STATUS_OPTIONS,
    },
  ],
  formFields: [
    "name",
    "code",
    "customerId",
    "projectType",
    "projectManagerEmployeeId",
    "accountManagerEmployeeId",
    "deliveryManagerEmployeeId",
    "description",
    "organizationId",
    "businessUnitId",
    "startDate",
    "endDate",
    "timezone",
    "currencyCode",
    "billingType",
    "budgetHours",
    "budgetAmount",
    "budgetCurrencyCode",
    "requiredResourceCount",
    "requiredSkills",
    "plannedHours",
    "billableHours",
    "nonBillableHours",
    "billingRateAmount",
    "costBudgetAmount",
    "projectHealth",
    "riskLevel",
    "priority",
    "deliveryStatus",
    "billingStatus",
    "allowTimesheets",
    "approvalMode",
    "approvalManagerEmployeeId",
  ],
  formSections: [
    {
      id: "projects.main.identity",
      tabKey: "general",
      label: "Project",
      order: 10,
      layout: "single-column",
      columns: 1,
      column: 1,
      fields: [
        { fieldLogicalName: "name", order: 10, requirementLevel: "required" },
        { fieldLogicalName: "code", order: 20 },
        { fieldLogicalName: "customerId", order: 30 },
        { fieldLogicalName: "projectType", order: 40 },
        { fieldLogicalName: "projectManagerEmployeeId", order: 50 },
        { fieldLogicalName: "accountManagerEmployeeId", order: 60 },
        { fieldLogicalName: "deliveryManagerEmployeeId", order: 70 },
        { fieldLogicalName: "description", order: 80 },
      ],
    },
    {
      id: "projects.main.schedule",
      tabKey: "general",
      label: "Schedule & Scope",
      order: 20,
      layout: "single-column",
      columns: 1,
      column: 2,
      fields: [
        { fieldLogicalName: "organizationId", order: 10 },
        { fieldLogicalName: "businessUnitId", order: 20 },
        { fieldLogicalName: "startDate", order: 30 },
        { fieldLogicalName: "endDate", order: 40 },
        { fieldLogicalName: "timezone", order: 50 },
        { fieldLogicalName: "currencyCode", order: 60 },
        { fieldLogicalName: "requiredResourceCount", order: 70 },
        { fieldLogicalName: "requiredSkills", order: 80 },
      ],
    },
    {
      id: "projects.main.controls",
      tabKey: "general",
      label: "Commercials & Controls",
      order: 30,
      layout: "single-column",
      columns: 1,
      column: 3,
      fields: [
        { fieldLogicalName: "billingType", order: 10 },
        { fieldLogicalName: "budgetHours", order: 20 },
        { fieldLogicalName: "budgetAmount", order: 30 },
        { fieldLogicalName: "budgetCurrencyCode", order: 40 },
        { fieldLogicalName: "plannedHours", order: 50 },
        { fieldLogicalName: "billableHours", order: 60 },
        { fieldLogicalName: "nonBillableHours", order: 70 },
        { fieldLogicalName: "billingRateAmount", order: 80 },
        { fieldLogicalName: "costBudgetAmount", order: 90 },
        { fieldLogicalName: "projectHealth", order: 100 },
        { fieldLogicalName: "riskLevel", order: 110 },
        { fieldLogicalName: "priority", order: 120 },
        { fieldLogicalName: "deliveryStatus", order: 130 },
        { fieldLogicalName: "billingStatus", order: 140 },
        { fieldLogicalName: "allowTimesheets", order: 150 },
        { fieldLogicalName: "approvalMode", order: 160 },
        { fieldLogicalName: "approvalManagerEmployeeId", order: 170 },
      ],
    },
  ],
  widgets: [
    {
      id: "system.documents",
      widgetType: "documents",
      label: "Documents",
      tabKey: "documents",
      order: 25,
      columnSpan: 1,
    },
  ],
  relatedTabs: [
    {
      tabKey: "assigned-employees",
      label: "Assigned Employees",
      order: 30,
      relationshipName: "project_assignments",
      relatedEntityLogicalName: "projectAssignment",
      targetFieldLogicalName: "projectId",
      listPath: "/api/projects/{parentId}/assignments",
      createPath: "/api/projects/{parentId}/assignments",
      deletePath: "/api/projects/{parentId}/assignments/{recordId}",
      permissions: {
        create: PERMISSION_KEYS.PROJECTS_ASSIGN,
        delete: PERMISSION_KEYS.PROJECTS_ASSIGN,
      },
      columns: [
        "employeeName",
        "employeeCode",
        "projectRoleName",
        "allocationType",
        "allocationPercent",
        "allocationHours",
        "billableFlag",
        "billingRateAmount",
        "costRateAmount",
        "startDate",
        "endDate",
        "resourceStatus",
      ],
      assignment: {
        lookupFieldLogicalName: "employeeId",
        optionsPath: "/api/employees?pageSize=100",
        title: "Assign Employees",
        optionValueField: "id",
        optionLabelField: "fullName",
        optionDescriptionField: "workEmail",
        optionMetaFields: ["employeeCode", "departmentName", "designationName"],
        assignedValueField: "employeeId",
        extraFields: [
          {
            fieldLogicalName: "allocationType",
            label: "Allocation Type",
            dataType: "optionset",
            required: true,
            defaultValue: "PERCENTAGE",
            options: PROJECT_ALLOCATION_TYPE_OPTIONS,
          },
          {
            fieldLogicalName: "allocationPercent",
            label: "Allocation %",
            dataType: "number",
            required: true,
            defaultValue: "100",
          },
          {
            fieldLogicalName: "allocationHours",
            label: "Allocation Hours",
            dataType: "decimal",
          },
          {
            fieldLogicalName: "billableFlag",
            label: "Billable",
            dataType: "boolean",
            defaultValue: true,
          },
          {
            fieldLogicalName: "billingRateAmount",
            label: "Billing Rate / Hour",
            dataType: "decimal",
            required: true,
          },
          {
            fieldLogicalName: "costRateAmount",
            label: "Cost Rate / Hour",
            dataType: "decimal",
          },
          {
            fieldLogicalName: "startDate",
            label: "Allocation From",
            dataType: "date",
            required: true,
          },
          {
            fieldLogicalName: "endDate",
            label: "Allocation To",
            dataType: "date",
          },
          {
            fieldLogicalName: "roleOnProject",
            label: "Project Role",
            dataType: "optionset",
            required: true,
            options: PROJECT_ROLE_OPTIONS,
          },
          {
            fieldLogicalName: "resourceStatus",
            label: "Resource Status",
            dataType: "optionset",
            required: true,
            defaultValue: "ACTIVE",
            options: PROJECT_RESOURCE_STATUS_OPTIONS,
          },
        ],
      },
      quickCreateFields: [
        {
          fieldLogicalName: "employeeId",
          label: "Employee",
          dataType: "lookup",
          required: true,
        },
        {
          fieldLogicalName: "roleOnProject",
          label: "Project Role",
          dataType: "optionset",
        },
        {
          fieldLogicalName: "allocationType",
          label: "Allocation Type",
          dataType: "optionset",
        },
        {
          fieldLogicalName: "allocationPercent",
          label: "Allocation %",
          dataType: "number",
        },
        {
          fieldLogicalName: "allocationHours",
          label: "Allocation Hours",
          dataType: "decimal",
        },
        {
          fieldLogicalName: "billableFlag",
          label: "Billable",
          dataType: "boolean",
        },
        {
          fieldLogicalName: "startDate",
          label: "From",
          dataType: "date",
        },
        {
          fieldLogicalName: "endDate",
          label: "To",
          dataType: "date",
        },
        {
          fieldLogicalName: "approvalManagerEmployeeId",
          label: "Approval Manager",
          dataType: "lookup",
        },
        {
          fieldLogicalName: "resourceStatus",
          label: "Status",
          dataType: "optionset",
        },
      ],
    },
  ],
  views: [
    {
      logicalName: "projects.all",
      viewId: "00000000-0000-4000-8000-000000000501",
      displayName: "All Projects",
      columns: [
        "name",
        "code",
        "status",
        "customerName",
        "startDate",
        "endDate",
        "assignedEmployeesCount",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
    {
      logicalName: "projects.active",
      viewId: "00000000-0000-4000-8000-000000000502",
      displayName: "Active Projects",
      columns: [
        "name",
        "code",
        "status",
        "customerName",
        "startDate",
        "endDate",
        "assignedEmployeesCount",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "ACTIVE" },
      ],
    },
  ],
  commands: [
    disabledBusinessCommand("project.close", "Close"),
    disabledBusinessCommand("project.reopen", "Reopen"),
  ],
};

export const leaveRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "leaves",
  metadataTableKey: "leaveRequests",
  apiPath: "/api/leave-requests",
  entityLogicalName: "leaveRequest",
  collectionName: "leaveRequests",
  label: "Leaves",
  singularLabel: "Leave Request",
  routeBase: "/leaves",
  capabilities: ["timeline", "approvalTracking"],
  timelineApiPath: "/api/leave-requests/{recordId}/timeline",
  primaryNameField: "requestName",
  ownerField: "ownerId",
  statusField: "status",
  subStatusField: "subStatus",
  permissions: {
    read: PERMISSION_KEYS.LEAVE_REQUESTS_READ,
    create: PERMISSION_KEYS.LEAVE_REQUESTS_CREATE,
  },
  fields: [
    {
      logicalName: "requestName",
      displayName: "Leave Request",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    {
      logicalName: "ownerId",
      displayName: "Owner",
      dataType: "lookup",
      isOwner: true,
      // Read-only because SubmitLeaveRequestDto whitelists neither owner nor
      // status: a leave request is always raised for the caller, and its status
      // is driven by the approval workflow. The record-status header still
      // displays both; it just no longer serialises them into the create body,
      // which the API rejected outright — "property ownerId should not exist,
      // property status should not exist" — failing every submission.
      isReadOnly: true,
    },
    {
      logicalName: "leaveTypeId",
      displayName: "Leave Type",
      dataType: "lookup",
    },
    { logicalName: "leaveTypeName", displayName: "Leave Type" },
    { logicalName: "startDate", displayName: "Start Date", dataType: "date" },
    { logicalName: "endDate", displayName: "End Date", dataType: "date" },
    { logicalName: "durationDays", displayName: "Days", dataType: "number" },
    {
      logicalName: "reason",
      displayName: "Reason",
      dataType: "multiline-string",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
      // Read-only for the same reason as ownerId above: SubmitLeaveRequestDto
      // whitelists neither, and the approval workflow owns this value. Marking
      // only ownerId was not enough — `/leaves/new` seeds the draft with a
      // literal `record={{ status: "PENDING" }}`, and
      // `sanitizeStandardMutationValues` keeps any writable field present in the
      // draft, so `status` still reached the API and still 400'd.
      isReadOnly: true,
    },
    {
      logicalName: "subStatus",
      displayName: "Sub Status",
      dataType: "optionset",
      isSubStatus: true,
    },
  ],
  formFields: ["leaveTypeId", "startDate", "endDate", "reason"],
  quickCreateFormFields: ["leaveTypeId", "startDate", "endDate", "reason"],
  views: [
    {
      logicalName: "leaves.my",
      viewId: "00000000-0000-4000-8000-000000000101",
      displayName: "My Leave Requests",
      columns: [
        "requestName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
    {
      logicalName: "leaves.all",
      viewId: "00000000-0000-4000-8000-000000000102",
      displayName: "Team / Assigned Leave",
      columns: [
        "requestName",
        "employeeName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
    /*
     * Status views. Two views — mine and everyone's — left the common questions
     * unanswered: what is waiting on me, and what has already been decided.
     * Filtering on status rather than adding new endpoints keeps these entirely
     * declarative.
     */
    {
      logicalName: "leaves.pending",
      viewId: "00000000-0000-4000-8000-000000000103",
      displayName: "Pending Approval",
      columns: [
        "requestName",
        "employeeName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "PENDING" },
      ],
      /* Oldest first: the request waiting longest needs attention first. */
      defaultSort: [{ fieldLogicalName: "startDate", direction: "asc" }],
    },
    {
      logicalName: "leaves.approved",
      viewId: "00000000-0000-4000-8000-000000000104",
      displayName: "Approved Leave",
      columns: [
        "requestName",
        "employeeName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "APPROVED" },
      ],
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
    {
      logicalName: "leaves.rejected",
      viewId: "00000000-0000-4000-8000-000000000105",
      displayName: "Rejected Leave",
      columns: [
        "requestName",
        "employeeName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "reason",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "REJECTED" },
      ],
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
  ],
  commands: [
    disabledBusinessCommand("leave.submit", "Submit"),
    disabledBusinessCommand("leave.cancel", "Cancel"),
    leaveDecisionCommand(
      "leave.approve",
      "Approve",
      PERMISSION_KEYS.LEAVE_REQUESTS_APPROVE,
    ),
    leaveDecisionCommand(
      "leave.reject",
      "Reject",
      PERMISSION_KEYS.LEAVE_REQUESTS_REJECT,
    ),
  ],
  widgets: [
    {
      id: "system.leaveApprovalTracker",
      widgetType: "approval_tracker",
      label: "Leave Approval Tracker",
      columnSpan: 3,
      dataSource: {
        apiPath: "/api/approvals",
        recordIdQueryKey: "entityId",
        query: {
          moduleKey: "leave",
          pageSize: "10",
        },
      },
    },
    // Same generic documents widget the Employee and Project forms use, so
    // supporting evidence (medical certificates, approvals) lives with the
    // request instead of needing a leave-specific attachment feature.
    {
      id: "system.documents",
      widgetType: "documents",
      label: "Documents",
      tabKey: "documents",
      order: 40,
      columnSpan: 1,
    },
  ],
  widgetTabLabel: "Leave Tracker",
};

export const attendanceRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "attendance",
  metadataTableKey: "attendanceEntries",
  apiPath: "/api/attendance",
  createApiPath: "/api/attendance/manual",
  updateApiPath: "/api/attendance/{recordId}/override",
  entityLogicalName: "attendanceEntry",
  collectionName: "attendanceEntries",
  label: "Attendance",
  singularLabel: "Attendance Entry",
  routeBase: "/attendance",
  capabilities: ["timeline"],
  timelineApiPath: "/api/attendance/{recordId}/timeline",
  lookupApiPaths: {
    officeLocationId: "/api/attendance/locations",
    shiftTemplateId: "/api/attendance/shifts",
  },
  primaryNameField: "entryName",
  ownerField: "ownerId",
  statusField: "status",
  subStatusField: "subStatus",
  permissions: {
    read: PERMISSION_KEYS.ATTENDANCE_READ,
    create: PERMISSION_KEYS.ATTENDANCE_MANAGE,
    update: PERMISSION_KEYS.ATTENDANCE_UPDATE,
    delete: PERMISSION_KEYS.ATTENDANCE_UPDATE,
    import: PERMISSION_KEYS.ATTENDANCE_IMPORT,
    export: PERMISSION_KEYS.ATTENDANCE_EXPORT,
  },
  adapterCapabilities: { softDelete: true },
  fields: [
    {
      logicalName: "entryName",
      displayName: "Attendance Entry",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    {
      logicalName: "ownerId",
      displayName: "Owner",
      dataType: "lookup",
      isOwner: true,
    },
    {
      logicalName: "attendanceDate",
      displayName: "Date",
      dataType: "date",
      isReadOnly: true,
    },
    {
      logicalName: "attendanceMode",
      displayName: "Work Mode",
      dataType: "optionset",
      options: [
        { value: "OFFICE", label: "Office" },
        { value: "REMOTE", label: "Remote" },
        { value: "HYBRID", label: "Hybrid" },
      ],
    },
    {
      logicalName: "workSite",
      displayName: "Work Site",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "officeLocationId",
      displayName: "Work Site",
      dataType: "lookup",
    },
    {
      logicalName: "shift",
      displayName: "Shift",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "shiftTemplateId",
      displayName: "Shift",
      dataType: "lookup",
    },
    {
      logicalName: "checkIn",
      displayName: "Check In",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "checkOut",
      displayName: "Check Out",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "duration",
      displayName: "Total Working Time",
      isReadOnly: true,
    },
    {
      logicalName: "checkInLocation",
      displayName: "Check-In Location",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "checkOutLocation",
      displayName: "Check-Out Location",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      isStatus: true,
      options: [
        { value: "CHECKED_IN", label: "Checked In" },
        { value: "CHECKED_OUT", label: "Checked Out" },
        { value: "PRESENT", label: "Present" },
        { value: "LATE", label: "Late" },
        { value: "ABSENT", label: "Absent" },
        { value: "HALF_DAY", label: "Half Day" },
        { value: "MISSED_CHECK_OUT", label: "Missed Check-Out" },
        { value: "ON_LEAVE", label: "On Leave" },
      ],
    },
    {
      logicalName: "subStatus",
      displayName: "Sub Status",
      dataType: "optionset",
      isSubStatus: true,
      options: [
        { value: "IN_PROGRESS", label: "Session In Progress" },
        { value: "COMPLETED", label: "Session Completed" },
        { value: "LATE_CHECK_IN", label: "Late Check-In" },
        { value: "LATE_CHECK_OUT", label: "Late Check-Out" },
        { value: "MISSING_CHECK_OUT", label: "Check-Out Missing" },
        { value: "APPROVED_LEAVE", label: "Approved Leave" },
        { value: "NO_ATTENDANCE", label: "No Attendance" },
        { value: "PARTIAL_DAY", label: "Partial Day" },
        { value: "STANDARD", label: "Standard" },
      ],
    },
  ],
  formFields: [
    "attendanceDate",
    "attendanceMode",
    "workSite",
    "shift",
    "checkIn",
    "checkOut",
    "duration",
    "checkInLocation",
    "checkOutLocation",
  ],
  formSections: [
    {
      id: "attendance.session",
      tabKey: "general",
      label: "Session",
      order: 10,
      layout: "single-column",
      columns: 1,
      column: 1,
      fields: [
        { fieldLogicalName: "attendanceDate", order: 10 },
        { fieldLogicalName: "attendanceMode", order: 20 },
        {
          fieldLogicalName: "workSite",
          order: 30,
          visibilityRuleKey: "attendance.hideWorkSiteOnRemote",
        },
        { fieldLogicalName: "shift", order: 40 },
      ],
    },
    {
      id: "attendance.time",
      tabKey: "general",
      label: "Time",
      order: 20,
      layout: "single-column",
      columns: 1,
      column: 2,
      fields: [
        { fieldLogicalName: "checkIn", order: 10 },
        { fieldLogicalName: "checkOut", order: 20 },
        { fieldLogicalName: "duration", order: 30 },
      ],
    },
    {
      id: "attendance.location",
      tabKey: "general",
      label: "Location Capture",
      order: 30,
      layout: "two-column",
      columns: 2,
      columnSpan: 2,
      fields: [
        { fieldLogicalName: "checkInLocation", order: 10 },
        { fieldLogicalName: "checkOutLocation", order: 20 },
      ],
    },
  ],
  views: [
    {
      logicalName: "attendance.my",
      viewId: "00000000-0000-4000-8000-000000000201",
      displayName: "My Attendance",
      columns: [
        "entryName",
        "attendanceDate",
        "attendanceMode",
        "shift",
        "checkIn",
        "checkOut",
        "duration",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.today",
      viewId: "00000000-0000-4000-8000-000000000202",
      displayName: "Today's Attendance",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.team",
      viewId: "00000000-0000-4000-8000-000000000203",
      displayName: "Team Attendance",
      columns: [
        "entryName",
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "checkIn",
        "checkOut",
        "duration",
        "status",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.all",
      viewId: "00000000-0000-4000-8000-000000000204",
      displayName: "All Attendance",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.missingCheckout",
      viewId: "00000000-0000-4000-8000-000000000205",
      displayName: "Missing Check Out",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      filters: [
        {
          fieldLogicalName: "status",
          operator: "eq",
          value: "MISSED_CHECK_OUT",
        },
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
  ],
  commands: [
    attendanceCommand(
      "attendance.checkIn",
      "Check In",
      [PERMISSION_KEYS.ATTENDANCE_CHECKIN, "attendance.create"],
      10,
      "not-checked-in",
      ["not-checked-in", "blocked", "completed"],
    ),
    attendanceCommand(
      "attendance.checkOut",
      "Check Out",
      [PERMISSION_KEYS.ATTENDANCE_CHECKOUT, "attendance.create"],
      20,
      "checked-in",
      ["checked-in", "blocked", "completed"],
    ),
    attendanceCorrectionCommand(),
  ],
  widgets: [
    // Attendance evidence (correction proof, timesheets, travel records) uses
    // the same generic documents widget as every other module.
    {
      id: "system.documents",
      widgetType: "documents",
      label: "Documents",
      tabKey: "documents",
      order: 40,
      columnSpan: 1,
    },
  ],
};

export const timesheetRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "timesheets",
  apiPath: "/api/timesheets",
  entityLogicalName: "timesheet",
  collectionName: "timesheets",
  label: "Timesheets",
  singularLabel: "Timesheet",
  routeBase: "/timesheets",
  capabilities: ["timeline", "approvalTracking"],
  adapterCapabilities: {
    disableSave: true,
    export: false,
    exportTemplate: false,
    import: false,
  },
  timelineApiPath: "/api/timesheets/{recordId}/timeline",
  primaryNameField: "timesheetName",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.TIMESHEETS_READ,
    create: PERMISSION_KEYS.TIMESHEETS_WRITE,
    update: PERMISSION_KEYS.TIMESHEETS_WRITE,
    import: PERMISSION_KEYS.TIMESHEETS_IMPORT,
    export: PERMISSION_KEYS.TIMESHEETS_EXPORT,
  },
  fields: [
    {
      logicalName: "timesheetName",
      displayName: "Timesheet",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    { logicalName: "period", displayName: "Period" },
    {
      logicalName: "submittedAt",
      displayName: "Submitted At",
      dataType: "datetime",
    },
    { logicalName: "totalHours", displayName: "Hours", dataType: "decimal" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "timesheets.my",
      viewId: "00000000-0000-4000-8000-000000000301",
      displayName: "My Timesheets",
      columns: ["timesheetName", "period", "totalHours", "status"],
      isDefault: true,
    },
    {
      logicalName: "timesheets.all",
      viewId: "00000000-0000-4000-8000-000000000302",
      displayName: "All Timesheets",
      columns: [
        "timesheetName",
        "employeeName",
        "period",
        "submittedAt",
        "totalHours",
        "status",
      ],
    },
  ],
  commands: [
    disabledBusinessCommand("timesheet.submit", "Submit"),
    disabledBusinessCommand("timesheet.approve", "Approve"),
    disabledBusinessCommand("timesheet.reject", "Reject"),
  ],
};

export const recruitmentApplicationRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "recruitmentApplications",
  metadataTableKey: "applications",
  apiPath: "/api/applications",
  entityLogicalName: "recruitmentApplication",
  collectionName: "applications",
  label: "Recruitment Applications",
  singularLabel: "Application",
  routeBase: "/recruitment/applications",
  primaryNameField: "applicationName",
  statusField: "stage",
  adapterCapabilities: {
    disableCreate: true,
    disableEdit: true,
    disableSave: true,
    import: false,
    export: false,
    exportTemplate: false,
  },
  permissions: {
    read: PERMISSION_KEYS.RECRUITMENT_READ,
    create: PERMISSION_KEYS.RECRUITMENT_CREATE,
    update: PERMISSION_KEYS.RECRUITMENT_UPDATE,
  },
  fields: [
    {
      logicalName: "applicationName",
      displayName: "Application",
      isPrimaryName: true,
    },
    { logicalName: "candidateName", displayName: "Candidate" },
    { logicalName: "candidateEmail", displayName: "Candidate Email" },
    { logicalName: "jobTitle", displayName: "Job Opening" },
    { logicalName: "jobCode", displayName: "Job Code" },
    {
      logicalName: "appliedAt",
      displayName: "Applied",
      dataType: "date",
    },
    {
      logicalName: "stage",
      displayName: "Stage",
      dataType: "optionset",
      options: RECRUITMENT_STAGE_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "matchScore",
      displayName: "Match Score",
      dataType: "number",
    },
    { logicalName: "currentCity", displayName: "Current City" },
    { logicalName: "preferredWorkMode", displayName: "Work Mode" },
  ],
  formFields: [
    "candidateName",
    "candidateEmail",
    "jobTitle",
    "jobCode",
    "appliedAt",
    "stage",
    "matchScore",
    "currentCity",
    "preferredWorkMode",
  ],
  views: [
    {
      logicalName: "recruitmentApplications.pipeline",
      viewId: "00000000-0000-4000-8000-000000000901",
      displayName: "Pipeline",
      columns: [
        "applicationName",
        "candidateName",
        "jobTitle",
        "stage",
        "matchScore",
        "appliedAt",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "appliedAt", direction: "desc" }],
    },
  ],
  commands: [
    disabledBusinessCommand(
      "recruitment.advance",
      "Advance",
      PERMISSION_KEYS.RECRUITMENT_ADVANCE,
      "Use the stage panel on this page to move an application.",
    ),
  ],
};

export const recruitmentCandidateRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "recruitmentCandidates",
  metadataTableKey: "candidates",
  apiPath: "/api/candidates",
  entityLogicalName: "candidate",
  collectionName: "candidates",
  label: "Candidates",
  singularLabel: "Candidate",
  createCommandLabel: "Add candidate",
  routeBase: "/recruitment/candidates",
  primaryNameField: "fullName",
  statusField: "currentStatus",
  permissions: {
    read: PERMISSION_KEYS.RECRUITMENT_READ,
    create: PERMISSION_KEYS.RECRUITMENT_CREATE,
    update: PERMISSION_KEYS.RECRUITMENT_UPDATE,
    delete: PERMISSION_KEYS.RECRUITMENT_UPDATE,
    export: PERMISSION_KEYS.RECRUITMENT_READ,
  },
  adapterCapabilities: { softDelete: true },
  lookupApiPaths: {
    nationalityCountryId: "/api/lookups/countries",
    currentCountryId: "/api/lookups/countries",
    currentStateProvinceId: "/api/lookups/states",
    currentCityId: "/api/lookups/cities",
  },
  fields: [
    {
      logicalName: "fullName",
      displayName: "Candidate",
      isPrimaryName: true,
      isReadOnly: true,
    },
    {
      logicalName: "firstName",
      displayName: "First Name",
      requirementLevel: "required",
    },
    { logicalName: "middleName", displayName: "Middle Name" },
    {
      logicalName: "lastName",
      displayName: "Last Name",
      requirementLevel: "required",
    },
    {
      logicalName: "email",
      displayName: "Primary Email",
      dataType: "email",
      requirementLevel: "required",
    },
    {
      logicalName: "personalEmail",
      displayName: "Personal Email",
      dataType: "email",
    },
    {
      logicalName: "phone",
      displayName: "Phone",
      dataType: "phone",
      requirementLevel: "required",
    },
    {
      logicalName: "alternatePhone",
      displayName: "Alternate Phone",
      dataType: "phone",
    },
    {
      logicalName: "source",
      displayName: "Source",
      dataType: "optionset",
      options: [
        { value: "LinkedIn", label: "LinkedIn" },
        { value: "WhatsApp", label: "WhatsApp" },
        { value: "Referral / Contact", label: "Referral / Contact" },
        { value: "Email", label: "Email" },
        { value: "Careers Page", label: "Careers Page" },
        { value: "Recruitment Agency", label: "Recruitment Agency" },
        { value: "Walk-in", label: "Walk-in" },
        { value: "Other", label: "Other" },
      ],
    },
    {
      logicalName: "currentStatus",
      displayName: "Current Stage",
      dataType: "optionset",
      requirementLevel: "required",
      options: RECRUITMENT_STAGE_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "applicationCount",
      displayName: "Applications",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "lastApplicationAt",
      displayName: "Last Application",
      dataType: "date",
      isReadOnly: true,
    },
    {
      logicalName: "gender",
      displayName: "Gender",
      dataType: "optionset",
      options: [
        { value: "MALE", label: "Male" },
        { value: "FEMALE", label: "Female" },
        { value: "OTHER", label: "Other" },
      ],
    },
    {
      logicalName: "dateOfBirth",
      displayName: "Date of Birth",
      dataType: "date",
    },
    {
      logicalName: "nationalityCountryId",
      displayName: "Nationality",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "country",
    },
    {
      logicalName: "currentCountryId",
      displayName: "Country",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "country",
      resetOnParentChange: true,
    },
    {
      logicalName: "currentStateProvinceId",
      displayName: "State / Province",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "stateProvince",
      dependsOnFieldId: "currentCountryId",
      dependencyFilterKey: "countryId",
      resetOnParentChange: true,
    },
    {
      logicalName: "currentCityId",
      displayName: "City",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "city",
      dependsOnFieldId: "currentStateProvinceId",
      dependencyFilterKey: "stateProvinceId",
    },
    {
      logicalName: "currentCountry",
      displayName: "Country",
      isReadOnly: true,
    },
    {
      logicalName: "currentStateProvince",
      displayName: "State / Province",
      isReadOnly: true,
    },
    {
      logicalName: "currentCity",
      displayName: "City",
      isReadOnly: true,
    },
    { logicalName: "addressArea", displayName: "Area / Address" },
    {
      logicalName: "noticePeriodDays",
      displayName: "Notice Period Days",
      dataType: "number",
      min: 0,
      max: 365,
    },
    {
      logicalName: "earliestJoiningDate",
      displayName: "Earliest Joining Date",
      dataType: "date",
    },
    {
      logicalName: "preferredWorkMode",
      displayName: "Preferred Work Mode",
      dataType: "optionset",
      options: [
        { value: "OFFICE", label: "Office" },
        { value: "REMOTE", label: "Remote" },
        { value: "HYBRID", label: "Hybrid" },
      ],
    },
    { logicalName: "preferredLocation", displayName: "Preferred Location" },
    {
      logicalName: "willingToRelocate",
      displayName: "Willing to Relocate",
      dataType: "boolean",
    },
    { logicalName: "currentEmployer", displayName: "Current Employer" },
    { logicalName: "currentDesignation", displayName: "Current Designation" },
    {
      logicalName: "totalYearsExperience",
      displayName: "Total Experience",
      dataType: "decimal",
      min: 0,
      max: 80,
    },
    {
      logicalName: "relevantYearsExperience",
      displayName: "Relevant Experience",
      dataType: "decimal",
      min: 0,
      max: 80,
    },
    {
      logicalName: "currentSalary",
      displayName: "Current Salary",
      dataType: "currency",
      min: 0,
    },
    {
      logicalName: "expectedSalary",
      displayName: "Expected Salary",
      dataType: "currency",
      min: 0,
    },
    {
      logicalName: "profileSummary",
      displayName: "Profile Summary",
      dataType: "multiline-string",
    },
    {
      logicalName: "reasonForLeavingCurrentEmployer",
      displayName: "Reason for Leaving",
      dataType: "multiline-string",
    },
    {
      logicalName: "linkedInUrl",
      displayName: "LinkedIn URL",
      dataType: "url",
    },
    {
      logicalName: "portfolioUrl",
      displayName: "Portfolio URL",
      dataType: "url",
    },
    {
      logicalName: "otherProfileUrl",
      displayName: "Other Profile URL",
      dataType: "url",
    },
    { logicalName: "resumeDocumentReference", displayName: "Resume Reference" },
    {
      logicalName: "skills",
      displayName: "Skills",
      dataType: "multiline-string",
    },
    {
      logicalName: "certifications",
      displayName: "Certifications",
      dataType: "multiline-string",
    },
    {
      logicalName: "interests",
      displayName: "Interests",
      dataType: "multiline-string",
    },
    {
      logicalName: "hobbies",
      displayName: "Hobbies",
      dataType: "multiline-string",
    },
    {
      logicalName: "strengths",
      displayName: "Strengths",
      dataType: "multiline-string",
    },
    {
      logicalName: "concerns",
      displayName: "Concerns / Risks",
      dataType: "multiline-string",
    },
    {
      logicalName: "recruiterNotes",
      displayName: "Recruiter Notes",
      dataType: "multiline-string",
    },
    {
      logicalName: "hrNotes",
      displayName: "HR Notes",
      dataType: "multiline-string",
    },
  ],
  formSections: [
    {
      id: "candidate.identity",
      tabKey: "summary",
      label: "Identity & Contact",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "firstName", order: 10 },
        { fieldLogicalName: "middleName", order: 20 },
        { fieldLogicalName: "lastName", order: 30 },
        { fieldLogicalName: "source", order: 40 },
        { fieldLogicalName: "email", order: 50 },
        { fieldLogicalName: "personalEmail", order: 60 },
        { fieldLogicalName: "phone", order: 70 },
        { fieldLogicalName: "alternatePhone", order: 80 },
        { fieldLogicalName: "currentStatus", order: 90 },
        { fieldLogicalName: "gender", order: 100 },
        { fieldLogicalName: "dateOfBirth", order: 110 },
        { fieldLogicalName: "nationalityCountryId", order: 120 },
      ],
    },
    {
      id: "candidate.location",
      tabKey: "summary",
      label: "Location & Availability",
      order: 20,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "currentCountryId", order: 10 },
        { fieldLogicalName: "currentStateProvinceId", order: 20 },
        { fieldLogicalName: "currentCityId", order: 30 },
        { fieldLogicalName: "currentCountry", order: 40 },
        { fieldLogicalName: "currentStateProvince", order: 50 },
        { fieldLogicalName: "currentCity", order: 60 },
        { fieldLogicalName: "addressArea", order: 70 },
        { fieldLogicalName: "noticePeriodDays", order: 80 },
        { fieldLogicalName: "earliestJoiningDate", order: 90 },
        { fieldLogicalName: "preferredWorkMode", order: 100 },
        { fieldLogicalName: "preferredLocation", order: 110 },
        { fieldLogicalName: "willingToRelocate", order: 120, columnSpan: 2 },
      ],
    },
    {
      id: "candidate.professional",
      tabKey: "professional",
      label: "Professional Summary",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "currentEmployer", order: 10 },
        { fieldLogicalName: "currentDesignation", order: 20 },
        { fieldLogicalName: "totalYearsExperience", order: 30 },
        { fieldLogicalName: "relevantYearsExperience", order: 40 },
        { fieldLogicalName: "currentSalary", order: 50 },
        { fieldLogicalName: "expectedSalary", order: 60 },
        { fieldLogicalName: "profileSummary", order: 70, columnSpan: 2 },
        {
          fieldLogicalName: "reasonForLeavingCurrentEmployer",
          order: 80,
          columnSpan: 2,
        },
        { fieldLogicalName: "linkedInUrl", order: 90 },
        { fieldLogicalName: "portfolioUrl", order: 100 },
        { fieldLogicalName: "otherProfileUrl", order: 110 },
        { fieldLogicalName: "resumeDocumentReference", order: 120 },
      ],
    },
    {
      id: "candidate.skills",
      tabKey: "professional",
      label: "Skills & Notes",
      order: 20,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "skills", order: 10, columnSpan: 2 },
        { fieldLogicalName: "certifications", order: 20, columnSpan: 2 },
        { fieldLogicalName: "interests", order: 30 },
        { fieldLogicalName: "hobbies", order: 40 },
        { fieldLogicalName: "strengths", order: 50 },
        { fieldLogicalName: "concerns", order: 60 },
        { fieldLogicalName: "recruiterNotes", order: 70 },
        { fieldLogicalName: "hrNotes", order: 80 },
      ],
    },
  ],
  widgets: [
    {
      id: "candidate.applications",
      label: "Applications",
      widgetType: "candidate_applications",
      tabKey: "applications",
      order: 10,
      columnSpan: 3,
    },
    {
      id: "candidate.documents",
      label: "Documents",
      widgetType: "candidate_documents",
      tabKey: "documents",
      order: 20,
      columnSpan: 3,
    },
    {
      id: "candidate.parsing",
      label: "Parsing",
      widgetType: "candidate_parsing",
      tabKey: "parsing",
      order: 30,
      columnSpan: 3,
    },
  ],
  views: [
    {
      logicalName: "recruitmentCandidates.all",
      viewId: "00000000-0000-4000-8000-000000000903",
      displayName: "All Candidates",
      columns: [
        "fullName",
        "source",
        "currentStatus",
        "applicationCount",
        "currentCity",
        "currentCountry",
        "email",
        "phone",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "fullName", direction: "asc" }],
    },
  ],
  commands: [
    {
      key: "system.back",
      label: "Back",
      description: "Return to the previous recruitment page.",
      scope: "module",
      placement: "list-command-bar",
      executionMode: "navigation",
      handlerKey: "system.back",
      order: 5,
    },
  ],
};

export const recruitmentTalentPoolRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "recruitmentTalentPool",
  metadataTableKey: "candidates",
  apiPath: "/api/candidates",
  entityLogicalName: "candidate",
  collectionName: "candidates",
  label: "Talent Pool",
  singularLabel: "Candidate",
  createCommandLabel: "Add candidate",
  routeBase: "/recruitment/candidates",
  primaryNameField: "fullName",
  statusField: "currentStatus",
  permissions: {
    read: PERMISSION_KEYS.RECRUITMENT_READ,
    create: PERMISSION_KEYS.RECRUITMENT_CREATE,
    update: PERMISSION_KEYS.RECRUITMENT_UPDATE,
    delete: PERMISSION_KEYS.RECRUITMENT_UPDATE,
    export: PERMISSION_KEYS.RECRUITMENT_READ,
  },
  adapterCapabilities: {
    softDelete: true,
  },
  fields: [
    { logicalName: "fullName", displayName: "Candidate", isPrimaryName: true },
    { logicalName: "email", displayName: "Email" },
    { logicalName: "phone", displayName: "Phone" },
    { logicalName: "source", displayName: "Source" },
    { logicalName: "currentCity", displayName: "City" },
    { logicalName: "currentCountry", displayName: "Country" },
    {
      logicalName: "currentStatus",
      displayName: "Status",
      dataType: "optionset",
      options: RECRUITMENT_STAGE_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "applicationCount",
      displayName: "Applications",
      dataType: "number",
    },
    {
      logicalName: "lastApplicationAt",
      displayName: "Last Application",
      dataType: "date",
    },
  ],
  views: [
    {
      logicalName: "recruitmentTalentPool.rejected",
      viewId: "00000000-0000-4000-8000-000000000902",
      displayName: "Talent Pool",
      columns: [
        "fullName",
        "source",
        "currentStatus",
        "applicationCount",
        "lastApplicationAt",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "fullName", direction: "asc" }],
    },
  ],
  commands: [
    {
      key: "system.back",
      label: "Back",
      description: "Return to the previous recruitment page.",
      scope: "module",
      placement: "list-command-bar",
      executionMode: "navigation",
      handlerKey: "system.back",
      order: 5,
    },
  ],
};

export const jobOpeningRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "recruitmentJobs",
  metadataTableKey: "jobOpenings",
  apiPath: "/api/job-openings",
  entityLogicalName: "jobOpening",
  collectionName: "jobOpenings",
  label: "Job Openings",
  singularLabel: "Job Opening",
  routeBase: "/recruitment/jobs",
  primaryNameField: "title",
  statusField: "status",
  adapterCapabilities: {
    import: false,
    export: false,
    exportTemplate: false,
  },
  permissions: {
    read: PERMISSION_KEYS.RECRUITMENT_READ,
    create: PERMISSION_KEYS.RECRUITMENT_CREATE,
    update: PERMISSION_KEYS.RECRUITMENT_UPDATE,
  },
  fields: [
    {
      logicalName: "title",
      displayName: "Job Title",
      isPrimaryName: true,
      requirementLevel: "required",
    },
    { logicalName: "code", displayName: "Code" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: JOB_OPENING_STATUS_OPTIONS,
      isStatus: true,
      requirementLevel: "required",
    },
    {
      logicalName: "pipelineId",
      displayName: "Recruitment Pipeline",
      dataType: "lookup",
      lookupTargetEntityLogicalName: "recruitmentPipeline",
      lookupTargetPrimaryNameField: "name",
    },
    {
      logicalName: "description",
      displayName: "Description",
      dataType: "multiline-string",
    },
    {
      logicalName: "requiredSkills",
      displayName: "Required Skills",
      dataType: "multiline-string",
    },
    {
      logicalName: "preferredSkills",
      displayName: "Preferred Skills",
      dataType: "multiline-string",
    },
    {
      logicalName: "minimumYearsExperience",
      displayName: "Minimum Experience (Years)",
      dataType: "decimal",
      min: 0,
    },
    {
      logicalName: "educationLevels",
      displayName: "Education Levels",
      dataType: "multi-optionset",
      options: JOB_OPENING_EDUCATION_LEVEL_OPTIONS,
    },
    {
      logicalName: "allowedWorkModes",
      displayName: "Allowed Work Modes",
      dataType: "multi-optionset",
      options: JOB_OPENING_WORK_MODE_OPTIONS,
    },
    {
      logicalName: "allowedLocations",
      displayName: "Allowed Locations",
      dataType: "multiline-string",
    },
    {
      logicalName: "noticePeriodDays",
      displayName: "Notice Period (Days)",
      dataType: "number",
      min: 0,
    },
    {
      logicalName: "skillMatchWeight",
      displayName: "Skill Fit Weight",
      dataType: "number",
      min: 0,
      max: 100,
    },
    {
      logicalName: "experienceFitWeight",
      displayName: "Experience Fit Weight",
      dataType: "number",
      min: 0,
      max: 100,
    },
    {
      logicalName: "educationFitWeight",
      displayName: "Education Fit Weight",
      dataType: "number",
      min: 0,
      max: 100,
    },
    {
      logicalName: "locationFitWeight",
      displayName: "Location Fit Weight",
      dataType: "number",
      min: 0,
      max: 100,
    },
    {
      logicalName: "availabilityFitWeight",
      displayName: "Availability Fit Weight",
      dataType: "number",
      min: 0,
      max: 100,
    },
    {
      logicalName: "requireAllMandatorySkills",
      displayName: "Require All Mandatory Skills",
      dataType: "boolean",
    },
    {
      logicalName: "rejectIfExperienceBelowMinimum",
      displayName: "Reject If Experience Is Below Minimum",
      dataType: "boolean",
    },
    {
      logicalName: "rejectIfWorkModeMismatch",
      displayName: "Reject If Work Mode Mismatches",
      dataType: "boolean",
    },
    {
      logicalName: "rejectIfLocationMismatch",
      displayName: "Reject If Location Mismatches",
      dataType: "boolean",
    },
    {
      logicalName: "applicationCount",
      displayName: "Applications",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "scoringStatus",
      displayName: "Scoring",
      isReadOnly: true,
    },
    {
      logicalName: "averageMatchScore",
      displayName: "Average Match",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "createdAt",
      displayName: "Created",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "updatedAt",
      displayName: "Updated",
      dataType: "datetime",
      isReadOnly: true,
    },
  ],
  formFields: [
    "title",
    "code",
    "status",
    "pipelineId",
    "description",
    "requiredSkills",
    "preferredSkills",
    "minimumYearsExperience",
    "educationLevels",
    "allowedWorkModes",
    "allowedLocations",
    "noticePeriodDays",
    "skillMatchWeight",
    "experienceFitWeight",
    "educationFitWeight",
    "locationFitWeight",
    "availabilityFitWeight",
    "requireAllMandatorySkills",
    "rejectIfExperienceBelowMinimum",
    "rejectIfWorkModeMismatch",
    "rejectIfLocationMismatch",
    "applicationCount",
    "scoringStatus",
    "averageMatchScore",
  ],
  formSections: [
    {
      id: "recruitmentJobs.main.basic",
      tabKey: "general",
      label: "Basic Information",
      order: 10,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "title", order: 10, requirementLevel: "required" },
        { fieldLogicalName: "code", order: 20 },
        {
          fieldLogicalName: "status",
          order: 30,
          requirementLevel: "required",
        },
        { fieldLogicalName: "pipelineId", order: 40 },
        { fieldLogicalName: "description", order: 50, columnSpan: 2 },
      ],
    },
    {
      id: "recruitmentJobs.main.criteria",
      tabKey: "scoring",
      label: "Hiring Criteria",
      order: 20,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "requiredSkills", order: 10 },
        { fieldLogicalName: "preferredSkills", order: 20 },
        { fieldLogicalName: "minimumYearsExperience", order: 30 },
        { fieldLogicalName: "noticePeriodDays", order: 40 },
        { fieldLogicalName: "educationLevels", order: 50, columnSpan: 2 },
        { fieldLogicalName: "allowedWorkModes", order: 60, columnSpan: 2 },
        { fieldLogicalName: "allowedLocations", order: 70, columnSpan: 2 },
      ],
    },
    {
      id: "recruitmentJobs.main.weights",
      tabKey: "scoring",
      label: "Scoring Weights",
      order: 30,
      layout: "three-column",
      columns: 3,
      fields: [
        { fieldLogicalName: "skillMatchWeight", order: 10 },
        { fieldLogicalName: "experienceFitWeight", order: 20 },
        { fieldLogicalName: "educationFitWeight", order: 30 },
        { fieldLogicalName: "locationFitWeight", order: 40 },
        { fieldLogicalName: "availabilityFitWeight", order: 50 },
      ],
    },
    {
      id: "recruitmentJobs.main.knockout",
      tabKey: "scoring",
      label: "Knockout Rules",
      order: 40,
      layout: "two-column",
      columns: 2,
      fields: [
        { fieldLogicalName: "requireAllMandatorySkills", order: 10 },
        { fieldLogicalName: "rejectIfExperienceBelowMinimum", order: 20 },
        { fieldLogicalName: "rejectIfWorkModeMismatch", order: 30 },
        { fieldLogicalName: "rejectIfLocationMismatch", order: 40 },
      ],
    },
  ],
  lookupApiPaths: {
    pipelineId: "/api/recruitment/pipelines",
  },
  views: [
    {
      logicalName: "jobOpenings.active",
      viewId: "00000000-0000-4000-8000-000000000911",
      displayName: "Active Openings",
      columns: [
        "title",
        "code",
        "status",
        "applicationCount",
        "scoringStatus",
        "averageMatchScore",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "updatedAt", direction: "desc" }],
    },
  ],
  commands: [
    {
      key: "system.back",
      label: "Back",
      description: "Return to the recruitment workspace.",
      scope: "module",
      placement: "list-command-bar",
      executionMode: "navigation",
      handlerKey: "system.back",
      order: 5,
    },
  ],
};

export const onboardingRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "onboarding",
  metadataTableKey: "onboarding",
  apiPath: "/api/onboarding",
  entityLogicalName: "employeeOnboarding",
  collectionName: "employeeOnboardings",
  label: "Onboarding",
  singularLabel: "Onboarding",
  routeBase: "/onboarding",
  primaryNameField: "title",
  statusField: "status",
  adapterCapabilities: {
    disableCreate: true,
    disableSave: true,
    softDelete: true,
    import: false,
    export: false,
    exportTemplate: false,
  },
  permissions: {
    read: PERMISSION_KEYS.ONBOARDING_READ,
    create: PERMISSION_KEYS.ONBOARDING_CREATE,
    update: PERMISSION_KEYS.ONBOARDING_UPDATE,
    delete: PERMISSION_KEYS.ONBOARDING_UPDATE,
  },
  fields: [
    { logicalName: "title", displayName: "Onboarding", isPrimaryName: true },
    { logicalName: "personName", displayName: "Person", isReadOnly: true },
    {
      logicalName: "candidateEmail",
      displayName: "Email",
      dataType: "email",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: ONBOARDING_STATUS_OPTIONS,
      isStatus: true,
    },
    { logicalName: "progressText", displayName: "Progress", isReadOnly: true },
    {
      logicalName: "progressPercent",
      displayName: "Progress %",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "blockerCount",
      displayName: "Blockers",
      dataType: "number",
      isReadOnly: true,
    },
    {
      logicalName: "draftProfileStatus",
      displayName: "Draft Profile",
      isReadOnly: true,
    },
    {
      logicalName: "templateName",
      displayName: "Template",
      isReadOnly: true,
    },
    { logicalName: "dueDate", displayName: "Due", dataType: "date" },
    {
      logicalName: "plannedJoiningDate",
      displayName: "Planned Joining",
      dataType: "date",
    },
    {
      logicalName: "createdAt",
      displayName: "Created",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "updatedAt",
      displayName: "Updated",
      dataType: "datetime",
      isReadOnly: true,
    },
  ],
  formFields: [
    "title",
    "personName",
    "candidateEmail",
    "status",
    "progressText",
    "blockerCount",
    "draftProfileStatus",
    "templateName",
    "dueDate",
    "plannedJoiningDate",
  ],
  views: [
    {
      logicalName: "onboarding.active",
      viewId: "00000000-0000-4000-8000-000000000950",
      displayName: "Active Onboarding",
      columns: [
        "title",
        "personName",
        "status",
        "progressText",
        "dueDate",
        "draftProfileStatus",
      ],
      isDefault: true,
      filters: [
        {
          fieldLogicalName: "status",
          operator: "in",
          value: [
            "DRAFT",
            "NOT_STARTED",
            "IN_PROGRESS",
            "AWAITING_CANDIDATE_INPUT",
            "READY_FOR_CONVERSION",
            "BLOCKED",
          ],
        },
      ],
      defaultSort: [{ fieldLogicalName: "dueDate", direction: "asc" }],
    },
    {
      logicalName: "onboarding.all",
      viewId: "00000000-0000-4000-8000-000000000951",
      displayName: "All Onboarding",
      columns: [
        "title",
        "personName",
        "status",
        "progressText",
        "blockerCount",
        "dueDate",
        "plannedJoiningDate",
      ],
      defaultSort: [{ fieldLogicalName: "createdAt", direction: "desc" }],
    },
  ],
  commands: [
    {
      key: "system.back",
      label: "Back",
      description: "Return to the workspace overview.",
      scope: "module",
      placement: "list-command-bar",
      executionMode: "navigation",
      handlerKey: "system.back",
      order: 5,
    },
  ],
};

function disabledBusinessCommand(
  key: string,
  label: string,
  permissionKey?: string,
  disabledReason = `${label} is not wired to a generic ModuleDataAdapter handler yet.`,
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} is a business command and requires an adapter handler before it can execute from the generic runtime.`,
    scope: "record",
    placement: "detail-command-bar",
    executionMode: "client",
    handlerKey: key,
    permission: permissionKey
      ? { permissionKey, operation: "execute", scope: "tenant" }
      : undefined,
    isDisabled: true,
    disabledReason,
    order: 500,
  };
}

function leaveDecisionCommand(
  key: "leave.approve" | "leave.reject",
  label: string,
  permissionKey: string,
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} this Leave Request through the generic command runtime.`,
    scope: "record",
    placement: "detail-command-bar",
    executionMode: "client",
    handlerKey: key,
    permission: { permissionKey, operation: "execute", scope: "tenant" },
    visibilityRules: [
      {
        operator: "field-equals",
        fieldLogicalName: "status",
        expectedValue: "PENDING",
      },
    ],
    order: 500,
  };
}

function attendanceCommand(
  key: "attendance.checkIn" | "attendance.checkOut",
  label: string,
  permissionKeys: readonly string[],
  order: number,
  expectedState: "not-checked-in" | "checked-in",
  visibleStates: readonly string[],
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} through the shared Attendance command handler.`,
    scope: "module",
    placement: "list-command-bar",
    executionMode: "client",
    handlerKey: key,
    payloadSchemaKey: key,
    permission: {
      permissionKey: permissionKeys[0] ?? "",
      anyPermissionKeys: permissionKeys,
      operation: "execute",
      scope: "self",
    },
    visibilityRules: [
      {
        operator: "field-in",
        fieldLogicalName: "attendanceActionState",
        expectedValues: visibleStates,
      },
    ],
    dynamicDisabled: {
      fieldLogicalName: "attendanceActionState",
      enabledValue: expectedState,
      reasonFieldLogicalName: "attendanceBlockedReason",
      fallbackReason:
        key === "attendance.checkIn"
          ? "Check in is not available for the current attendance state."
          : "Check out is not available for the current attendance state.",
    },
    order,
  };
}

function attendanceCorrectionCommand(): CommandDefinition {
  return {
    key: "attendance.correction",
    label: "Correction Request",
    description: "Submit an attendance correction request for manager review.",
    scope: "module",
    placement: "list-command-bar",
    executionMode: "client",
    handlerKey: "attendance.correction",
    permission: {
      permissionKey: PERMISSION_KEYS.ATTENDANCE_READ,
      operation: "execute",
      scope: "self",
    },
    order: 30,
  };
}

export const approvalRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "approvals",
  apiPath: "/api/approvals",
  entityLogicalName: "approval",
  collectionName: "approvals",
  label: "Approvals",
  singularLabel: "Approval",
  routeBase: "/approvals",
  primaryNameField: "approvalName",
  statusField: "status",
  // An approval is raised by the module whose record needs approving — leave,
  // timesheets, claims — and can never be created here. Without this the standard
  // command set still emitted `system.new`, whose handler resolves to
  // `/approvals/new`; no page exists at that route, so it fell through to
  // `approvals/[approvalId]` with the literal id "new" and threw.
  adapterCapabilities: { disableCreate: true },
  permissions: {
    read: PERMISSION_KEYS.APPROVALS_READ,
  },
  fields: [
    {
      logicalName: "approvalName",
      displayName: "Approval",
      isPrimaryName: true,
    },
    { logicalName: "moduleLabel", displayName: "Module" },
    { logicalName: "requesterName", displayName: "Requester" },
    { logicalName: "assignedToName", displayName: "Assigned To" },
    {
      logicalName: "submittedAt",
      displayName: "Submitted At",
      dataType: "datetime",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "approvals.assigned",
      viewId: "00000000-0000-4000-8000-000000000401",
      displayName: "Assigned Approvals",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "submittedAt",
        "status",
      ],
      isDefault: true,
    },
    {
      logicalName: "approvals.all",
      viewId: "00000000-0000-4000-8000-000000000402",
      displayName: "All Approvals",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "assignedToName",
        "submittedAt",
        "status",
      ],
    },
    /*
     * "Assigned" and "All" both mix decided requests in with live ones, so the
     * queue never visibly shrinks. These separate what still needs a decision
     * from what has already had one.
     */
    {
      logicalName: "approvals.pending",
      viewId: "00000000-0000-4000-8000-000000000403",
      displayName: "Pending Decision",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "assignedToName",
        "submittedAt",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "PENDING" },
      ],
      /* Oldest submission first — the queue reads as a queue. */
      defaultSort: [{ fieldLogicalName: "submittedAt", direction: "asc" }],
    },
    {
      logicalName: "approvals.approved",
      viewId: "00000000-0000-4000-8000-000000000404",
      displayName: "Approved",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "assignedToName",
        "submittedAt",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "APPROVED" },
      ],
      defaultSort: [{ fieldLogicalName: "submittedAt", direction: "desc" }],
    },
    {
      logicalName: "approvals.rejected",
      viewId: "00000000-0000-4000-8000-000000000405",
      displayName: "Rejected",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "assignedToName",
        "submittedAt",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "REJECTED" },
      ],
      defaultSort: [{ fieldLogicalName: "submittedAt", direction: "desc" }],
    },
  ],
  commands: [
    disabledBusinessCommand("approval.approve", "Approve"),
    disabledBusinessCommand("approval.reject", "Reject"),
  ],
};
