import { PERMISSION_KEYS } from "@/lib/security-keys";
import type { CommandDefinition } from "../command-runtime.types";
import type { StandardModuleRuntimeSpec } from "./standard-module-runtime";

const ACTIVE_STATUS_OPTIONS = [
  { value: "ACTIVE", label: "Active" },
  { value: "INACTIVE", label: "Inactive" },
] as const;

const APPROVAL_STATUS_OPTIONS = [
  { value: "PENDING", label: "Pending" },
  { value: "APPROVED", label: "Approved" },
  { value: "REJECTED", label: "Rejected" },
  { value: "CANCELLED", label: "Cancelled" },
] as const;

export const customerRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "customers",
  apiPath: "/api/customers",
  entityLogicalName: "customer",
  collectionName: "customers",
  label: "Customers",
  singularLabel: "Customer",
  routeBase: "/customers",
  primaryNameField: "name",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.CUSTOMERS_READ,
    create: PERMISSION_KEYS.CUSTOMERS_CREATE,
    update: PERMISSION_KEYS.CUSTOMERS_WRITE,
    delete: PERMISSION_KEYS.CUSTOMERS_DELETE,
    assign: PERMISSION_KEYS.CUSTOMERS_ASSIGN,
    share: PERMISSION_KEYS.CUSTOMERS_SHARE,
  },
  fields: [
    { logicalName: "name", displayName: "Customer", isPrimaryName: true },
    { logicalName: "code", displayName: "Code" },
    { logicalName: "industry", displayName: "Industry" },
    { logicalName: "contactName", displayName: "Primary Contact" },
    {
      logicalName: "contactEmail",
      displayName: "Contact Email",
      dataType: "email",
    },
    {
      logicalName: "contactPhone",
      displayName: "Contact Phone",
      dataType: "phone",
    },
    {
      logicalName: "billingEmail",
      displayName: "Billing Email",
      dataType: "email",
    },
    { logicalName: "websiteUrl", displayName: "Website", dataType: "url" },
    {
      logicalName: "address",
      displayName: "Address",
      dataType: "multiline-string",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: ACTIVE_STATUS_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "projectCount",
      displayName: "Projects",
      dataType: "number",
    },
  ],
  formFields: [
    "name",
    "code",
    "industry",
    "status",
    "contactName",
    "contactEmail",
    "contactPhone",
    "billingEmail",
    "websiteUrl",
    "address",
  ],
  views: [
    {
      logicalName: "customers.all",
      viewId: "00000000-0000-4000-8000-000000000601",
      displayName: "All Customers",
      columns: [
        "name",
        "code",
        "industry",
        "contactName",
        "projectCount",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
    {
      logicalName: "customers.active",
      viewId: "00000000-0000-4000-8000-000000000602",
      displayName: "Active Customers",
      columns: [
        "name",
        "code",
        "industry",
        "contactName",
        "projectCount",
        "status",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "ACTIVE" },
      ],
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
  ],
  commands: [
    disabledBusinessCommand("customer.activate", "Activate"),
    disabledBusinessCommand("customer.deactivate", "Deactivate"),
    disabledBusinessCommand("customer.convert", "Convert"),
  ],
};

export const projectRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "projects",
  apiPath: "/api/projects",
  entityLogicalName: "project",
  collectionName: "projects",
  label: "Projects",
  singularLabel: "Project",
  routeBase: "/projects",
  capabilities: ["timeline"],
  timelineApiPath: "/api/projects/{recordId}/timeline",
  primaryNameField: "name",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.PROJECTS_READ,
    create: PERMISSION_KEYS.PROJECTS_CREATE,
    update: PERMISSION_KEYS.PROJECTS_UPDATE,
    assign: PERMISSION_KEYS.PROJECTS_ASSIGN,
  },
  fields: [
    { logicalName: "name", displayName: "Project", isPrimaryName: true },
    { logicalName: "code", displayName: "Code" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: [
        { value: "PLANNING", label: "Planning" },
        { value: "ACTIVE", label: "Active" },
        { value: "COMPLETED", label: "Completed" },
        { value: "ON_HOLD", label: "On Hold" },
      ],
      isStatus: true,
    },
    { logicalName: "customerName", displayName: "Customer" },
    { logicalName: "startDate", displayName: "Start Date", dataType: "date" },
    { logicalName: "endDate", displayName: "End Date", dataType: "date" },
    {
      logicalName: "assignedEmployeesCount",
      displayName: "Assigned Employees",
      dataType: "number",
    },
  ],
  views: [
    {
      logicalName: "projects.all",
      viewId: "00000000-0000-4000-8000-000000000501",
      displayName: "All Projects",
      columns: [
        "name",
        "code",
        "status",
        "customerName",
        "startDate",
        "endDate",
        "assignedEmployeesCount",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "name", direction: "asc" }],
    },
    {
      logicalName: "projects.active",
      viewId: "00000000-0000-4000-8000-000000000502",
      displayName: "Active Projects",
      columns: [
        "name",
        "code",
        "status",
        "customerName",
        "startDate",
        "endDate",
        "assignedEmployeesCount",
      ],
      filters: [
        { fieldLogicalName: "status", operator: "eq", value: "ACTIVE" },
      ],
    },
  ],
  commands: [
    disabledBusinessCommand("project.close", "Close"),
    disabledBusinessCommand("project.reopen", "Reopen"),
  ],
};

export const leaveRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "leaves",
  metadataTableKey: "leaveRequests",
  apiPath: "/api/leave-requests",
  entityLogicalName: "leaveRequest",
  collectionName: "leaveRequests",
  label: "Leaves",
  singularLabel: "Leave Request",
  routeBase: "/leaves",
  capabilities: ["timeline", "approvalTracking"],
  timelineApiPath: "/api/leave-requests/{recordId}/timeline",
  primaryNameField: "requestName",
  ownerField: "ownerId",
  statusField: "status",
  subStatusField: "subStatus",
  permissions: {
    read: PERMISSION_KEYS.LEAVE_REQUESTS_READ,
    create: PERMISSION_KEYS.LEAVE_REQUESTS_CREATE,
  },
  fields: [
    {
      logicalName: "requestName",
      displayName: "Leave Request",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    {
      logicalName: "ownerId",
      displayName: "Owner",
      dataType: "lookup",
      isOwner: true,
    },
    {
      logicalName: "leaveTypeId",
      displayName: "Leave Type",
      dataType: "lookup",
    },
    { logicalName: "leaveTypeName", displayName: "Leave Type" },
    { logicalName: "startDate", displayName: "Start Date", dataType: "date" },
    { logicalName: "endDate", displayName: "End Date", dataType: "date" },
    { logicalName: "durationDays", displayName: "Days", dataType: "number" },
    {
      logicalName: "reason",
      displayName: "Reason",
      dataType: "multiline-string",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
    },
    {
      logicalName: "subStatus",
      displayName: "Sub Status",
      dataType: "optionset",
      isSubStatus: true,
    },
  ],
  formFields: ["leaveTypeId", "startDate", "endDate", "reason"],
  quickCreateFormFields: ["leaveTypeId", "startDate", "endDate", "reason"],
  views: [
    {
      logicalName: "leaves.my",
      viewId: "00000000-0000-4000-8000-000000000101",
      displayName: "My Leave Requests",
      columns: [
        "requestName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
    {
      logicalName: "leaves.all",
      viewId: "00000000-0000-4000-8000-000000000102",
      displayName: "Team / Assigned Leave",
      columns: [
        "requestName",
        "employeeName",
        "leaveTypeName",
        "startDate",
        "endDate",
        "durationDays",
        "status",
      ],
      defaultSort: [{ fieldLogicalName: "startDate", direction: "desc" }],
    },
  ],
  commands: [
    disabledBusinessCommand("leave.submit", "Submit"),
    disabledBusinessCommand("leave.cancel", "Cancel"),
    leaveDecisionCommand(
      "leave.approve",
      "Approve",
      PERMISSION_KEYS.LEAVE_REQUESTS_APPROVE,
    ),
    leaveDecisionCommand(
      "leave.reject",
      "Reject",
      PERMISSION_KEYS.LEAVE_REQUESTS_REJECT,
    ),
  ],
  widgets: [
    {
      id: "system.leaveApprovalTracker",
      widgetType: "approval_tracker",
      label: "Leave Approval Tracker",
      columnSpan: 3,
      dataSource: {
        apiPath: "/api/approvals",
        recordIdQueryKey: "entityId",
        query: {
          moduleKey: "leave",
          pageSize: "10",
        },
      },
    },
  ],
  widgetTabLabel: "Leave Tracker",
};

export const attendanceRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "attendance",
  metadataTableKey: "attendanceEntries",
  apiPath: "/api/attendance",
  createApiPath: "/api/attendance/manual",
  updateApiPath: "/api/attendance/{recordId}/override",
  entityLogicalName: "attendanceEntry",
  collectionName: "attendanceEntries",
  label: "Attendance",
  singularLabel: "Attendance Entry",
  routeBase: "/attendance",
  capabilities: ["timeline"],
  timelineApiPath: "/api/attendance/{recordId}/timeline",
  lookupApiPaths: {
    officeLocationId: "/api/attendance/locations",
    shiftTemplateId: "/api/attendance/shifts",
  },
  primaryNameField: "entryName",
  ownerField: "ownerId",
  statusField: "status",
  subStatusField: "subStatus",
  permissions: {
    read: PERMISSION_KEYS.ATTENDANCE_READ,
    create: PERMISSION_KEYS.ATTENDANCE_MANAGE,
    update: PERMISSION_KEYS.ATTENDANCE_UPDATE,
    import: PERMISSION_KEYS.ATTENDANCE_IMPORT,
    export: PERMISSION_KEYS.ATTENDANCE_EXPORT,
  },
  fields: [
    {
      logicalName: "entryName",
      displayName: "Attendance Entry",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    {
      logicalName: "ownerId",
      displayName: "Owner",
      dataType: "lookup",
      isOwner: true,
    },
    {
      logicalName: "attendanceDate",
      displayName: "Date",
      dataType: "date",
      isReadOnly: true,
    },
    {
      logicalName: "attendanceMode",
      displayName: "Work Mode",
      dataType: "optionset",
      options: [
        { value: "OFFICE", label: "Office" },
        { value: "REMOTE", label: "Remote" },
        { value: "HYBRID", label: "Hybrid" },
      ],
    },
    {
      logicalName: "workSite",
      displayName: "Work Site",
      dataType: "lookup",
      isReadOnly: true,
    },
    {
      logicalName: "officeLocationId",
      displayName: "Work Site",
      dataType: "lookup",
    },
    {
      logicalName: "shift",
      displayName: "Shift",
      dataType: "lookup",
      isReadOnly: true,
    },
    {
      logicalName: "shiftTemplateId",
      displayName: "Shift",
      dataType: "lookup",
    },
    {
      logicalName: "checkIn",
      displayName: "Check In",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "checkOut",
      displayName: "Check Out",
      dataType: "datetime",
      isReadOnly: true,
    },
    {
      logicalName: "duration",
      displayName: "Total Working Time",
      isReadOnly: true,
    },
    {
      logicalName: "checkInLocation",
      displayName: "Check-In Location",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "checkOutLocation",
      displayName: "Check-Out Location",
      dataType: "string",
      isReadOnly: true,
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      isStatus: true,
    },
    {
      logicalName: "subStatus",
      displayName: "Sub Status",
      dataType: "optionset",
      isSubStatus: true,
    },
  ],
  formFields: [
    "attendanceDate",
    "attendanceMode",
    "workSite",
    "shift",
    "checkIn",
    "checkOut",
    "duration",
    "checkInLocation",
    "checkOutLocation",
  ],
  formSections: [
    {
      id: "attendance.session",
      tabKey: "general",
      label: "Session",
      order: 10,
      layout: "single-column",
      columns: 1,
      column: 1,
      fields: [
        { fieldLogicalName: "attendanceDate", order: 10 },
        { fieldLogicalName: "attendanceMode", order: 20 },
        {
          fieldLogicalName: "workSite",
          order: 30,
          visibilityRuleKey: "attendance.hideWorkSiteOnRemote",
        },
        { fieldLogicalName: "shift", order: 40 },
      ],
    },
    {
      id: "attendance.time",
      tabKey: "general",
      label: "Time",
      order: 20,
      layout: "single-column",
      columns: 1,
      column: 2,
      fields: [
        { fieldLogicalName: "checkIn", order: 10 },
        { fieldLogicalName: "checkOut", order: 20 },
        { fieldLogicalName: "duration", order: 30 },
      ],
    },
    {
      id: "attendance.location",
      tabKey: "general",
      label: "Location Capture",
      order: 30,
      layout: "two-column",
      columns: 2,
      columnSpan: 2,
      fields: [
        { fieldLogicalName: "checkInLocation", order: 10 },
        { fieldLogicalName: "checkOutLocation", order: 20 },
      ],
    },
  ],
  views: [
    {
      logicalName: "attendance.my",
      viewId: "00000000-0000-4000-8000-000000000201",
      displayName: "My Attendance",
      columns: [
        "entryName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "checkIn",
        "checkOut",
        "duration",
        "status",
      ],
      isDefault: true,
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.today",
      viewId: "00000000-0000-4000-8000-000000000202",
      displayName: "Today's Attendance",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.team",
      viewId: "00000000-0000-4000-8000-000000000203",
      displayName: "Team Attendance",
      columns: [
        "entryName",
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "checkIn",
        "checkOut",
        "duration",
        "status",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.all",
      viewId: "00000000-0000-4000-8000-000000000204",
      displayName: "All Attendance",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
    {
      logicalName: "attendance.missingCheckout",
      viewId: "00000000-0000-4000-8000-000000000205",
      displayName: "Missing Check Out",
      columns: [
        "employeeName",
        "attendanceDate",
        "attendanceMode",
        "workSite",
        "shift",
        "status",
        "checkIn",
        "checkOut",
        "duration",
      ],
      filters: [
        {
          fieldLogicalName: "status",
          operator: "equals",
          value: "MISSED_CHECK_OUT",
        },
      ],
      defaultSort: [{ fieldLogicalName: "attendanceDate", direction: "desc" }],
    },
  ],
  commands: [
    attendanceCommand(
      "attendance.checkIn",
      "Check In",
      [PERMISSION_KEYS.ATTENDANCE_CHECKIN, "attendance.create"],
      10,
      "not-checked-in",
      ["not-checked-in", "blocked", "completed"],
    ),
    attendanceCommand(
      "attendance.checkOut",
      "Check Out",
      [PERMISSION_KEYS.ATTENDANCE_CHECKOUT, "attendance.create"],
      20,
      "checked-in",
      ["checked-in", "blocked", "completed"],
    ),
    disabledBusinessCommand("attendance.correction", "Correction Request"),
  ],
};

export const timesheetRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "timesheets",
  apiPath: "/api/timesheets",
  entityLogicalName: "timesheet",
  collectionName: "timesheets",
  label: "Timesheets",
  singularLabel: "Timesheet",
  routeBase: "/timesheets",
  capabilities: ["timeline", "approvalTracking"],
  timelineApiPath: "/api/timesheets/{recordId}/timeline",
  primaryNameField: "timesheetName",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.TIMESHEETS_READ,
    create: PERMISSION_KEYS.TIMESHEETS_CREATE,
    update: PERMISSION_KEYS.TIMESHEETS_WRITE,
    import: PERMISSION_KEYS.TIMESHEETS_IMPORT,
    export: PERMISSION_KEYS.TIMESHEETS_EXPORT,
  },
  fields: [
    {
      logicalName: "timesheetName",
      displayName: "Timesheet",
      isPrimaryName: true,
    },
    { logicalName: "employeeName", displayName: "Employee" },
    { logicalName: "period", displayName: "Period" },
    {
      logicalName: "submittedAt",
      displayName: "Submitted At",
      dataType: "datetime",
    },
    { logicalName: "totalHours", displayName: "Hours", dataType: "decimal" },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "timesheets.my",
      viewId: "00000000-0000-4000-8000-000000000301",
      displayName: "My Timesheets",
      columns: ["timesheetName", "period", "totalHours", "status"],
      isDefault: true,
    },
    {
      logicalName: "timesheets.all",
      viewId: "00000000-0000-4000-8000-000000000302",
      displayName: "All Timesheets",
      columns: [
        "timesheetName",
        "employeeName",
        "period",
        "submittedAt",
        "totalHours",
        "status",
      ],
    },
  ],
  commands: [
    disabledBusinessCommand("timesheet.submit", "Submit"),
    disabledBusinessCommand("timesheet.approve", "Approve"),
    disabledBusinessCommand("timesheet.reject", "Reject"),
  ],
  widgets: [
    {
      id: "system.timesheetApprovalTracker",
      widgetType: "approval_tracker",
      label: "Timesheet Approval Tracker",
      columnSpan: 3,
      dataSource: {
        apiPath: "/api/timesheets/team/{recordId}",
        responseAdapter: "approval-record",
      },
    },
  ],
};

function disabledBusinessCommand(
  key: string,
  label: string,
  permissionKey?: string,
  disabledReason = `${label} is not wired to a generic ModuleDataAdapter handler yet.`,
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} is a business command and requires an adapter handler before it can execute from the generic runtime.`,
    scope: "record",
    placement: "detail-command-bar",
    executionMode: "client",
    handlerKey: key,
    permission: permissionKey
      ? { permissionKey, operation: "execute", scope: "tenant" }
      : undefined,
    isDisabled: true,
    disabledReason,
    order: 500,
  };
}

function leaveDecisionCommand(
  key: "leave.approve" | "leave.reject",
  label: string,
  permissionKey: string,
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} this Leave Request through the generic command runtime.`,
    scope: "record",
    placement: "detail-command-bar",
    executionMode: "client",
    handlerKey: key,
    permission: { permissionKey, operation: "execute", scope: "tenant" },
    visibilityRules: [
      {
        operator: "field-equals",
        fieldLogicalName: "status",
        expectedValue: "PENDING",
      },
    ],
    order: 500,
  };
}

function attendanceCommand(
  key: "attendance.checkIn" | "attendance.checkOut",
  label: string,
  permissionKeys: readonly string[],
  order: number,
  expectedState: "not-checked-in" | "checked-in",
  visibleStates: readonly string[],
): CommandDefinition {
  return {
    key,
    label,
    description: `${label} through the shared Attendance command handler.`,
    scope: "module",
    placement: "list-command-bar",
    executionMode: "client",
    handlerKey: key,
    payloadSchemaKey: key,
    permission: {
      permissionKey: permissionKeys[0] ?? "",
      anyPermissionKeys: permissionKeys,
      operation: "execute",
      scope: "self",
    },
    visibilityRules: [
      {
        operator: "field-in",
        fieldLogicalName: "attendanceActionState",
        expectedValues: visibleStates,
      },
    ],
    dynamicDisabled: {
      fieldLogicalName: "attendanceActionState",
      enabledValue: expectedState,
      reasonFieldLogicalName: "attendanceBlockedReason",
      fallbackReason:
        key === "attendance.checkIn"
          ? "Check in is not available for the current attendance state."
          : "Check out is not available for the current attendance state.",
    },
    order,
  };
}

export const approvalRuntimeSpec: StandardModuleRuntimeSpec = {
  moduleKey: "approvals",
  apiPath: "/api/approvals",
  entityLogicalName: "approval",
  collectionName: "approvals",
  label: "Approvals",
  singularLabel: "Approval",
  routeBase: "/approvals",
  primaryNameField: "approvalName",
  statusField: "status",
  permissions: {
    read: PERMISSION_KEYS.APPROVALS_READ,
  },
  fields: [
    {
      logicalName: "approvalName",
      displayName: "Approval",
      isPrimaryName: true,
    },
    { logicalName: "moduleLabel", displayName: "Module" },
    { logicalName: "requesterName", displayName: "Requester" },
    { logicalName: "assignedToName", displayName: "Assigned To" },
    {
      logicalName: "submittedAt",
      displayName: "Submitted At",
      dataType: "datetime",
    },
    {
      logicalName: "status",
      displayName: "Status",
      dataType: "optionset",
      options: APPROVAL_STATUS_OPTIONS,
      isStatus: true,
    },
  ],
  views: [
    {
      logicalName: "approvals.assigned",
      viewId: "00000000-0000-4000-8000-000000000401",
      displayName: "Assigned Approvals",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "submittedAt",
        "status",
      ],
      isDefault: true,
    },
    {
      logicalName: "approvals.all",
      viewId: "00000000-0000-4000-8000-000000000402",
      displayName: "All Approvals",
      columns: [
        "approvalName",
        "moduleLabel",
        "requesterName",
        "assignedToName",
        "submittedAt",
        "status",
      ],
    },
  ],
  commands: [
    disabledBusinessCommand("approval.approve", "Approve"),
    disabledBusinessCommand("approval.reject", "Reject"),
  ],
};
