import {
  buildObjectKey,
  isKeyInScope,
  normalizeKey,
  scopePrefix,
} from './storage-keys';
import type { StorageScope } from './object-storage.types';

const TENANT_A: StorageScope = { kind: 'tenant', tenantId: 'tenant-aaa' };
const TENANT_B: StorageScope = { kind: 'tenant', tenantId: 'tenant-bbb' };
const PLATFORM: StorageScope = { kind: 'platform' };

/**
 * These are the tests that decide whether one tenant can reach another tenant's
 * bytes. The audit found that a storage key was effectively a bearer token over
 * the whole file store: two endpoints accepted one as request input and read it
 * back with no ownership check (FILE-03), and keys were handed to browsers and
 * written into audit rows (FILE-18), so they were never secret.
 *
 * The primary remedy is that a key is now always read from a row already
 * fetched under a tenant filter. This module is the second lock, and it is the
 * one that still holds if that discipline ever slips.
 */
describe('storage key scoping', () => {
  describe('isKeyInScope', () => {
    it('accepts a key inside the caller tenant prefix', () => {
      const key = buildObjectKey({
        scope: TENANT_A,
        domain: 'documents',
        segments: ['employee', 'emp-1'],
        originalFileName: 'contract.pdf',
      });

      expect(isKeyInScope(key, TENANT_A)).toBe(true);
    });

    it("refuses another tenant's key even when it is well formed", () => {
      const key = buildObjectKey({
        scope: TENANT_B,
        domain: 'documents',
        originalFileName: 'payslip.pdf',
      });

      // This is the leaked-key case: tenant A knows tenant B's exact key.
      expect(isKeyInScope(key, TENANT_A)).toBe(false);
    });

    it('refuses a tenant prefix that merely shares a leading substring', () => {
      // 'tenant-aaa' must not match 'tenant-aaa-extra'. A prefix check written
      // as a bare startsWith without the separator would let a tenant whose id
      // extends another's read across the boundary.
      const neighbour: StorageScope = {
        kind: 'tenant',
        tenantId: 'tenant-aaa-extra',
      };
      const key = buildObjectKey({ scope: neighbour, domain: 'documents' });

      expect(isKeyInScope(key, TENANT_A)).toBe(false);
      expect(isKeyInScope(key, neighbour)).toBe(true);
    });

    it('refuses the platform namespace to a tenant caller', () => {
      const key = buildObjectKey({ scope: PLATFORM, domain: 'app-releases' });

      expect(isKeyInScope(key, TENANT_A)).toBe(false);
      expect(isKeyInScope(key, PLATFORM)).toBe(true);
    });

    it('refuses a tenant key to a platform caller', () => {
      const key = buildObjectKey({ scope: TENANT_A, domain: 'documents' });

      expect(isKeyInScope(key, PLATFORM)).toBe(false);
    });

    it.each([
      ['parent traversal', 'tenants/tenant-aaa/../tenant-bbb/documents/x.pdf'],
      ['encoded traversal', 'tenants/tenant-aaa/%2e%2e/tenant-bbb/x.pdf'],
      ['double-encoded separator', 'tenants%2ftenant-bbb%2fx.pdf'],
      ['absolute path', '/tenants/tenant-aaa/documents/x.pdf'],
      ['backslash separator', 'tenants\\tenant-aaa\\documents\\x.pdf'],
      ['absolute http url', 'https://evil.example/x.pdf'],
      ['protocol relative url', '//evil.example/x.pdf'],
      ['windows drive', 'C:/windows/system32/config/sam'],
      ['null byte', 'tenants/tenant-aaa/documents/x.pdf\u0000.png'],
      ['empty segment', 'tenants//tenant-aaa/x.pdf'],
      ['bare dot segment', 'tenants/./tenant-aaa/x.pdf'],
      ['empty string', ''],
    ])('refuses %s', (_label, key) => {
      expect(isKeyInScope(key, TENANT_A)).toBe(false);
    });

    it('refuses a traversal that would land back inside the caller scope', () => {
      // Still refused. The key grammar is a whitelist, not a sanitiser: a key
      // that needs normalising to be safe was not generated by us.
      expect(
        isKeyInScope('tenants/tenant-bbb/../tenant-aaa/x.pdf', TENANT_A),
      ).toBe(false);
    });
  });

  describe('normalizeKey', () => {
    it('rejects a key longer than the storage limit', () => {
      expect(normalizeKey(`tenants/tenant-aaa/${'a'.repeat(1100)}`)).toBeNull();
    });

    it('preserves a legitimate key unchanged', () => {
      const key = 'tenants/tenant-aaa/documents/employee/emp-1/2026/09/abc.pdf';
      expect(normalizeKey(key)).toBe(key);
    });
  });

  describe('buildObjectKey', () => {
    it('places the tenant id directly under the tenants root', () => {
      const key = buildObjectKey({ scope: TENANT_A, domain: 'payslips' });
      expect(key.startsWith('tenants/tenant-aaa/payslips/')).toBe(true);
    });

    it('never puts the original filename in the key', () => {
      const key = buildObjectKey({
        scope: TENANT_A,
        domain: 'employees',
        segments: ['emp-1'],
        originalFileName: 'Ayesha Khan passport 4410312345678.pdf',
      });

      // Only the extension survives. Object keys reach logs, bucket listings and
      // provider dashboards, none of which are behind DijiPeople authorization,
      // so a filename carrying a name or a national id must not travel there.
      expect(key).not.toContain('Ayesha');
      expect(key).not.toContain('4410312345678');
      expect(key).not.toContain('passport');
      expect(key.endsWith('.pdf')).toBe(true);
    });

    it('drops an extension that is not a plain short token', () => {
      const key = buildObjectKey({
        scope: TENANT_A,
        domain: 'documents',
        originalFileName: 'payload.php%00.jpg',
      });
      expect(key.endsWith('.jpg')).toBe(true);
    });

    it('rejects a segment that is not an opaque identifier', () => {
      for (const bad of [
        '../escape',
        'has space',
        'has/slash',
        'employee@example.com',
        '',
      ]) {
        expect(() =>
          buildObjectKey({
            scope: TENANT_A,
            domain: 'documents',
            segments: [bad],
          }),
        ).toThrow();
      }
    });

    it('rejects a tenant id that is not an opaque identifier', () => {
      // A malformed tenant id means the authenticated context is wrong. Silently
      // sanitising it would file the object under a namespace nobody intended.
      expect(() =>
        scopePrefix({ kind: 'tenant', tenantId: '../platform' }),
      ).toThrow();
    });

    it('generates a distinct key for every call', () => {
      const keys = new Set(
        Array.from({ length: 50 }, () =>
          buildObjectKey({ scope: TENANT_A, domain: 'documents' }),
        ),
      );
      expect(keys.size).toBe(50);
    });
  });
});
