// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import {
  describeMigrationUrlProblem,
  resolveMigrationDatabaseUrl,
} from '@repo/config';

// Every Prisma CLI call in this repository passes `--config prisma.config.ts`,
// so this one datasource url is what `migrate deploy`, `migrate dev`,
// `migrate status` and `db execute` all connect over.
//
// It is deliberately NOT plain `DATABASE_URL`. The API runs against Neon's
// *pooled* endpoint, which is PgBouncer in transaction pooling mode — fine for
// the runtime, fatal for migrations. `migrate deploy` serialises concurrent
// migrators with a session-scoped advisory lock, and a transaction pooler
// cannot hold one across statements, so the lock is not slow to take: it is
// unobtainable, and every production deploy died on `P1002` after the ten
// second timeout. That was BUG-0086.
//
// `DIRECT_DATABASE_URL` names the direct endpoint for the same database and is
// optional. Unset — local development, CI, any plain Postgres with no pooler in
// front of it — this falls straight back to `DATABASE_URL` and nothing changes.
const migrationDatabaseUrl = resolveMigrationDatabaseUrl(process.env);

// Fail here, and say why, rather than ten seconds later inside Prisma with an
// error that describes a lock timeout and never mentions pooling. This message
// names the variable to set; `P1002` names an advisory lock id.
const migrationUrlProblem = describeMigrationUrlProblem(process.env);
if (migrationUrlProblem) {
  throw new Error(migrationUrlProblem);
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node prisma/seed-demo.ts',
  },
  datasource: {
    url: migrationDatabaseUrl,
  },
});
