-- Complete the explicit monthly and reopening state machines without
-- rewriting any existing status values.
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'NOT_STARTED';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_APPROVED';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'PAYROLL_READY';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'PAYROLL_PROCESSED';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'NOT_REQUIRED';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'AUTO_COMPLETED';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'EXCEPTION';
ALTER TYPE "TimesheetStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE "TimesheetWeekStatus" ADD VALUE IF NOT EXISTS 'REOPENING_REQUESTED';

ALTER TABLE "TimesheetReopeningRequest"
  ADD COLUMN IF NOT EXISTS "previousWeekStatus" "TimesheetWeekStatus";
