-- EXECPLAN-0055 WP-02 / ADR-0027 — platform number sequences and partner numbers.
--
-- Schema (generated by `prisma migrate diff --from-schema <HEAD> --to-schema`):
--   * enum  "NumberSequenceResetPolicy" ('NEVER')
--   * table "PlatformNumberSequence" (platform scope, no tenantId), unique "key"
--   * column "Partner"."partnerNumber" TEXT NULL, unique
--
-- Data transformation (hand-written; the schema cannot express it):
--   1. Every partner with "partnerNumber" IS NULL is numbered in creation order
--      (ORDER BY "createdAt", id) as 'PART-' || six-digit zero-padded value.
--      Numbering starts after the highest value already issued — the larger of
--      the highest existing 'PART-<n>' number and the partner sequence's
--      "nextValue" - 1 — so re-running this block never reissues a number and
--      only numbers partners that still have none.
--   2. The 'partner' sequence row is created with "nextValue" = highest issued
--      number + 1. If the row already exists its format is left alone and
--      "nextValue" is only ever raised (never lowered), for the same reason the
--      settings screen may only raise it: lowering it would reissue a number a
--      partner already carries.
--
-- Additive and repeatable. Rollback is a code revert: the table and the
-- nullable column are unused by older code. `code` is untouched.

-- CreateEnum
CREATE TYPE "NumberSequenceResetPolicy" AS ENUM ('NEVER');

-- AlterTable
ALTER TABLE "Partner" ADD COLUMN     "partnerNumber" TEXT;

-- CreateTable
CREATE TABLE "PlatformNumberSequence" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "prefix" TEXT NOT NULL DEFAULT '',
    "separator" TEXT NOT NULL DEFAULT '',
    "suffix" TEXT NOT NULL DEFAULT '',
    "padding" INTEGER NOT NULL DEFAULT 6,
    "nextValue" INTEGER NOT NULL DEFAULT 1,
    "resetPolicy" "NumberSequenceResetPolicy" NOT NULL DEFAULT 'NEVER',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedById" TEXT,

    CONSTRAINT "PlatformNumberSequence_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PlatformNumberSequence_key_key" ON "PlatformNumberSequence"("key");

-- CreateIndex
CREATE UNIQUE INDEX "Partner_partnerNumber_key" ON "Partner"("partnerNumber");

-- Backfill (1): number existing partners in creation order.
-- lpad() truncates a longer string, so the width is GREATEST(6, length) and a
-- seven-digit value is kept whole rather than silently cut to six.
WITH base AS (
    SELECT GREATEST(
        COALESCE((
            SELECT MAX(substring("partnerNumber" FROM '^PART-([0-9]+)$')::INTEGER)
            FROM "Partner"
            WHERE "partnerNumber" ~ '^PART-[0-9]+$'
        ), 0),
        COALESCE((
            SELECT "nextValue" - 1 FROM "PlatformNumberSequence" WHERE "key" = 'partner'
        ), 0)
    ) AS start_after
),
numbered AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY "createdAt", id) AS rn
    FROM "Partner"
    WHERE "partnerNumber" IS NULL
)
UPDATE "Partner" AS p
SET "partnerNumber" = 'PART-' || lpad(
        (base.start_after + numbered.rn)::TEXT,
        GREATEST(6, length((base.start_after + numbered.rn)::TEXT)),
        '0')
FROM numbered, base
WHERE p.id = numbered.id;

-- Backfill (2): the 'partner' sequence continues after the highest number issued.
INSERT INTO "PlatformNumberSequence"
    ("id", "key", "label", "prefix", "separator", "suffix", "padding", "nextValue", "resetPolicy", "createdAt", "updatedAt")
SELECT
    gen_random_uuid()::TEXT, 'partner', 'Partner number', 'PART-', '', '', 6,
    COALESCE((
        SELECT MAX(substring("partnerNumber" FROM '^PART-([0-9]+)$')::INTEGER)
        FROM "Partner"
        WHERE "partnerNumber" ~ '^PART-[0-9]+$'
    ), 0) + 1,
    'NEVER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
ON CONFLICT ("key") DO UPDATE
    SET "nextValue" = GREATEST("PlatformNumberSequence"."nextValue", EXCLUDED."nextValue");
