import {
  EmployeeGender,
  EmployeeWorkMode,
  JobOpeningStatus,
  RecruitmentStage,
} from '@prisma/client';
import { PERMISSION_KEYS } from '../../../../common/constants/permissions';
import { ENTITY_KEYS } from '../../../../common/constants/rbac-matrix';
import { TENANT_FEATURE_KEYS } from '../../../../common/constants/tenant-features';
import type { ReportDataSource } from '../semantic.types';

/**
 * Recruitment, in four sources.
 *
 *   - **`recruitment_openings`** — requisitions, and whether they are open.
 *   - **`recruitment_candidates`** — people, and where they came from.
 *   - **`recruitment_applications`** — a candidate against an opening. This is
 *     the hire event: an application reaching `HIRED` is one hire.
 *   - **`recruitment_stage_transitions`** — `ApplicationStageHistory`, which is
 *     what makes a funnel and a time-to-hire computable at all. Neither is
 *     derivable from the current stage alone, because an application that
 *     passed through SCREENING and now sits at OFFER carries no trace of the
 *     screening step on the `Application` row.
 *
 * **Stage order comes from `RecruitmentPipelineStage.sortOrder`, never from the
 * `RecruitmentStage` enum's declaration order.** The enum is a fixed vocabulary;
 * the pipeline is tenant-configured, may omit stages, may reorder them, and
 * marks its exits with `isTerminal`. A funnel built on enum ordinal will read
 * correctly for a default pipeline and wrongly for every customised one, which
 * is the worst possible failure mode. The pipeline stage table is not reachable
 * as a relation from any of these four models — an application reaches its
 * pipeline through `jobOpening.pipeline`, and the stages hang off the pipeline —
 * so the ordering has to be loaded by the query planner. That requirement is
 * recorded on the funnel metric rather than left implicit.
 */

export const RECRUITMENT_OPENINGS_SOURCE: ReportDataSource = {
  key: 'recruitment_openings',
  label: 'Job openings',
  description:
    'Requisitions, one row per opening, with their lifecycle status.',
  prismaModel: 'jobOpening',
  rbacEntityKey: ENTITY_KEYS.JOBS,
  scope: {
    organizationIdField: null,
    createdByIdField: 'createdById',
  },
  // A candidate does not belong to a business unit until they are hired.
  // Candidate, Application and JobOpening carry no businessUnitId,
  // organizationId or teamId, so a BUSINESS_UNIT-scoped recruiter has nothing
  // to be narrowed to — denying them everything would be an accident, not a
  // policy. Declared explicitly because it is a widening.
  scopeFallback: 'TENANT_WIDE',
  defaultDateField: 'createdAt',
  recordIdField: 'id',
  requiredFeatureKey: TENANT_FEATURE_KEYS.RECRUITMENT,
  caveats: [
    'JobOpening has no opened-at or closed-at column. A period narrows this source on when the opening record was created, so "openings created this quarter" is answerable and "openings closed this quarter" is not.',
    'There is no headcount or vacancy-count column on an opening, so one opening is one requisition regardless of how many people it is meant to hire.',
  ],
  fields: [
    {
      key: 'recruitment_openings.id',
      label: 'Job opening id',
      type: 'string',
      path: 'id',
      reportable: true,
      filterable: true,
      hidden: true,
    },
    {
      key: 'recruitment_openings.title',
      label: 'Title',
      type: 'string',
      path: 'title',
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'title',
    },
    {
      key: 'recruitment_openings.code',
      label: 'Code',
      type: 'string',
      path: 'code',
      reportable: true,
      filterable: true,
      sortable: true,
    },
    {
      key: 'recruitment_openings.status',
      label: 'Status',
      description:
        'DRAFT, OPEN, ON_HOLD, CLOSED, FILLED or CANCELLED. Only OPEN counts as an open requisition.',
      type: 'enum',
      path: 'status',
      enumValues: Object.values(JobOpeningStatus),
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'status',
    },
    {
      key: 'recruitment_openings.pipeline',
      label: 'Pipeline',
      description: 'Recruitment pipeline the opening runs through.',
      type: 'string',
      path: 'pipeline.name',
      relationPath: ['pipeline'],
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'pipelineId',
      labelLookup: {
        model: 'recruitmentPipeline',
        valueField: 'id',
        labelField: 'name',
      },
      nullLabel: 'No pipeline',
    },
    {
      key: 'recruitment_openings.created_at',
      label: 'Created at',
      description: 'The default period field for this source.',
      type: 'datetime',
      path: 'createdAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
    {
      key: 'recruitment_openings.updated_at',
      label: 'Last updated at',
      type: 'datetime',
      path: 'updatedAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
  ],
};

export const RECRUITMENT_CANDIDATES_SOURCE: ReportDataSource = {
  key: 'recruitment_candidates',
  label: 'Candidates',
  description:
    'People in the recruitment pipeline, one row per candidate, with the channel they arrived through.',
  prismaModel: 'candidate',
  rbacEntityKey: ENTITY_KEYS.CANDIDATES,
  scope: {
    organizationIdField: null,
    createdByIdField: 'createdById',
  },
  // A candidate does not belong to a business unit until they are hired.
  // Candidate, Application and JobOpening carry no businessUnitId,
  // organizationId or teamId, so a BUSINESS_UNIT-scoped recruiter has nothing
  // to be narrowed to — denying them everything would be an accident, not a
  // policy. Declared explicitly because it is a widening.
  scopeFallback: 'TENANT_WIDE',
  defaultDateField: 'createdAt',
  recordIdField: 'id',
  requiredFeatureKey: TENANT_FEATURE_KEYS.RECRUITMENT,
  caveats: [
    'Candidate source is an uncontrolled free-text column. "LinkedIn", "linkedin", "LI referral" and null are four different groups, and no validation prevents that, so a source breakdown is a view of what recruiters typed rather than a channel taxonomy. Read it as indicative and expect a long tail.',
    'Current status is the candidate-level stage, which is not the same as the stage of any one application: a candidate applying to three openings has one status and three application stages.',
    'Salary expectations are restricted and require the compensation read permission.',
  ],
  fields: [
    {
      key: 'recruitment_candidates.id',
      label: 'Candidate id',
      type: 'string',
      path: 'id',
      reportable: true,
      filterable: true,
      hidden: true,
    },
    {
      key: 'recruitment_candidates.first_name',
      label: 'First name',
      type: 'string',
      path: 'firstName',
      reportable: true,
      filterable: true,
      sortable: true,
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_candidates.last_name',
      label: 'Last name',
      type: 'string',
      path: 'lastName',
      reportable: true,
      filterable: true,
      sortable: true,
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_candidates.source',
      label: 'Source',
      description:
        'Free-text channel the candidate came through. Values are uncontrolled; see the source caveat.',
      type: 'string',
      path: 'source',
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'source',
      nullLabel: 'Source not recorded',
    },
    {
      key: 'recruitment_candidates.current_status',
      label: 'Current stage',
      description: 'Candidate-level stage, across all their applications.',
      type: 'enum',
      path: 'currentStatus',
      enumValues: Object.values(RecruitmentStage),
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'currentStatus',
    },
    {
      key: 'recruitment_candidates.gender',
      label: 'Gender',
      description:
        'Self-declared. A null means nothing was recorded, which is a different answer from PREFER_NOT_TO_SAY.',
      type: 'enum',
      path: 'gender',
      enumValues: Object.values(EmployeeGender),
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'gender',
      nullLabel: 'Not recorded',
    },
    {
      key: 'recruitment_candidates.preferred_work_mode',
      label: 'Preferred work mode',
      type: 'enum',
      path: 'preferredWorkMode',
      enumValues: Object.values(EmployeeWorkMode),
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'preferredWorkMode',
      nullLabel: 'Not stated',
    },
    {
      key: 'recruitment_candidates.total_years_experience',
      label: 'Total experience (years)',
      type: 'number',
      path: 'totalYearsExperience',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
    },
    {
      key: 'recruitment_candidates.relevant_years_experience',
      label: 'Relevant experience (years)',
      type: 'number',
      path: 'relevantYearsExperience',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
    },
    {
      key: 'recruitment_candidates.notice_period_days',
      label: 'Notice period (days)',
      type: 'integer',
      path: 'noticePeriodDays',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
    },
    {
      key: 'recruitment_candidates.earliest_joining_date',
      label: 'Earliest joining date',
      type: 'date',
      path: 'earliestJoiningDate',
      format: 'date',
      reportable: true,
      filterable: true,
      sortable: true,
    },
    {
      key: 'recruitment_candidates.willing_to_relocate',
      label: 'Willing to relocate',
      type: 'boolean',
      path: 'willingToRelocate',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'willingToRelocate',
      nullLabel: 'Not stated',
    },
    {
      key: 'recruitment_candidates.current_country',
      label: 'Current country',
      description: 'Free-text country as captured on the candidate record.',
      type: 'string',
      path: 'currentCountry',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'currentCountry',
      nullLabel: 'Not recorded',
    },
    {
      key: 'recruitment_candidates.current_city',
      label: 'Current city',
      description: 'Free-text city as captured on the candidate record.',
      type: 'string',
      path: 'currentCity',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'currentCity',
      nullLabel: 'Not recorded',
    },
    {
      key: 'recruitment_candidates.current_salary',
      label: 'Current salary',
      description:
        'Self-reported current salary. Restricted: requires the compensation read permission.',
      type: 'money',
      path: 'currentSalary',
      format: 'currency',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
      sensitivity: 'RESTRICTED',
      permission: PERMISSION_KEYS.COMPENSATION_READ,
    },
    {
      key: 'recruitment_candidates.expected_salary',
      label: 'Expected salary',
      description:
        'Self-reported salary expectation. Restricted: requires the compensation read permission.',
      type: 'money',
      path: 'expectedSalary',
      format: 'currency',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
      sensitivity: 'RESTRICTED',
      permission: PERMISSION_KEYS.COMPENSATION_READ,
    },
    {
      key: 'recruitment_candidates.created_at',
      label: 'Created at',
      description: 'The default period field for this source.',
      type: 'datetime',
      path: 'createdAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
  ],
};

export const RECRUITMENT_APPLICATIONS_SOURCE: ReportDataSource = {
  key: 'recruitment_applications',
  label: 'Applications',
  description:
    'One candidate against one opening. An application reaching HIRED is one hire.',
  prismaModel: 'application',
  rbacEntityKey: ENTITY_KEYS.CANDIDATES,
  scope: {
    organizationIdField: null,
    // The recruiter who owns the application is the natural SELF scope here.
    ownerUserIdField: 'recruiterOwnerUserId',
    createdByIdField: 'createdById',
  },
  // A candidate does not belong to a business unit until they are hired.
  // Candidate, Application and JobOpening carry no businessUnitId,
  // organizationId or teamId, so a BUSINESS_UNIT-scoped recruiter has nothing
  // to be narrowed to — denying them everything would be an accident, not a
  // policy. Declared explicitly because it is a widening.
  scopeFallback: 'TENANT_WIDE',
  defaultDateField: 'appliedAt',
  recordIdField: 'id',
  requiredFeatureKey: TENANT_FEATURE_KEYS.RECRUITMENT,
  caveats: [
    'Stage is the CURRENT stage. An application now at OFFER leaves no trace on this row of having passed through SCREENING, so a funnel cannot be built from this source — use Stage transitions.',
    'A candidate may apply to several openings, so applications count applications, not people.',
    'Candidate source is reached through the candidate relation. It can be selected and filtered here but not grouped on, because Application carries the candidate id and not the source column; group the Candidates source by source instead.',
  ],
  fields: [
    {
      key: 'recruitment_applications.id',
      label: 'Application id',
      type: 'string',
      path: 'id',
      reportable: true,
      filterable: true,
      hidden: true,
    },
    {
      key: 'recruitment_applications.stage',
      label: 'Current stage',
      description:
        'Where the application stands now. Order stages by the pipeline sort order, never by the enum declaration order.',
      type: 'enum',
      path: 'stage',
      enumValues: Object.values(RecruitmentStage),
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'stage',
    },
    {
      key: 'recruitment_applications.applied_at',
      label: 'Applied at',
      description: 'The default period field for this source.',
      type: 'datetime',
      path: 'appliedAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'appliedAt',
    },
    {
      key: 'recruitment_applications.moved_at',
      label: 'Last stage move at',
      type: 'datetime',
      path: 'movedAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
    {
      key: 'recruitment_applications.rejected_at',
      label: 'Rejected at',
      type: 'datetime',
      path: 'rejectedAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
    {
      key: 'recruitment_applications.rejection_reason',
      label: 'Rejection reason',
      description: 'Free text entered by the recruiter.',
      type: 'string',
      path: 'rejectionReason',
      reportable: true,
      filterable: true,
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_applications.match_score',
      label: 'Match score',
      description: 'Automated match score, when one was computed.',
      type: 'integer',
      path: 'matchScore',
      reportable: true,
      filterable: true,
      sortable: true,
      aggregatable: true,
      supportedAggregations: ['avg', 'min', 'max'],
    },
    {
      key: 'recruitment_applications.recruiter',
      label: 'Recruiter',
      description:
        'Owning recruiter, labelled by their account email — User stores no single display-name column.',
      type: 'string',
      path: 'recruiterOwnerUserId',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'recruiterOwnerUserId',
      labelLookup: { model: 'user', valueField: 'id', labelField: 'email' },
      nullLabel: 'Unassigned',
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_applications.job_opening',
      label: 'Job opening',
      description: 'Opening applied to.',
      type: 'string',
      path: 'jobOpening.title',
      relationPath: ['jobOpening'],
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'jobOpeningId',
      labelLookup: {
        model: 'jobOpening',
        valueField: 'id',
        labelField: 'title',
      },
      nullLabel: 'Unknown opening',
    },
    {
      key: 'recruitment_applications.job_opening_status',
      label: 'Job opening status',
      type: 'enum',
      path: 'jobOpening.status',
      relationPath: ['jobOpening'],
      enumValues: Object.values(JobOpeningStatus),
      reportable: true,
      filterable: true,
      // Application carries `jobOpeningId`, not the opening's status column.
      groupable: false,
    },
    {
      key: 'recruitment_applications.candidate',
      label: 'Candidate',
      description: 'Candidate who applied, labelled by their email address.',
      type: 'string',
      path: 'candidate.email',
      relationPath: ['candidate'],
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'candidateId',
      labelLookup: {
        model: 'candidate',
        valueField: 'id',
        labelField: 'email',
      },
      nullLabel: 'Unknown candidate',
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_applications.candidate_source',
      label: 'Candidate source',
      description:
        'Free-text channel the candidate came through. Selectable and filterable here; group the Candidates source to break down by it.',
      type: 'string',
      path: 'candidate.source',
      relationPath: ['candidate'],
      reportable: true,
      filterable: true,
      groupable: false,
    },
    {
      key: 'recruitment_applications.created_at',
      label: 'Created at',
      type: 'datetime',
      path: 'createdAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
    },
  ],
};

export const RECRUITMENT_STAGE_TRANSITIONS_SOURCE: ReportDataSource = {
  key: 'recruitment_stage_transitions',
  label: 'Stage transitions',
  description:
    'Every recorded stage change on an application. The only source a funnel or a time-to-hire can be computed from.',
  prismaModel: 'applicationStageHistory',
  rbacEntityKey: ENTITY_KEYS.CANDIDATES,
  scope: {
    organizationIdField: null,
    createdByIdField: 'createdById',
  },
  // A candidate does not belong to a business unit until they are hired.
  // Candidate, Application and JobOpening carry no businessUnitId,
  // organizationId or teamId, so a BUSINESS_UNIT-scoped recruiter has nothing
  // to be narrowed to — denying them everything would be an accident, not a
  // policy. Declared explicitly because it is a widening.
  scopeFallback: 'TENANT_WIDE',
  defaultDateField: 'changedAt',
  recordIdField: 'id',
  requiredFeatureKey: TENANT_FEATURE_KEYS.RECRUITMENT,
  caveats: [
    'Transitions exist only from the point the pipeline began recording them. An application older than that appears to jump straight to its current stage.',
    'A backward move is a real row: a pipeline with allowBackwardMove enabled can produce a transition from OFFER back to INTERVIEW, so counting transitions into a stage over-counts the people who reached it.',
    'Stage order must be read from the pipeline configuration, not from the enum. A tenant may omit or reorder stages, and terminal stages are flagged on the pipeline stage row.',
  ],
  fields: [
    {
      key: 'recruitment_stage_transitions.id',
      label: 'Transition id',
      type: 'string',
      path: 'id',
      reportable: true,
      filterable: true,
      hidden: true,
    },
    {
      key: 'recruitment_stage_transitions.from_stage',
      label: 'From stage',
      description:
        'Null on the first transition, when the application was created.',
      type: 'enum',
      path: 'fromStage',
      enumValues: Object.values(RecruitmentStage),
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'fromStage',
      nullLabel: 'Entered pipeline',
    },
    {
      key: 'recruitment_stage_transitions.to_stage',
      label: 'To stage',
      type: 'enum',
      path: 'toStage',
      enumValues: Object.values(RecruitmentStage),
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'toStage',
    },
    {
      key: 'recruitment_stage_transitions.changed_at',
      label: 'Changed at',
      description: 'The default period field for this source.',
      type: 'datetime',
      path: 'changedAt',
      format: 'datetime',
      reportable: true,
      filterable: true,
      sortable: true,
      groupable: true,
      groupByField: 'changedAt',
    },
    {
      key: 'recruitment_stage_transitions.changed_by',
      label: 'Changed by',
      description: 'Account that moved the application, labelled by email.',
      type: 'string',
      path: 'changedByUserId',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'changedByUserId',
      labelLookup: { model: 'user', valueField: 'id', labelField: 'email' },
      nullLabel: 'System',
      sensitivity: 'INTERNAL',
    },
    {
      key: 'recruitment_stage_transitions.application',
      label: 'Application',
      type: 'string',
      path: 'applicationId',
      reportable: true,
      filterable: true,
      groupable: true,
      groupByField: 'applicationId',
    },
    {
      key: 'recruitment_stage_transitions.applied_at',
      label: 'Application applied at',
      description:
        'When the application was raised. Time-to-hire is measured from here to the transition into HIRED.',
      type: 'datetime',
      path: 'application.appliedAt',
      relationPath: ['application'],
      format: 'datetime',
      reportable: true,
      filterable: true,
      groupable: false,
    },
    {
      key: 'recruitment_stage_transitions.job_opening',
      label: 'Job opening',
      description:
        'Opening the application belongs to. Reached through the application, so it cannot be grouped on here.',
      type: 'string',
      path: 'application.jobOpening.title',
      relationPath: ['application', 'jobOpening'],
      reportable: true,
      filterable: true,
      groupable: false,
    },
  ],
};
