ALTER TABLE "AgentTrackingSettings"
ADD COLUMN IF NOT EXISTS "mandatory" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "historyRetentionDays" INTEGER NOT NULL DEFAULT 90,
ADD COLUMN IF NOT EXISTS "installerUrl" TEXT,
ADD COLUMN IF NOT EXISTS "releaseDate" TIMESTAMP(3);
